import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import * as React from "react";
import * as DialogPrimitive from "@radix-ui/react-dialog";
import { X } from "lucide-react";
import { cn } from "@/lib/cn";
export const Dialog = DialogPrimitive.Root;
export const DialogTrigger = DialogPrimitive.Trigger;
export const DialogPortal = DialogPrimitive.Portal;
export const DialogClose = DialogPrimitive.Close;
export const DialogOverlay = React.forwardRef(({ className, ...props }, ref) => (_jsx(DialogPrimitive.Overlay, { ref: ref, className: cn("fixed inset-0 z-50 bg-black/50 backdrop-blur-sm animate-fade-in", className), ...props })));
DialogOverlay.displayName = "DialogOverlay";
export const DialogContent = React.forwardRef(({ className, children, size = "md", ...props }, ref) => (_jsxs(DialogPortal, { children: [_jsx(DialogOverlay, {}), _jsxs(DialogPrimitive.Content, { ref: ref, className: cn("fixed left-1/2 top-1/2 z-50 grid w-full -translate-x-1/2 -translate-y-1/2", "gap-4 border border-border bg-surface-0 p-5 shadow-lg rounded-lg animate-scale-in", size === "sm" && "max-w-sm", size === "md" && "max-w-lg", size === "lg" && "max-w-2xl", size === "xl" && "max-w-4xl", className), ...props, children: [children, _jsxs(DialogPrimitive.Close, { className: cn("absolute right-3 top-3 rounded-sm p-1 text-text-muted", "transition-colors hover:bg-surface-2 hover:text-text-primary", "focus-visible:outline-none focus-visible:shadow-focus", "disabled:pointer-events-none"), children: [_jsx(X, { className: "h-4 w-4" }), _jsx("span", { className: "sr-only", children: "Close" })] })] })] })));
DialogContent.displayName = "DialogContent";
export const DialogHeader = ({ className, ...props }) => (_jsx("div", { className: cn("flex flex-col gap-1 text-left", className), ...props }));
export const DialogFooter = ({ className, ...props }) => (_jsx("div", { className: cn("flex flex-row justify-end gap-2 pt-2 border-t border-border-subtle", className), ...props }));
export const DialogTitle = React.forwardRef(({ className, ...props }, ref) => (_jsx(DialogPrimitive.Title, { ref: ref, className: cn("text-lg font-semibold text-text-primary", className), ...props })));
DialogTitle.displayName = "DialogTitle";
export const DialogDescription = React.forwardRef(({ className, ...props }, ref) => (_jsx(DialogPrimitive.Description, { ref: ref, className: cn("text-sm text-text-muted", className), ...props })));
DialogDescription.displayName = "DialogDescription";
