import { jsx as _jsx } from "react/jsx-runtime";
import * as React from "react";
import * as TabsPrimitive from "@radix-ui/react-tabs";
import { cn } from "@/lib/cn";
export const Tabs = TabsPrimitive.Root;
export const TabsList = React.forwardRef(({ className, ...props }, ref) => (_jsx(TabsPrimitive.List, { ref: ref, className: cn("inline-flex h-9 items-center border-b border-border", className), ...props })));
TabsList.displayName = "TabsList";
export const TabsTrigger = React.forwardRef(({ className, ...props }, ref) => (_jsx(TabsPrimitive.Trigger, { ref: ref, className: cn("relative inline-flex items-center justify-center whitespace-nowrap", "px-3 py-1.5 text-sm font-medium text-text-muted", "transition-colors duration-fast outline-none", "hover:text-text-primary", "focus-visible:text-text-primary focus-visible:shadow-focus", "disabled:pointer-events-none disabled:opacity-50", "data-[state=active]:text-text-primary", "data-[state=active]:after:content-[''] data-[state=active]:after:absolute", "data-[state=active]:after:left-0 data-[state=active]:after:right-0 data-[state=active]:after:-bottom-px data-[state=active]:after:h-0.5 data-[state=active]:after:bg-accent", className), ...props })));
TabsTrigger.displayName = "TabsTrigger";
export const TabsContent = React.forwardRef(({ className, ...props }, ref) => (_jsx(TabsPrimitive.Content, { ref: ref, className: cn("mt-3 outline-none", className), ...props })));
TabsContent.displayName = "TabsContent";
