import { z } from "zod";
import { defineResource, defineListView } from "@/builders";
import type { View } from "@/contracts/views";
import type { ResourceDefinition } from "@/contracts/resources";
import { formViewFromZod } from "../_factory/formFromZod";

/** Extended CRM resources — full ERPNext+ parity.
 *
 *  Everything a modern sales + marketing org expects: Leads, Opportunities,
 *  Campaigns, Appointments, Contracts, Competitors, Market Segments, Sales
 *  Stages. Each resource ships with a Zod schema, list view, and seed data
 *  wired to the shared seed factory in the sales-crm bundle. Detail pages
 *  are auto-generated by the RichDetailPage factory — richer custom pages
 *  can be added per resource in the crm-extended-pages.tsx file.
 *
 *  The original Contact resource + signature pages stay in crm-plugin.ts —
 *  this file adds alongside, keeping every import co-located with the
 *  sales-crm bundle so the plugin ships as one cohesive unit.
 */

/* ================================================================ */
/* Schemas                                                           */
/* ================================================================ */

const LeadSchema = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  email: z.string().email(),
  phone: z.string().optional(),
  company: z.string(),
  title: z.string().optional(),
  source: z.enum([
    "website",
    "referral",
    "cold-outreach",
    "event",
    "partner",
    "advertisement",
    "social",
    "inbound-chat",
  ]),
  status: z.enum(["new", "contacted", "qualified", "unqualified", "converted", "lost"]),
  score: z.number().min(0).max(100),
  owner: z.string(),
  territory: z.string().optional(),
  campaign: z.string().optional(),
  industry: z.string().optional(),
  notes: z.string().optional(),
  createdAt: z.string(),
  updatedAt: z.string(),
  firstResponseAt: z.string().optional(),
  convertedAt: z.string().optional(),
  convertedToOpportunityId: z.string().optional(),
  lostReason: z.string().optional(),
});

const OpportunitySchema = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  account: z.string(),
  contactId: z.string().optional(),
  owner: z.string(),
  stage: z.enum([
    "discovery",
    "qualification",
    "proposal",
    "negotiation",
    "won",
    "lost",
  ]),
  amount: z.number(),
  probability: z.number().min(0).max(100),
  weightedAmount: z.number(),
  closeDate: z.string(),
  source: z.string().optional(),
  campaign: z.string().optional(),
  competitor: z.string().optional(),
  lostReason: z.string().optional(),
  nextStep: z.string().optional(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

const CampaignSchema = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  type: z.enum([
    "email",
    "event",
    "webinar",
    "paid-ads",
    "content",
    "partner",
    "direct-mail",
  ]),
  status: z.enum(["draft", "scheduled", "active", "paused", "completed", "archived"]),
  budget: z.number(),
  spent: z.number(),
  owner: z.string(),
  startAt: z.string(),
  endAt: z.string(),
  leadsGenerated: z.number(),
  opportunitiesGenerated: z.number(),
  revenueGenerated: z.number(),
  targetAudience: z.string().optional(),
  channel: z.string().optional(),
});

const AppointmentSchema = z.object({
  id: z.string(),
  code: z.string(),
  subject: z.string(),
  type: z.enum(["discovery-call", "demo", "follow-up", "onboarding", "check-in"]),
  status: z.enum(["proposed", "confirmed", "completed", "cancelled", "no-show"]),
  contactId: z.string().optional(),
  opportunityId: z.string().optional(),
  assignee: z.string(),
  startAt: z.string(),
  durationMinutes: z.number(),
  location: z.string().optional(),
  meetingUrl: z.string().optional(),
  notes: z.string().optional(),
});

const ContractSchema = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  counterparty: z.string(),
  contactId: z.string().optional(),
  opportunityId: z.string().optional(),
  value: z.number(),
  currency: z.string(),
  startAt: z.string(),
  endAt: z.string(),
  status: z.enum(["draft", "sent", "signed", "active", "renewed", "expired", "terminated"]),
  autoRenew: z.boolean(),
  owner: z.string(),
  templateId: z.string().optional(),
  signedAt: z.string().optional(),
  lastReviewAt: z.string().optional(),
});

const CompetitorSchema = z.object({
  id: z.string(),
  name: z.string(),
  website: z.string().optional(),
  category: z.string(),
  strengths: z.array(z.string()),
  weaknesses: z.array(z.string()),
  winRateVsUs: z.number().min(0).max(100),
  notes: z.string().optional(),
});

const MarketSegmentSchema = z.object({
  id: z.string(),
  name: z.string(),
  industry: z.string(),
  geo: z.string(),
  companySize: z.enum(["SMB", "Mid-Market", "Enterprise"]),
  targetAccountCount: z.number(),
  coveragePct: z.number().min(0).max(100),
  owner: z.string(),
});

const SalesStageSchema = z.object({
  id: z.string(),
  name: z.string(),
  order: z.number(),
  probability: z.number().min(0).max(100),
  description: z.string().optional(),
});

/* ================================================================ */
/* Seed generators                                                   */
/* ================================================================ */

const LEAD_COMPANIES = [
  "Initech", "Umbrella", "Globex", "Tyrell", "Cyberdyne", "Hooli",
  "Stark Industries", "Dunder Mifflin", "Acme Co", "Massive Dynamic",
];
const FIRST_NAMES = ["Ada", "Grace", "Alan", "Linus", "Margaret", "Katherine", "Rachel", "Ken", "Barbara", "Guido"];
const LAST_NAMES = ["Knuth", "Hopper", "Turing", "Torvalds", "Hamilton", "Johnson", "Pappas", "Thompson", "Liskov", "van Rossum"];
const TERRITORIES = ["NA East", "NA West", "EMEA", "APAC", "LATAM"];
const SOURCES = [
  "website", "referral", "cold-outreach", "event", "partner", "advertisement", "social", "inbound-chat",
] as const;
const LEAD_STATUSES = ["new", "contacted", "qualified", "unqualified", "converted", "lost"] as const;
const OPP_STAGES = ["discovery", "qualification", "proposal", "negotiation", "won", "lost"] as const;
const STAGE_PROB: Record<string, number> = {
  discovery: 10,
  qualification: 25,
  proposal: 50,
  negotiation: 75,
  won: 100,
  lost: 0,
};
const CAMPAIGN_TYPES = ["email", "event", "webinar", "paid-ads", "content", "partner", "direct-mail"] as const;
const CAMPAIGN_STATUSES = ["draft", "scheduled", "active", "paused", "completed", "archived"] as const;
const OWNERS = ["sam@gutu.dev", "alex@gutu.dev", "taylor@gutu.dev", "jordan@gutu.dev"];
const LOST_REASONS = ["Budget", "Competitor", "Timing", "No decision", "Feature gap"];

const pick = <T>(arr: readonly T[], i: number): T => arr[i % arr.length];
const personName = (i: number) => `${pick(FIRST_NAMES, i)} ${pick(LAST_NAMES, i + 2)}`;
const daysAgo = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString();
const code = (prefix: string, i: number, pad = 4) =>
  `${prefix}-${String(i + 1).padStart(pad, "0")}`;

function seedLeads(n: number): Record<string, unknown>[] {
  return Array.from({ length: n }, (_, i) => {
    const name = personName(i);
    const status = pick(LEAD_STATUSES, i);
    const createdAt = daysAgo(60 - (i % 60));
    const firstRespDelayMin = (i * 37) % 240;
    return {
      id: `lead_${i + 1}`,
      code: code("LD", i),
      name,
      email: `${name.toLowerCase().replace(/\s+/g, ".")}@${pick(LEAD_COMPANIES, i).toLowerCase().replace(/\s+/g, "-")}.com`,
      phone: `+1-555-${String(1000 + i).slice(-4)}`,
      company: pick(LEAD_COMPANIES, i),
      title: pick(["CTO", "VP Eng", "Head of Ops", "Director", "Founder", "PM"], i),
      source: pick(SOURCES, i),
      status,
      score: 20 + ((i * 13) % 80),
      owner: pick(OWNERS, i),
      territory: pick(TERRITORIES, i),
      campaign: i % 3 === 0 ? `camp_${(i % 10) + 1}` : undefined,
      industry: pick(["SaaS", "Retail", "Manufacturing", "Healthcare", "Finance"], i),
      createdAt,
      updatedAt: daysAgo((i * 0.3) % 30),
      firstResponseAt:
        status !== "new"
          ? new Date(Date.parse(createdAt) + firstRespDelayMin * 60_000).toISOString()
          : undefined,
      convertedAt: status === "converted" ? daysAgo((i * 0.5) % 25) : undefined,
      convertedToOpportunityId: status === "converted" ? `opp_${(i % 30) + 1}` : undefined,
      lostReason: status === "lost" || status === "unqualified" ? pick(LOST_REASONS, i) : undefined,
    };
  });
}

function seedOpportunities(n: number): Record<string, unknown>[] {
  return Array.from({ length: n }, (_, i) => {
    const stage = pick(OPP_STAGES, i);
    const amount = 5_000 + ((i * 3_217) % 195_000);
    const probability = STAGE_PROB[stage];
    return {
      id: `opp_${i + 1}`,
      code: code("OP", i),
      name: `${pick(LEAD_COMPANIES, i)} — ${pick(
        ["expansion", "renewal", "new logo", "upsell", "cross-sell"],
        i,
      )}`,
      account: pick(LEAD_COMPANIES, i),
      contactId: `contact_${(i % 15) + 1}`,
      owner: pick(OWNERS, i),
      stage,
      amount,
      probability,
      weightedAmount: Math.round((amount * probability) / 100),
      closeDate: daysAgo(-7 - (i % 90)),
      source: pick(SOURCES, i),
      campaign: i % 4 === 0 ? `camp_${(i % 10) + 1}` : undefined,
      competitor: i % 5 === 0 ? `comp_${(i % 5) + 1}` : undefined,
      lostReason: stage === "lost" ? pick(LOST_REASONS, i) : undefined,
      nextStep: stage !== "won" && stage !== "lost" ? pick([
        "Schedule demo",
        "Send proposal",
        "Follow up with CTO",
        "Legal review",
        "Pricing discussion",
      ], i) : undefined,
      createdAt: daysAgo(90 - (i % 90)),
      updatedAt: daysAgo((i * 0.4) % 30),
    };
  });
}

function seedCampaigns(n: number): Record<string, unknown>[] {
  return Array.from({ length: n }, (_, i) => {
    const status = pick(CAMPAIGN_STATUSES, i);
    const budget = 5_000 + ((i * 7_537) % 45_000);
    const spent = status === "draft" ? 0 : Math.round(budget * (0.4 + ((i * 0.11) % 0.6)));
    const leads = status === "draft" ? 0 : 10 + ((i * 17) % 200);
    const opps = Math.round(leads * (0.05 + (i * 0.013) % 0.3));
    const revenue = opps * (10_000 + (i * 2137) % 40_000);
    return {
      id: `camp_${i + 1}`,
      code: code("CM", i),
      name: pick(
        [
          "Q1 Webinar Series",
          "EU Expansion Launch",
          "Product-Led Growth Trial",
          "Partner Co-Marketing",
          "Re-engage Dormant",
          "Industry Conference",
          "Content Nurture Track",
          "Paid Search — Enterprise",
          "LinkedIn Outbound",
          "Holiday Promo",
        ],
        i,
      ),
      type: pick(CAMPAIGN_TYPES, i),
      status,
      budget,
      spent,
      owner: pick(OWNERS, i),
      startAt: daysAgo(60 - (i % 60)),
      endAt: daysAgo(-30 + (i % 60)),
      leadsGenerated: leads,
      opportunitiesGenerated: opps,
      revenueGenerated: revenue,
      targetAudience: pick(["SMB", "Mid-Market", "Enterprise", "Existing customers"], i),
      channel: pick(["Email", "LinkedIn", "Webinar", "Conference", "Ads"], i),
    };
  });
}

function seedAppointments(n: number): Record<string, unknown>[] {
  return Array.from({ length: n }, (_, i) => {
    const type = pick(
      ["discovery-call", "demo", "follow-up", "onboarding", "check-in"] as const,
      i,
    );
    const status = pick(
      ["proposed", "confirmed", "completed", "cancelled", "no-show"] as const,
      i,
    );
    return {
      id: `appt_${i + 1}`,
      code: code("AP", i),
      subject: `${pick(["Intro call", "Product demo", "Follow-up on pricing", "Onboarding kickoff", "Quarterly check-in"], i)}`,
      type,
      status,
      contactId: `contact_${(i % 15) + 1}`,
      opportunityId: i % 3 === 0 ? `opp_${(i % 30) + 1}` : undefined,
      assignee: pick(OWNERS, i),
      startAt: daysAgo(-3 + i * 0.7),
      durationMinutes: pick([30, 45, 60, 90], i),
      location: i % 2 === 0 ? undefined : pick(["SF HQ", "NYC Office", "London"], i),
      meetingUrl: `https://meet.gutu.dev/${code("AP", i).toLowerCase()}`,
      notes:
        status === "completed"
          ? pick(
              [
                "Strong interest; next step: proposal.",
                "Pricing objection raised; follow up with discount options.",
                "CTO loved the ingestion rate; loop in security team next.",
                "Wants PoC; send statement of work.",
              ],
              i,
            )
          : undefined,
    };
  });
}

function seedContracts(n: number): Record<string, unknown>[] {
  const CONTRACT_STATUSES = ["draft", "sent", "signed", "active", "renewed", "expired", "terminated"] as const;
  return Array.from({ length: n }, (_, i) => {
    const status = pick(CONTRACT_STATUSES, i);
    const startAt = daysAgo(365 - (i * 7) % 365);
    return {
      id: `ctr_${i + 1}`,
      code: code("CT", i),
      name: `Master Services Agreement — ${pick(LEAD_COMPANIES, i)}`,
      counterparty: pick(LEAD_COMPANIES, i),
      contactId: `contact_${(i % 15) + 1}`,
      opportunityId: `opp_${(i % 30) + 1}`,
      value: 25_000 + ((i * 4_927) % 200_000),
      currency: "USD",
      startAt,
      endAt: new Date(Date.parse(startAt) + 365 * 86_400_000).toISOString(),
      status,
      autoRenew: i % 2 === 0,
      owner: pick(OWNERS, i),
      templateId: pick(["tpl_msa", "tpl_dpa", "tpl_sla"], i),
      signedAt:
        status === "signed" || status === "active" || status === "renewed"
          ? daysAgo(300 - (i * 5) % 300)
          : undefined,
      lastReviewAt: daysAgo((i * 8) % 120),
    };
  });
}

function seedCompetitors(n: number): Record<string, unknown>[] {
  const names = ["Rival A", "Rival B", "Rival C", "Rival D", "Rival E", "Rival F"];
  return Array.from({ length: n }, (_, i) => ({
    id: `comp_${i + 1}`,
    name: pick(names, i),
    website: `https://${pick(names, i).toLowerCase().replace(/\s+/g, "-")}.com`,
    category: pick(["Direct", "Indirect", "Emerging"], i),
    strengths: pick(
      [
        ["Brand recognition", "Marketing spend"],
        ["Low price", "Self-service onboarding"],
        ["Integrations", "Developer mindshare"],
        ["Enterprise relationships", "Compliance certifications"],
      ],
      i,
    ),
    weaknesses: pick(
      [
        ["Poor support SLA", "Clunky UX"],
        ["Limited API", "No multi-tenant"],
        ["Steep pricing", "Lock-in"],
        ["Slow roadmap", "Thin docs"],
      ],
      i,
    ),
    winRateVsUs: 35 + ((i * 11) % 50),
    notes: pick(
      [
        "Tends to win on price in SMB; loses to us on flexibility.",
        "Strong in EU; we win on latency in APAC.",
        "Newer entrant; watch their Series B funding.",
      ],
      i,
    ),
  }));
}

function seedMarketSegments(n: number): Record<string, unknown>[] {
  return Array.from({ length: n }, (_, i) => ({
    id: `seg_${i + 1}`,
    name: pick(
      [
        "EU SaaS Mid-Market",
        "US Enterprise Retail",
        "APAC Fintech SMB",
        "Global Manufacturing",
        "Healthcare Compliance",
        "Public Sector NA",
        "Education & Nonprofit",
        "Hospitality",
      ],
      i,
    ),
    industry: pick(["SaaS", "Retail", "Finance", "Manufacturing", "Healthcare", "Public Sector", "Education", "Hospitality"], i),
    geo: pick(["NA", "EMEA", "APAC", "LATAM", "Global"], i),
    companySize: pick(["SMB", "Mid-Market", "Enterprise"] as const, i),
    targetAccountCount: 50 + ((i * 37) % 450),
    coveragePct: 15 + ((i * 11) % 70),
    owner: pick(OWNERS, i),
  }));
}

function seedSalesStages(): Record<string, unknown>[] {
  return OPP_STAGES.map((s, i) => ({
    id: `stg_${s}`,
    name:
      s === "won"
        ? "Closed Won"
        : s === "lost"
          ? "Closed Lost"
          : s.charAt(0).toUpperCase() + s.slice(1),
    order: i + 1,
    probability: STAGE_PROB[s],
    description:
      s === "discovery"
        ? "Initial conversation; understanding the customer's problem."
        : s === "qualification"
          ? "Confirming budget, authority, need, and timeline."
          : s === "proposal"
            ? "Formal proposal sent; waiting on feedback."
            : s === "negotiation"
              ? "Terms + pricing under active negotiation."
              : s === "won"
                ? "Contract signed. Hand off to onboarding."
                : "Lost — capture reason + save for future re-engagement.",
  }));
}

/* ================================================================ */
/* Resources                                                         */
/* ================================================================ */

function tagSeed<T extends ResourceDefinition>(
  resource: T,
  rows: readonly Record<string, unknown>[],
): T {
  (resource as unknown as { __seed: Record<string, unknown>[] }).__seed = [...rows];
  return resource;
}

export const leadResource = tagSeed(
  defineResource({
    id: "crm.lead",
    singular: "Lead",
    plural: "Leads",
    schema: LeadSchema,
    displayField: "name",
    searchable: ["name", "email", "company", "code"],
    icon: "UserRound",
  }),
  seedLeads(40),
);

export const opportunityResource = tagSeed(
  defineResource({
    id: "crm.opportunity",
    singular: "Opportunity",
    plural: "Opportunities",
    schema: OpportunitySchema,
    displayField: "name",
    searchable: ["name", "account", "code"],
    icon: "Target",
  }),
  seedOpportunities(30),
);

export const campaignResource = tagSeed(
  defineResource({
    id: "crm.campaign",
    singular: "Campaign",
    plural: "Campaigns",
    schema: CampaignSchema,
    displayField: "name",
    searchable: ["name", "code"],
    icon: "Megaphone",
  }),
  seedCampaigns(10),
);

export const appointmentResource = tagSeed(
  defineResource({
    id: "crm.appointment",
    singular: "Appointment",
    plural: "Appointments",
    schema: AppointmentSchema,
    displayField: "subject",
    searchable: ["subject", "code"],
    icon: "Calendar",
  }),
  seedAppointments(20),
);

export const contractResource = tagSeed(
  defineResource({
    id: "crm.contract",
    singular: "Contract",
    plural: "Contracts",
    schema: ContractSchema,
    displayField: "name",
    searchable: ["name", "counterparty", "code"],
    icon: "FileText",
  }),
  seedContracts(15),
);

export const competitorResource = tagSeed(
  defineResource({
    id: "crm.competitor",
    singular: "Competitor",
    plural: "Competitors",
    schema: CompetitorSchema,
    displayField: "name",
    searchable: ["name", "category"],
    icon: "Swords",
  }),
  seedCompetitors(6),
);

export const marketSegmentResource = tagSeed(
  defineResource({
    id: "crm.market-segment",
    singular: "Market Segment",
    plural: "Market Segments",
    schema: MarketSegmentSchema,
    displayField: "name",
    searchable: ["name", "industry"],
    icon: "Target",
  }),
  seedMarketSegments(8),
);

export const salesStageResource = tagSeed(
  defineResource({
    id: "crm.sales-stage",
    singular: "Sales Stage",
    plural: "Sales Stages",
    schema: SalesStageSchema,
    displayField: "name",
    searchable: ["name"],
    icon: "Layers",
  }),
  seedSalesStages(),
);

/* ================================================================ */
/* List views                                                        */
/* ================================================================ */

export const leadListView = defineListView({
  id: "crm.leads.list",
  title: "Leads",
  description: "Every inbound/outbound lead, scored and assigned.",
  resource: "crm.lead",
  search: true,
  pageSize: 25,
  defaultSort: { field: "score", dir: "desc" },
  columns: [
    { field: "code", label: "Code", width: 90, kind: "text" },
    { field: "name", label: "Name", sortable: true },
    { field: "company", label: "Company", sortable: true },
    { field: "score", label: "Score", align: "right", sortable: true, kind: "number" },
    {
      field: "status",
      label: "Status",
      kind: "enum",
      options: [
        { value: "new", label: "New", intent: "info" },
        { value: "contacted", label: "Contacted", intent: "accent" },
        { value: "qualified", label: "Qualified", intent: "success" },
        { value: "unqualified", label: "Unqualified", intent: "warning" },
        { value: "converted", label: "Converted", intent: "success" },
        { value: "lost", label: "Lost", intent: "danger" },
      ],
    },
    {
      field: "source",
      label: "Source",
      kind: "enum",
      options: SOURCES.map((v) => ({ value: v, label: v })),
    },
    { field: "owner", label: "Owner", width: 140 },
    { field: "territory", label: "Territory", width: 120 },
    { field: "updatedAt", label: "Updated", kind: "datetime", sortable: true },
  ],
  filters: [
    {
      field: "status",
      label: "Status",
      kind: "enum",
      options: [
        { value: "new", label: "New" },
        { value: "contacted", label: "Contacted" },
        { value: "qualified", label: "Qualified" },
        { value: "unqualified", label: "Unqualified" },
        { value: "converted", label: "Converted" },
        { value: "lost", label: "Lost" },
      ],
    },
    {
      field: "source",
      label: "Source",
      kind: "enum",
      options: SOURCES.map((v) => ({ value: v, label: v })),
    },
  ],
});

export const opportunityListView = defineListView({
  id: "crm.opportunities.list",
  title: "Opportunities",
  description: "Deals in flight.",
  resource: "crm.opportunity",
  search: true,
  pageSize: 25,
  defaultSort: { field: "closeDate", dir: "asc" },
  columns: [
    { field: "code", label: "Code", width: 90, kind: "text" },
    { field: "name", label: "Name", sortable: true },
    { field: "account", label: "Account", sortable: true },
    { field: "amount", label: "Amount", align: "right", sortable: true, kind: "currency" },
    { field: "probability", label: "Prob %", align: "right", sortable: true, kind: "number" },
    { field: "weightedAmount", label: "Weighted", align: "right", sortable: true, kind: "currency" },
    {
      field: "stage",
      label: "Stage",
      kind: "enum",
      options: [
        { value: "discovery", label: "Discovery", intent: "neutral" },
        { value: "qualification", label: "Qualification", intent: "info" },
        { value: "proposal", label: "Proposal", intent: "accent" },
        { value: "negotiation", label: "Negotiation", intent: "warning" },
        { value: "won", label: "Won", intent: "success" },
        { value: "lost", label: "Lost", intent: "danger" },
      ],
    },
    { field: "closeDate", label: "Close date", kind: "date", sortable: true },
    { field: "owner", label: "Owner", width: 140 },
  ],
  filters: [
    {
      field: "stage",
      label: "Stage",
      kind: "enum",
      options: OPP_STAGES.map((s) => ({ value: s, label: s })),
    },
  ],
});

export const campaignListView = defineListView({
  id: "crm.campaigns.list",
  title: "Campaigns",
  description: "Marketing campaigns with pipeline attribution.",
  resource: "crm.campaign",
  search: true,
  defaultSort: { field: "startAt", dir: "desc" },
  columns: [
    { field: "code", label: "Code", width: 90 },
    { field: "name", label: "Name", sortable: true },
    { field: "type", label: "Type", kind: "enum" },
    {
      field: "status",
      label: "Status",
      kind: "enum",
      options: [
        { value: "draft", label: "Draft", intent: "neutral" },
        { value: "scheduled", label: "Scheduled", intent: "info" },
        { value: "active", label: "Active", intent: "success" },
        { value: "paused", label: "Paused", intent: "warning" },
        { value: "completed", label: "Completed", intent: "accent" },
        { value: "archived", label: "Archived", intent: "neutral" },
      ],
    },
    { field: "budget", label: "Budget", align: "right", kind: "currency" },
    { field: "spent", label: "Spent", align: "right", kind: "currency" },
    { field: "leadsGenerated", label: "Leads", align: "right", kind: "number" },
    { field: "revenueGenerated", label: "Revenue", align: "right", kind: "currency" },
    { field: "startAt", label: "Start", kind: "date", sortable: true },
  ],
});

export const appointmentListView = defineListView({
  id: "crm.appointments.list",
  title: "Appointments",
  description: "Calls, demos, check-ins.",
  resource: "crm.appointment",
  search: true,
  defaultSort: { field: "startAt", dir: "asc" },
  columns: [
    { field: "code", label: "Code", width: 90 },
    { field: "subject", label: "Subject", sortable: true },
    { field: "type", label: "Type", kind: "enum" },
    {
      field: "status",
      label: "Status",
      kind: "enum",
      options: [
        { value: "proposed", label: "Proposed", intent: "info" },
        { value: "confirmed", label: "Confirmed", intent: "accent" },
        { value: "completed", label: "Completed", intent: "success" },
        { value: "cancelled", label: "Cancelled", intent: "neutral" },
        { value: "no-show", label: "No-show", intent: "danger" },
      ],
    },
    { field: "assignee", label: "Assignee" },
    { field: "startAt", label: "Start", kind: "datetime", sortable: true },
    { field: "durationMinutes", label: "Duration (min)", align: "right", kind: "number" },
  ],
});

export const contractListView = defineListView({
  id: "crm.contracts.list",
  title: "Contracts",
  description: "MSAs, DPAs, SLAs.",
  resource: "crm.contract",
  search: true,
  defaultSort: { field: "endAt", dir: "asc" },
  columns: [
    { field: "code", label: "Code", width: 90 },
    { field: "name", label: "Name", sortable: true },
    { field: "counterparty", label: "Counterparty", sortable: true },
    { field: "value", label: "Value", align: "right", kind: "currency" },
    {
      field: "status",
      label: "Status",
      kind: "enum",
      options: [
        { value: "draft", label: "Draft", intent: "neutral" },
        { value: "sent", label: "Sent", intent: "info" },
        { value: "signed", label: "Signed", intent: "accent" },
        { value: "active", label: "Active", intent: "success" },
        { value: "renewed", label: "Renewed", intent: "success" },
        { value: "expired", label: "Expired", intent: "warning" },
        { value: "terminated", label: "Terminated", intent: "danger" },
      ],
    },
    { field: "startAt", label: "Start", kind: "date", sortable: true },
    { field: "endAt", label: "End", kind: "date", sortable: true },
    { field: "autoRenew", label: "Auto-renew", kind: "boolean" },
    { field: "owner", label: "Owner", width: 140 },
  ],
});

export const competitorListView = defineListView({
  id: "crm.competitors.list",
  title: "Competitors",
  description: "Battlecards + win-rate intel.",
  resource: "crm.competitor",
  columns: [
    { field: "name", label: "Name", sortable: true },
    { field: "category", label: "Category", kind: "enum" },
    { field: "winRateVsUs", label: "Win % vs us", align: "right", kind: "number" },
    { field: "website", label: "Website" },
  ],
});

export const marketSegmentListView = defineListView({
  id: "crm.market-segments.list",
  title: "Market Segments",
  description: "Target account lists.",
  resource: "crm.market-segment",
  columns: [
    { field: "name", label: "Name", sortable: true },
    { field: "industry", label: "Industry", kind: "enum" },
    { field: "geo", label: "Geo", width: 90 },
    { field: "companySize", label: "Size", kind: "enum" },
    { field: "targetAccountCount", label: "Target accts", align: "right", kind: "number" },
    { field: "coveragePct", label: "Coverage %", align: "right", kind: "number" },
    { field: "owner", label: "Owner" },
  ],
});

export const salesStageListView = defineListView({
  id: "crm.sales-stages.list",
  title: "Sales Stages",
  description: "Pipeline stage definitions with win probabilities.",
  resource: "crm.sales-stage",
  defaultSort: { field: "order", dir: "asc" },
  columns: [
    { field: "order", label: "Order", align: "right", width: 60 },
    { field: "name", label: "Name", sortable: true },
    { field: "probability", label: "Probability %", align: "right", kind: "number" },
    { field: "description", label: "Description" },
  ],
});

/* ================================================================ */
/* Exports                                                           */
/* ================================================================ */

export const CRM_EXTENDED_RESOURCES: readonly ResourceDefinition[] = [
  leadResource,
  opportunityResource,
  campaignResource,
  appointmentResource,
  contractResource,
  competitorResource,
  marketSegmentResource,
  salesStageResource,
];

/* ================================================================ */
/* Auto-generated form views from Zod schemas                        */
/* ================================================================ */

const leadFormView = formViewFromZod({
  id: "crm.lead.form",
  title: "Lead",
  resource: "crm.lead",
  schema: LeadSchema,
  exclude: ["id", "score"],
  defaults: { status: "new", source: "website", score: 50 },
  columns: 2,
});

const opportunityFormView = formViewFromZod({
  id: "crm.opportunity.form",
  title: "Opportunity",
  resource: "crm.opportunity",
  schema: OpportunitySchema,
  exclude: ["id", "weightedAmount"],
  defaults: { stage: "discovery", probability: 10, amount: 0 },
  columns: 2,
});

const campaignFormView = formViewFromZod({
  id: "crm.campaign.form",
  title: "Campaign",
  resource: "crm.campaign",
  schema: CampaignSchema,
  exclude: ["id"],
  defaults: {
    status: "draft",
    type: "email",
    budget: 0,
    spent: 0,
    leadsGenerated: 0,
    opportunitiesGenerated: 0,
    revenueGenerated: 0,
  },
  columns: 2,
});

const appointmentFormView = formViewFromZod({
  id: "crm.appointment.form",
  title: "Appointment",
  resource: "crm.appointment",
  schema: AppointmentSchema,
  exclude: ["id"],
  defaults: { status: "proposed", type: "discovery-call", durationMinutes: 30 },
  columns: 2,
});

const contractFormView = formViewFromZod({
  id: "crm.contract.form",
  title: "Contract",
  resource: "crm.contract",
  schema: ContractSchema,
  exclude: ["id"],
  defaults: {
    status: "draft",
    autoRenew: false,
    currency: "USD",
    value: 0,
  },
  columns: 2,
});

const competitorFormView = formViewFromZod({
  id: "crm.competitor.form",
  title: "Competitor",
  resource: "crm.competitor",
  schema: CompetitorSchema,
  exclude: ["id"],
  defaults: { winRateVsUs: 50, strengths: [], weaknesses: [] },
  columns: 2,
});

const marketSegmentFormView = formViewFromZod({
  id: "crm.market-segment.form",
  title: "Market Segment",
  resource: "crm.market-segment",
  schema: MarketSegmentSchema,
  exclude: ["id"],
  defaults: { companySize: "SMB", targetAccountCount: 100, coveragePct: 0 },
  columns: 2,
});

const salesStageFormView = formViewFromZod({
  id: "crm.sales-stage.form",
  title: "Sales Stage",
  resource: "crm.sales-stage",
  schema: SalesStageSchema,
  exclude: ["id"],
  defaults: { order: 1, probability: 10 },
  columns: 2,
});

export const CRM_EXTENDED_VIEWS: readonly View[] = [
  leadListView,
  leadFormView,
  opportunityListView,
  opportunityFormView,
  campaignListView,
  campaignFormView,
  appointmentListView,
  appointmentFormView,
  contractListView,
  contractFormView,
  competitorListView,
  competitorFormView,
  marketSegmentListView,
  marketSegmentFormView,
  salesStageListView,
  salesStageFormView,
];
