import { buildDomainPlugin } from "./_factory/buildDomainPlugin";
import { SECTIONS } from "./_factory/sections";
import { CITIES, code, daysAgo, daysFromNow, personName, pick } from "./_factory/seeds";
import { assetsControlRoomView, assetsReportsIndexView, assetsReportsDetailView, } from "./assets-dashboard";
const DEPARTMENTS = ["Engineering", "Sales", "Marketing", "Operations", "Finance", "Support", "HR"];
export const assetsPlugin = buildDomainPlugin({
    id: "assets",
    label: "Assets",
    icon: "Package",
    section: SECTIONS.supplyChain,
    order: 5,
    resources: [
        {
            id: "asset",
            singular: "Asset",
            plural: "Assets",
            icon: "Package",
            path: "/assets",
            displayField: "tag",
            defaultSort: { field: "purchasedAt", dir: "desc" },
            pageSize: 25,
            fields: [
                { name: "tag", kind: "text", required: true, sortable: true, width: 120 },
                { name: "name", kind: "text", required: true, sortable: true },
                { name: "category", kind: "enum", options: [
                        { value: "laptop", label: "Laptop" },
                        { value: "vehicle", label: "Vehicle" },
                        { value: "equipment", label: "Equipment" },
                        { value: "machinery", label: "Machinery" },
                        { value: "furniture", label: "Furniture" },
                        { value: "real-estate", label: "Real estate" },
                        { value: "intangible", label: "Intangible" },
                    ], sortable: true },
                { name: "serialNumber", kind: "text", width: 150 },
                { name: "vendor", kind: "text" },
                { name: "modelNumber", kind: "text" },
                { name: "location", kind: "text" },
                { name: "department", kind: "enum", options: DEPARTMENTS.map((d) => ({ value: d, label: d })), sortable: true },
                { name: "assignee", kind: "text" },
                { name: "status", kind: "enum", required: true, options: [
                        { value: "deployed", label: "Deployed", intent: "success" },
                        { value: "in_storage", label: "In storage", intent: "neutral" },
                        { value: "maintenance", label: "Maintenance", intent: "warning" },
                        { value: "retired", label: "Retired", intent: "danger" },
                        { value: "lost", label: "Lost", intent: "danger" },
                    ], sortable: true },
                { name: "purchasedAt", kind: "date", sortable: true, width: 130 },
                { name: "warrantyEndsAt", kind: "date", sortable: true, width: 130 },
                { name: "nextServiceAt", kind: "date", sortable: true, width: 130 },
                { name: "usefulLifeYears", kind: "number", align: "right", width: 110 },
                { name: "cost", kind: "currency", align: "right", sortable: true },
                { name: "salvageValue", kind: "currency", align: "right" },
                { name: "netBookValue", kind: "currency", align: "right", readonly: true },
                { name: "depreciationMethod", kind: "enum", options: [
                        { value: "straight-line", label: "Straight-line" },
                        { value: "double-declining", label: "Double-declining" },
                        { value: "units-of-production", label: "Units of production" },
                        { value: "none", label: "None" },
                    ] },
                { name: "maintenanceDueSoon", kind: "boolean", width: 140 },
                { name: "notes", kind: "textarea", formSection: "Notes" },
            ],
            seedCount: 40,
            seed: (i) => {
                const cost = 500 + ((i * 1097) % 40000);
                const life = pick([3, 5, 7, 10], i);
                const ageYrs = Math.min(life, (i * 2) % (life + 1));
                const salvage = Math.round(cost * 0.1);
                const nbv = Math.max(salvage, Math.round(cost - ((cost - salvage) * ageYrs) / life));
                return {
                    tag: code("AST", i, 5),
                    name: pick(["MacBook Pro", "Dell XPS", "Ford Transit", "Forklift", "Scanner", "Desk", "Chair", "Server"], i),
                    category: pick(["laptop", "vehicle", "equipment", "machinery", "furniture"], i),
                    serialNumber: `SN-${String(100000 + i * 37).slice(-6)}`,
                    vendor: pick(["Apple", "Dell", "Ford", "Crown", "Zebra", "Herman Miller"], i),
                    modelNumber: pick(["M3 Pro", "XPS 15", "Transit 250", "FC-40", "DS8178"], i),
                    location: pick(CITIES, i),
                    department: pick(DEPARTMENTS, i),
                    assignee: personName(i),
                    status: pick(["deployed", "deployed", "deployed", "in_storage", "maintenance", "retired"], i),
                    purchasedAt: daysAgo(i * 30),
                    warrantyEndsAt: daysFromNow(365 - i * 10),
                    nextServiceAt: daysFromNow(30 + (i * 17) % 180),
                    usefulLifeYears: life,
                    cost,
                    salvageValue: salvage,
                    netBookValue: nbv,
                    depreciationMethod: pick(["straight-line", "double-declining", "units-of-production"], i),
                    maintenanceDueSoon: ((i * 17) % 180) < 30,
                    notes: "",
                };
            },
        },
        {
            id: "assignment",
            singular: "Assignment",
            plural: "Assignments",
            icon: "UserCheck",
            path: "/assets/assignments",
            defaultSort: { field: "assignedAt", dir: "desc" },
            fields: [
                { name: "assetTag", label: "Asset", kind: "text", required: true, sortable: true },
                { name: "assignee", kind: "text", required: true, sortable: true },
                { name: "department", kind: "enum", options: DEPARTMENTS.map((d) => ({ value: d, label: d })) },
                { name: "location", kind: "text" },
                { name: "assignedAt", kind: "date", required: true, sortable: true, width: 130 },
                { name: "returnedAt", kind: "date" },
                { name: "status", kind: "enum", required: true, options: [
                        { value: "active", label: "Active", intent: "success" },
                        { value: "returned", label: "Returned", intent: "neutral" },
                    ] },
                { name: "notes", kind: "textarea", formSection: "Notes" },
            ],
            seedCount: 30,
            seed: (i) => ({
                assetTag: code("AST", i, 5),
                assignee: personName(i),
                department: pick(DEPARTMENTS, i),
                location: pick(CITIES, i),
                assignedAt: daysAgo(60 - i * 2),
                returnedAt: i % 4 === 0 ? daysAgo(i) : "",
                status: i % 4 === 0 ? "returned" : "active",
                notes: "",
            }),
        },
        {
            id: "depreciation-entry",
            singular: "Depreciation Entry",
            plural: "Depreciation Entries",
            icon: "TrendingDown",
            path: "/assets/depreciation",
            defaultSort: { field: "postedAt", dir: "desc" },
            fields: [
                { name: "assetTag", kind: "text", required: true, sortable: true },
                { name: "period", kind: "text", required: true, sortable: true, width: 110 },
                { name: "method", kind: "enum", options: [
                        { value: "straight-line", label: "Straight-line" },
                        { value: "double-declining", label: "Double-declining" },
                    ] },
                { name: "amount", kind: "currency", required: true, align: "right", sortable: true },
                { name: "accumulated", kind: "currency", align: "right" },
                { name: "postedAt", kind: "date", sortable: true, width: 130 },
            ],
            seedCount: 48,
            seed: (i) => {
                const amount = 100 + (i * 71) % 900;
                return {
                    assetTag: code("AST", i % 40, 5),
                    period: `2026-${String(((i % 12) + 1)).padStart(2, "0")}`,
                    method: pick(["straight-line", "double-declining"], i),
                    amount,
                    accumulated: amount * (1 + Math.floor(i / 12)),
                    postedAt: daysAgo(i * 3),
                };
            },
        },
        {
            id: "asset-transfer",
            singular: "Asset Transfer",
            plural: "Asset Transfers",
            icon: "ArrowLeftRight",
            path: "/assets/transfers",
            defaultSort: { field: "transferredAt", dir: "desc" },
            fields: [
                { name: "code", kind: "text", required: true, sortable: true },
                { name: "assetTag", kind: "text", required: true, sortable: true },
                { name: "fromLocation", kind: "text" },
                { name: "toLocation", kind: "text" },
                { name: "fromAssignee", kind: "text" },
                { name: "toAssignee", kind: "text" },
                { name: "reason", kind: "enum", options: [
                        { value: "relocation", label: "Relocation" },
                        { value: "reassignment", label: "Reassignment" },
                        { value: "maintenance", label: "Maintenance" },
                        { value: "retirement", label: "Retirement" },
                    ] },
                { name: "transferredAt", kind: "date", required: true, sortable: true },
                { name: "status", kind: "enum", options: [
                        { value: "pending", label: "Pending", intent: "warning" },
                        { value: "in-transit", label: "In transit", intent: "info" },
                        { value: "completed", label: "Completed", intent: "success" },
                    ] },
            ],
            seedCount: 14,
            seed: (i) => ({
                code: code("TFR", i, 5),
                assetTag: code("AST", i * 2, 5),
                fromLocation: pick(CITIES, i),
                toLocation: pick(CITIES, i + 3),
                fromAssignee: personName(i),
                toAssignee: personName(i + 4),
                reason: pick(["relocation", "reassignment", "maintenance", "retirement"], i),
                transferredAt: daysAgo(i * 10),
                status: pick(["completed", "completed", "in-transit", "pending"], i),
            }),
        },
        {
            id: "disposal",
            singular: "Asset Disposal",
            plural: "Asset Disposals",
            icon: "Trash2",
            path: "/assets/disposals",
            fields: [
                { name: "code", kind: "text", required: true, sortable: true },
                { name: "assetTag", kind: "text", required: true, sortable: true },
                { name: "method", kind: "enum", options: [
                        { value: "sold", label: "Sold" },
                        { value: "scrapped", label: "Scrapped" },
                        { value: "donated", label: "Donated" },
                        { value: "lost", label: "Lost/stolen" },
                    ] },
                { name: "disposedAt", kind: "date", sortable: true },
                { name: "proceeds", kind: "currency", align: "right" },
                { name: "gainLoss", kind: "currency", align: "right" },
                { name: "notes", kind: "textarea", formSection: "Notes" },
            ],
            seedCount: 8,
            seed: (i) => {
                const proceeds = pick([100, 500, 0, 1500, 50], i);
                return {
                    code: code("DSP", i, 5),
                    assetTag: code("AST", 30 + i, 5),
                    method: pick(["sold", "scrapped", "donated", "lost"], i),
                    disposedAt: daysAgo(i * 30),
                    proceeds,
                    gainLoss: proceeds - (500 + (i * 137) % 1500),
                    notes: "",
                };
            },
        },
        {
            id: "audit",
            singular: "Asset Audit",
            plural: "Asset Audits",
            icon: "ClipboardCheck",
            path: "/assets/audits",
            defaultSort: { field: "conductedAt", dir: "desc" },
            fields: [
                { name: "code", kind: "text", required: true, sortable: true },
                { name: "scope", kind: "text" },
                { name: "auditor", kind: "text" },
                { name: "conductedAt", kind: "date", required: true, sortable: true },
                { name: "assetsChecked", kind: "number", align: "right" },
                { name: "missing", kind: "number", align: "right" },
                { name: "discrepancies", kind: "number", align: "right" },
                { name: "status", kind: "enum", options: [
                        { value: "planned", label: "Planned", intent: "info" },
                        { value: "in-progress", label: "In progress", intent: "warning" },
                        { value: "completed", label: "Completed", intent: "success" },
                    ] },
            ],
            seedCount: 6,
            seed: (i) => ({
                code: code("AAU", i, 5),
                scope: pick(["HQ laptops", "Factory machinery", "All vehicles", "Furniture annual"], i),
                auditor: personName(i),
                conductedAt: daysAgo(i * 60),
                assetsChecked: 20 + (i * 13) % 80,
                missing: i % 5,
                discrepancies: (i * 3) % 15,
                status: pick(["completed", "completed", "in-progress", "planned"], i),
            }),
        },
    ],
    extraNav: [
        { id: "assets.control-room.nav", label: "Assets Control Room", icon: "LayoutDashboard", path: "/assets/control-room", view: "assets.control-room.view", order: 0 },
        { id: "assets.reports.nav", label: "Reports", icon: "BarChart3", path: "/assets/reports", view: "assets.reports.view" },
    ],
    extraViews: [
        assetsControlRoomView,
        assetsReportsIndexView,
        assetsReportsDetailView,
    ],
    commands: [
        { id: "assets.go.control-room", label: "Assets: Control Room", icon: "LayoutDashboard", run: () => { window.location.hash = "/assets/control-room"; } },
        { id: "assets.go.reports", label: "Assets: Reports", icon: "BarChart3", run: () => { window.location.hash = "/assets/reports"; } },
        { id: "assets.new", label: "New asset", icon: "Plus", run: () => { window.location.hash = "/assets/new"; } },
        { id: "assets.new-assignment", label: "Assign asset", icon: "UserCheck", run: () => { window.location.hash = "/assets/assignments/new"; } },
        { id: "assets.new-audit", label: "New audit", icon: "ClipboardCheck", run: () => { window.location.hash = "/assets/audits/new"; } },
    ],
});
