import { buildDomainPlugin } from "./_factory/buildDomainPlugin";
import { SECTIONS } from "./_factory/sections";
import { STATUS_ACTIVE } from "./_factory/options";
import { personEmail, personName, daysAgo, hoursAgo, daysFromNow, pick } from "./_factory/seeds";
import { authControlRoomView, authReportsIndexView, authReportsDetailView, } from "./auth-dashboard";
export const authPlugin = buildDomainPlugin({
    id: "auth",
    label: "Auth",
    icon: "Lock",
    section: SECTIONS.people,
    order: 1,
    resources: [
        {
            id: "user",
            singular: "User",
            plural: "Users",
            icon: "UserCircle",
            path: "/auth/users",
            defaultSort: { field: "lastLogin", dir: "desc" },
            pageSize: 25,
            fields: [
                { name: "name", kind: "text", required: true, sortable: true },
                { name: "email", kind: "email", required: true, sortable: true },
                { name: "role", kind: "enum", options: [
                        { value: "admin", label: "Admin", intent: "danger" },
                        { value: "member", label: "Member", intent: "info" },
                        { value: "viewer", label: "Viewer", intent: "neutral" },
                        { value: "owner", label: "Owner", intent: "accent" },
                        { value: "billing", label: "Billing", intent: "warning" },
                    ], sortable: true },
                { name: "status", kind: "enum", options: [
                        { value: "active", label: "Active", intent: "success" },
                        { value: "invited", label: "Invited", intent: "info" },
                        { value: "suspended", label: "Suspended", intent: "warning" },
                        { value: "deleted", label: "Deleted", intent: "danger" },
                    ] },
                { name: "department", kind: "text" },
                { name: "mfa", label: "MFA", kind: "boolean" },
                { name: "mfaEnrolledNumeric", label: "MFA %", kind: "number", align: "right", readonly: true },
                { name: "ssoProvider", kind: "enum", options: [
                        { value: "google", label: "Google" },
                        { value: "microsoft", label: "Microsoft" },
                        { value: "okta", label: "Okta" },
                        { value: "email", label: "Email + password" },
                        { value: "none", label: "None" },
                    ] },
                { name: "lastLogin", kind: "datetime", sortable: true },
                { name: "inactiveOver90d", kind: "boolean", width: 130 },
                { name: "createdAt", kind: "date", sortable: true },
                { name: "locale", kind: "text", width: 90 },
                { name: "timezone", kind: "text" },
            ],
            seedCount: 40,
            seed: (i) => {
                const lastLogin = hoursAgo(i * 4);
                return {
                    name: personName(i),
                    email: personEmail(i, "gutu.dev"),
                    role: pick(["admin", "member", "member", "member", "viewer", "owner", "billing"], i),
                    status: pick(["active", "active", "active", "active", "invited", "suspended"], i),
                    department: pick(["Engineering", "Ops", "Sales", "Marketing", "Finance", "Support"], i),
                    mfa: i % 3 !== 0,
                    mfaEnrolledNumeric: i % 3 !== 0 ? 100 : 0,
                    ssoProvider: pick(["google", "microsoft", "okta", "email"], i),
                    lastLogin,
                    inactiveOver90d: (Date.now() - Date.parse(lastLogin)) / 86_400_000 > 90,
                    createdAt: daysAgo(i * 20),
                    locale: pick(["en-US", "en-GB", "de-DE", "ja-JP"], i),
                    timezone: pick(["America/Los_Angeles", "America/New_York", "Europe/London", "Asia/Tokyo"], i),
                };
            },
        },
        {
            id: "session",
            singular: "Session",
            plural: "Sessions",
            icon: "Fingerprint",
            path: "/auth/sessions",
            readOnly: true,
            displayField: "id",
            defaultSort: { field: "createdAt", dir: "desc" },
            fields: [
                { name: "user", kind: "text", sortable: true },
                { name: "ip", kind: "text", width: 140 },
                { name: "userAgent", label: "User Agent", kind: "text" },
                { name: "provider", kind: "enum", options: [
                        { value: "google", label: "Google" },
                        { value: "microsoft", label: "Microsoft" },
                        { value: "okta", label: "Okta" },
                        { value: "password", label: "Password" },
                        { value: "magic-link", label: "Magic link" },
                    ] },
                { name: "location", kind: "text" },
                { name: "active", kind: "boolean" },
                { name: "createdAt", kind: "datetime", sortable: true },
                { name: "expiresAt", kind: "datetime", sortable: true },
            ],
            seedCount: 30,
            seed: (i) => ({
                user: personEmail(i, "gutu.dev"),
                ip: `10.0.${i}.${(i * 7) % 255}`,
                userAgent: pick(["Safari/17", "Chrome/131", "Firefox/133", "iOS Safari"], i),
                provider: pick(["google", "microsoft", "okta", "password", "magic-link"], i),
                location: pick(["San Francisco, USA", "New York, USA", "London, UK", "Tokyo, JP"], i),
                active: i < 20,
                createdAt: daysAgo(i * 0.5),
                expiresAt: daysFromNow(30 - i * 0.5),
            }),
        },
        {
            id: "role",
            singular: "Role",
            plural: "Roles",
            icon: "ShieldCheck",
            path: "/auth/roles",
            fields: [
                { name: "key", label: "Key", kind: "text", required: true, sortable: true, width: 130 },
                { name: "name", kind: "text", required: true, sortable: true },
                { name: "description", kind: "textarea", formSection: "About" },
                { name: "members", kind: "number", align: "right" },
                { name: "permissions", kind: "number", align: "right" },
                { name: "system", label: "System role", kind: "boolean", width: 130 },
            ],
            seedCount: 8,
            seed: (i) => ({
                key: pick(["owner", "admin", "billing", "member", "viewer", "support", "engineering", "custom"], i),
                name: pick(["Owner", "Admin", "Billing", "Member", "Viewer", "Support Agent", "Engineer", "Custom"], i),
                description: "Role description",
                members: 1 + (i * 3) % 30,
                permissions: 5 + (i * 2) % 30,
                system: i < 5,
            }),
        },
        {
            id: "permission",
            singular: "Permission",
            plural: "Permissions",
            icon: "Key",
            path: "/auth/permissions",
            fields: [
                { name: "key", kind: "text", required: true, sortable: true },
                { name: "resource", kind: "text", sortable: true },
                { name: "action", kind: "enum", options: [
                        { value: "read", label: "Read" },
                        { value: "write", label: "Write" },
                        { value: "delete", label: "Delete" },
                        { value: "admin", label: "Admin" },
                    ] },
                { name: "description", kind: "text" },
            ],
            seedCount: 20,
            seed: (i) => ({
                key: `${pick(["read", "write", "delete"], i)}.${pick(["invoice", "contact", "user", "role"], i)}`,
                resource: pick(["accounting.invoice", "crm.contact", "auth.user", "auth.role"], i),
                action: pick(["read", "write", "delete", "admin"], i),
                description: "",
            }),
        },
        {
            id: "invitation",
            singular: "Invitation",
            plural: "Invitations",
            icon: "Mail",
            path: "/auth/invitations",
            displayField: "email",
            defaultSort: { field: "invitedAt", dir: "desc" },
            fields: [
                { name: "email", kind: "email", required: true, sortable: true },
                { name: "role", kind: "text", required: true },
                { name: "invitedBy", kind: "text" },
                { name: "invitedAt", kind: "datetime", sortable: true },
                { name: "expiresAt", kind: "datetime" },
                { name: "status", kind: "enum", options: [
                        { value: "pending", label: "Pending", intent: "warning" },
                        { value: "accepted", label: "Accepted", intent: "success" },
                        { value: "expired", label: "Expired", intent: "neutral" },
                        { value: "revoked", label: "Revoked", intent: "danger" },
                    ] },
            ],
            seedCount: 14,
            seed: (i) => ({
                email: `invited+${i}@example.com`,
                role: pick(["admin", "member", "viewer"], i),
                invitedBy: "sam@gutu.dev",
                invitedAt: daysAgo(i * 3),
                expiresAt: daysFromNow(30 - i * 2),
                status: pick(["pending", "accepted", "accepted", "expired", "revoked"], i),
            }),
        },
        {
            id: "api-token",
            singular: "API Token",
            plural: "API Tokens",
            icon: "Key",
            path: "/auth/api-tokens",
            displayField: "name",
            fields: [
                { name: "name", kind: "text", required: true, sortable: true },
                { name: "owner", kind: "text", sortable: true },
                { name: "scopes", kind: "multi-enum", options: [
                        { value: "read", label: "Read" },
                        { value: "write", label: "Write" },
                        { value: "admin", label: "Admin" },
                        { value: "webhook", label: "Webhook" },
                    ] },
                { name: "prefix", kind: "text", width: 140 },
                { name: "lastUsedAt", kind: "datetime", sortable: true },
                { name: "createdAt", kind: "date" },
                { name: "expiresAt", kind: "date" },
                { name: "revoked", kind: "boolean" },
            ],
            seedCount: 10,
            seed: (i) => ({
                name: pick(["CI deploy token", "Integration: Slack", "Integration: GitHub", "Readonly reports", "Webhook relay"], i),
                owner: personEmail(i, "gutu.dev"),
                scopes: pick([["read"], ["read", "write"], ["admin"], ["webhook"]], i),
                prefix: `gutu_${pick(["pat", "svc", "wh"], i)}_${String(1000 + i).slice(-4)}`,
                lastUsedAt: hoursAgo(i * 8),
                createdAt: daysAgo(i * 30),
                expiresAt: daysFromNow(365),
                revoked: i % 7 === 6,
            }),
        },
        {
            id: "login-event",
            singular: "Login Event",
            plural: "Login Events",
            icon: "LogIn",
            path: "/auth/login-events",
            readOnly: true,
            displayField: "id",
            defaultSort: { field: "occurredAt", dir: "desc" },
            fields: [
                { name: "occurredAt", kind: "datetime", sortable: true },
                { name: "user", kind: "text", sortable: true },
                { name: "ip", kind: "text" },
                { name: "userAgent", label: "User Agent", kind: "text" },
                { name: "provider", kind: "enum", options: [
                        { value: "google", label: "Google" },
                        { value: "microsoft", label: "Microsoft" },
                        { value: "okta", label: "Okta" },
                        { value: "password", label: "Password" },
                        { value: "magic-link", label: "Magic link" },
                    ] },
                { name: "success", kind: "boolean" },
                { name: "reason", kind: "text" },
            ],
            seedCount: 60,
            seed: (i) => {
                const success = i % 5 !== 4;
                return {
                    occurredAt: hoursAgo(i * 2),
                    user: personEmail(i, "gutu.dev"),
                    ip: `10.0.${i % 255}.${(i * 7) % 255}`,
                    userAgent: pick(["Safari/17", "Chrome/131", "Firefox/133", "iOS Safari"], i),
                    provider: pick(["google", "microsoft", "okta", "password", "magic-link"], i),
                    success,
                    reason: success ? "" : pick(["bad-password", "mfa-failed", "account-locked"], i),
                };
            },
        },
        {
            id: "ip-policy",
            singular: "IP Policy",
            plural: "IP Policies",
            icon: "Shield",
            path: "/auth/ip-policies",
            fields: [
                { name: "name", kind: "text", required: true, sortable: true },
                { name: "cidr", kind: "text", required: true, width: 160 },
                { name: "action", kind: "enum", options: [
                        { value: "allow", label: "Allow", intent: "success" },
                        { value: "deny", label: "Deny", intent: "danger" },
                    ] },
                { name: "appliesTo", kind: "text" },
                { name: "status", kind: "enum", options: STATUS_ACTIVE },
            ],
            seedCount: 6,
            seed: (i) => ({
                name: pick(["HQ office", "VPN", "Deny TOR", "Deny country X", "Partner"], i),
                cidr: pick(["192.168.1.0/24", "10.0.0.0/16", "1.1.1.0/24", "0.0.0.0/0"], i),
                action: i === 2 || i === 3 ? "deny" : "allow",
                appliesTo: pick(["admin", "all", "member"], i),
                status: "active",
            }),
        },
    ],
    extraNav: [
        { id: "auth.control-room.nav", label: "Auth Control Room", icon: "LayoutDashboard", path: "/auth/control-room", view: "auth.control-room.view", order: 0 },
        { id: "auth.reports.nav", label: "Reports", icon: "BarChart3", path: "/auth/reports", view: "auth.reports.view" },
    ],
    extraViews: [
        authControlRoomView,
        authReportsIndexView,
        authReportsDetailView,
    ],
    commands: [
        { id: "auth.go.control-room", label: "Auth: Control Room", icon: "LayoutDashboard", run: () => { window.location.hash = "/auth/control-room"; } },
        { id: "auth.go.reports", label: "Auth: Reports", icon: "BarChart3", run: () => { window.location.hash = "/auth/reports"; } },
        { id: "auth.new-user", label: "New user", icon: "UserPlus", run: () => { window.location.hash = "/auth/users/new"; } },
        { id: "auth.new-role", label: "New role", icon: "ShieldCheck", run: () => { window.location.hash = "/auth/roles/new"; } },
        { id: "auth.new-token", label: "New API token", icon: "Key", run: () => { window.location.hash = "/auth/api-tokens/new"; } },
        { id: "auth.new-invite", label: "Invite user", icon: "Mail", run: () => { window.location.hash = "/auth/invitations/new"; } },
    ],
});
