import { buildDomainPlugin } from "./_factory/buildDomainPlugin";
import { SECTIONS } from "./_factory/sections";
import { STATUS_TICKET, PRIORITY, STATUS_ACTIVE } from "./_factory/options";
import { CITIES, code, daysAgo, daysFromNow, personName, pick } from "./_factory/seeds";
import { fieldServiceCalendarView } from "./field-service-pages";
import { fieldServiceControlRoomView, fieldServiceReportsIndexView, fieldServiceReportsDetailView, } from "./field-service-dashboard";
const TECHS = ["Taylor Turing", "Jordan Hamilton", "Casey Pappas", "Morgan Liskov", "Riley Perlman", "Dakota Shamir", "Sam Hopper", "Alex Knuth"];
const SERVICE_TYPES = [
    { value: "install", label: "Installation" },
    { value: "repair", label: "Repair" },
    { value: "maintenance", label: "Maintenance" },
    { value: "inspection", label: "Inspection" },
    { value: "emergency", label: "Emergency" },
];
export const fieldServicePlugin = buildDomainPlugin({
    id: "field-service",
    label: "Field Service",
    icon: "Truck",
    section: SECTIONS.operations,
    order: 3,
    resources: [
        {
            id: "job",
            singular: "Job",
            plural: "Jobs",
            icon: "Wrench",
            path: "/field-service/jobs",
            displayField: "code",
            defaultSort: { field: "scheduledAt", dir: "asc" },
            pageSize: 25,
            fields: [
                { name: "code", kind: "text", required: true, sortable: true, width: 120 },
                { name: "customer", kind: "text", required: true, sortable: true },
                { name: "contactPhone", kind: "phone", width: 130 },
                { name: "serviceType", kind: "enum", required: true, options: SERVICE_TYPES, sortable: true, width: 130 },
                { name: "assetCode", label: "Asset", kind: "text" },
                { name: "technician", kind: "text", sortable: true },
                { name: "team", kind: "text", width: 120 },
                { name: "location", kind: "text" },
                { name: "address", kind: "text" },
                { name: "city", kind: "enum", options: CITIES.map((c) => ({ value: c, label: c })), sortable: true },
                { name: "priority", kind: "enum", required: true, options: PRIORITY, sortable: true },
                { name: "status", kind: "enum", required: true, options: STATUS_TICKET, sortable: true },
                { name: "scheduledAt", kind: "datetime", required: true, sortable: true, width: 160 },
                { name: "arrivedAt", kind: "datetime" },
                { name: "completedAt", kind: "datetime" },
                { name: "estimatedHours", kind: "number", align: "right", width: 110 },
                { name: "actualHours", kind: "number", align: "right", width: 110 },
                { name: "travelKm", label: "Travel (km)", kind: "number", align: "right", width: 110 },
                { name: "visits", kind: "number", align: "right", width: 80 },
                { name: "slaBreached", label: "SLA breach", kind: "boolean", width: 110 },
                { name: "overdue", kind: "boolean", width: 90 },
                { name: "reportedIssue", kind: "textarea", formSection: "Details" },
                { name: "resolutionNotes", kind: "textarea", formSection: "Details" },
            ],
            seedCount: 40,
            seed: (i) => {
                const scheduled = daysAgo(i - 10);
                const isCompleted = i % 3 === 2;
                return {
                    code: code("FS", i, 6),
                    customer: pick(["Acme Corp", "Globex", "Initech", "Hooli", "Pied Piper"], i),
                    contactPhone: `+1-555-${String(2000 + i).slice(-4)}`,
                    serviceType: pick(["install", "repair", "maintenance", "inspection", "emergency"], i),
                    assetCode: `AST-${String(10000 + i).slice(-5)}`,
                    technician: pick(TECHS, i),
                    team: pick(["North", "South", "East", "West"], i),
                    location: pick(CITIES, i),
                    address: pick(["100 Main St", "200 Market Ave", "300 Industrial Way"], i),
                    city: pick(CITIES, i),
                    priority: pick(["low", "normal", "high", "urgent"], i),
                    status: pick(["open", "in_progress", "resolved"], i),
                    scheduledAt: scheduled,
                    arrivedAt: isCompleted ? scheduled : "",
                    completedAt: isCompleted ? daysAgo(i - 11) : "",
                    estimatedHours: pick([1, 2, 3, 4, 6], i),
                    actualHours: isCompleted ? pick([1, 2, 3, 4, 5], i) : 0,
                    travelKm: 10 + (i * 7) % 80,
                    visits: isCompleted ? (i % 2 === 0 ? 1 : 2) : 0,
                    slaBreached: i % 9 === 0,
                    overdue: !isCompleted && i % 5 === 0,
                    reportedIssue: pick(["Unit won't start", "Intermittent noise", "Water leak", "Loose wiring", "Routine check"], i),
                    resolutionNotes: isCompleted ? "Replaced faulty part, tested, signed off by customer." : "",
                };
            },
        },
        {
            id: "technician",
            singular: "Technician",
            plural: "Technicians",
            icon: "HardHat",
            path: "/field-service/technicians",
            fields: [
                { name: "code", kind: "text", required: true, sortable: true, width: 100 },
                { name: "name", kind: "text", required: true, sortable: true },
                { name: "email", kind: "email" },
                { name: "phone", kind: "phone" },
                { name: "team", kind: "enum", options: [
                        { value: "North", label: "North" }, { value: "South", label: "South" },
                        { value: "East", label: "East" }, { value: "West", label: "West" },
                    ] },
                { name: "skills", kind: "multi-enum", options: [
                        { value: "electrical", label: "Electrical" },
                        { value: "plumbing", label: "Plumbing" },
                        { value: "hvac", label: "HVAC" },
                        { value: "mechanical", label: "Mechanical" },
                        { value: "software", label: "Software" },
                    ] },
                { name: "certifications", kind: "text" },
                { name: "homeCity", kind: "enum", options: CITIES.map((c) => ({ value: c, label: c })) },
                { name: "vehicleCode", label: "Vehicle", kind: "text", width: 120 },
                { name: "status", kind: "enum", required: true, options: [
                        { value: "on-duty", label: "On duty", intent: "success" },
                        { value: "off-duty", label: "Off duty", intent: "neutral" },
                        { value: "on-break", label: "On break", intent: "info" },
                        { value: "absent", label: "Absent", intent: "warning" },
                    ] },
                { name: "activeJobs", kind: "number", align: "right", readonly: true },
            ],
            seedCount: 8,
            seed: (i) => ({
                code: code("TEC", i, 4),
                name: pick(TECHS, i),
                email: `${pick(TECHS, i).toLowerCase().replace(/\s+/g, ".")}@gutu.dev`,
                phone: `+1-555-${String(3000 + i).slice(-4)}`,
                team: pick(["North", "South", "East", "West"], i),
                skills: pick([
                    ["electrical", "hvac"],
                    ["plumbing"],
                    ["mechanical", "electrical"],
                    ["software"],
                    ["hvac", "mechanical"],
                ], i),
                certifications: pick(["EPA 608", "OSHA 30", "NATE Certified", "None"], i),
                homeCity: pick(CITIES, i),
                vehicleCode: `VAN-${String(i + 1).padStart(2, "0")}`,
                status: pick(["on-duty", "on-duty", "on-duty", "off-duty", "on-break"], i),
                activeJobs: 2 + (i % 5),
            }),
        },
        {
            id: "vehicle",
            singular: "Vehicle",
            plural: "Vehicles",
            icon: "Car",
            path: "/field-service/vehicles",
            fields: [
                { name: "code", kind: "text", required: true, sortable: true, width: 100 },
                { name: "make", kind: "text" },
                { name: "model", kind: "text" },
                { name: "year", kind: "number", align: "right", width: 90 },
                { name: "licensePlate", kind: "text", width: 140 },
                { name: "assignedTo", kind: "text" },
                { name: "mileage", kind: "number", align: "right" },
                { name: "nextServiceAt", kind: "date" },
                { name: "status", kind: "enum", required: true, options: [
                        { value: "active", label: "Active", intent: "success" },
                        { value: "maintenance", label: "Maintenance", intent: "warning" },
                        { value: "retired", label: "Retired", intent: "neutral" },
                    ] },
            ],
            seedCount: 8,
            seed: (i) => ({
                code: `VAN-${String(i + 1).padStart(2, "0")}`,
                make: pick(["Ford", "Mercedes", "Ram", "Chevrolet"], i),
                model: pick(["Transit", "Sprinter", "ProMaster", "Express"], i),
                year: 2020 + (i % 5),
                licensePlate: `FS${String(1000 + i * 17).slice(-4)}`,
                assignedTo: pick(TECHS, i),
                mileage: 10_000 + i * 8_000,
                nextServiceAt: daysFromNow(30 + i * 10),
                status: i === 7 ? "maintenance" : "active",
            }),
        },
        {
            id: "parts-request",
            singular: "Parts Request",
            plural: "Parts Requests",
            icon: "Package",
            path: "/field-service/parts-requests",
            displayField: "code",
            defaultSort: { field: "requestedAt", dir: "desc" },
            fields: [
                { name: "code", kind: "text", required: true, sortable: true, width: 120 },
                { name: "jobCode", label: "Job", kind: "text", required: true },
                { name: "partSku", label: "Part SKU", kind: "text", required: true, width: 120 },
                { name: "partName", label: "Part", kind: "text", required: true },
                { name: "qty", kind: "number", required: true, align: "right" },
                { name: "requestedBy", kind: "text" },
                { name: "requestedAt", kind: "datetime", sortable: true, width: 150 },
                { name: "status", kind: "enum", required: true, sortable: true, options: [
                        { value: "pending", label: "Pending", intent: "warning" },
                        { value: "approved", label: "Approved", intent: "info" },
                        { value: "fulfilled", label: "Fulfilled", intent: "success" },
                        { value: "rejected", label: "Rejected", intent: "danger" },
                    ] },
                { name: "needBy", kind: "date" },
            ],
            seedCount: 18,
            seed: (i) => ({
                code: code("PRQ", i, 5),
                jobCode: code("FS", i, 6),
                partSku: `SKU-${String(1000 + i * 7).slice(-5)}`,
                partName: pick(["Motor", "Filter", "Belt", "Seal", "Pump", "Thermostat", "Sensor"], i),
                qty: 1 + (i % 4),
                requestedBy: pick(TECHS, i),
                requestedAt: daysAgo(i * 0.5),
                status: pick(["pending", "pending", "approved", "fulfilled", "rejected"], i),
                needBy: daysFromNow((i % 7) + 1),
            }),
        },
        {
            id: "parts-usage",
            singular: "Parts Usage",
            plural: "Parts Usage",
            icon: "Cog",
            path: "/field-service/parts-usage",
            fields: [
                { name: "jobCode", label: "Job", kind: "text", required: true },
                { name: "partSku", kind: "text", required: true },
                { name: "partName", kind: "text", required: true },
                { name: "qty", kind: "number", required: true, align: "right" },
                { name: "unitCost", kind: "currency", align: "right" },
                { name: "usedAt", kind: "datetime", sortable: true },
                { name: "technician", kind: "text" },
            ],
            seedCount: 30,
            seed: (i) => ({
                jobCode: code("FS", i % 40, 6),
                partSku: `SKU-${String(1000 + (i % 15) * 7).slice(-5)}`,
                partName: pick(["Motor", "Filter", "Belt", "Seal", "Pump", "Thermostat", "Sensor"], i),
                qty: 1 + (i % 3),
                unitCost: 15 + (i * 7) % 200,
                usedAt: daysAgo(i),
                technician: pick(TECHS, i),
            }),
        },
        {
            id: "service-contract",
            singular: "Service Contract",
            plural: "Service Contracts",
            icon: "FileSignature",
            path: "/field-service/service-contracts",
            displayField: "code",
            fields: [
                { name: "code", kind: "text", required: true, sortable: true },
                { name: "customer", kind: "text", required: true, sortable: true },
                { name: "coverage", kind: "enum", options: [
                        { value: "basic", label: "Basic" },
                        { value: "standard", label: "Standard" },
                        { value: "premium", label: "Premium" },
                        { value: "full", label: "Full" },
                    ] },
                { name: "startAt", kind: "date" },
                { name: "endAt", kind: "date" },
                { name: "assetsCovered", kind: "number", align: "right" },
                { name: "visitsPerYear", kind: "number", align: "right" },
                { name: "valueAnnual", kind: "currency", align: "right" },
                { name: "status", kind: "enum", options: STATUS_ACTIVE },
            ],
            seedCount: 12,
            seed: (i) => ({
                code: code("FSC", i, 5),
                customer: pick(["Acme Corp", "Globex", "Initech", "Hooli", "Pied Piper"], i),
                coverage: pick(["basic", "standard", "premium", "full"], i),
                startAt: daysAgo(365 - i * 20),
                endAt: daysFromNow(365 - i * 20),
                assetsCovered: 1 + (i % 10),
                visitsPerYear: pick([2, 4, 6, 12], i),
                valueAnnual: 2_000 + ((i * 2137) % 30_000),
                status: i === 11 ? "archived" : "active",
            }),
        },
        {
            id: "quote",
            singular: "Quote",
            plural: "Quotes",
            icon: "FileText",
            path: "/field-service/quotes",
            displayField: "code",
            defaultSort: { field: "createdAt", dir: "desc" },
            fields: [
                { name: "code", kind: "text", required: true, sortable: true, width: 120 },
                { name: "customer", kind: "text", required: true, sortable: true },
                { name: "jobCode", label: "Job", kind: "text" },
                { name: "serviceType", kind: "enum", options: SERVICE_TYPES },
                { name: "laborHours", kind: "number", align: "right" },
                { name: "laborCost", kind: "currency", align: "right" },
                { name: "partsCost", kind: "currency", align: "right" },
                { name: "tax", kind: "currency", align: "right" },
                { name: "total", kind: "currency", align: "right", sortable: true },
                { name: "status", kind: "enum", required: true, options: [
                        { value: "draft", label: "Draft", intent: "neutral" },
                        { value: "sent", label: "Sent", intent: "info" },
                        { value: "accepted", label: "Accepted", intent: "success" },
                        { value: "rejected", label: "Rejected", intent: "danger" },
                        { value: "expired", label: "Expired", intent: "warning" },
                    ] },
                { name: "createdAt", kind: "date", sortable: true, width: 130 },
                { name: "validUntil", kind: "date" },
            ],
            seedCount: 16,
            seed: (i) => {
                const laborHours = 2 + (i % 6);
                const laborCost = laborHours * 80;
                const partsCost = 50 + (i * 23) % 500;
                const tax = Math.round((laborCost + partsCost) * 0.08);
                return {
                    code: code("FQ", i, 5),
                    customer: pick(["Acme Corp", "Globex", "Initech", "Hooli", "Pied Piper"], i),
                    jobCode: code("FS", i % 40, 6),
                    serviceType: pick(["install", "repair", "maintenance", "inspection"], i),
                    laborHours,
                    laborCost,
                    partsCost,
                    tax,
                    total: laborCost + partsCost + tax,
                    status: pick(["accepted", "accepted", "sent", "draft", "rejected", "expired"], i),
                    createdAt: daysAgo(i * 3),
                    validUntil: daysFromNow(30),
                };
            },
        },
        {
            id: "customer-site",
            singular: "Customer Site",
            plural: "Customer Sites",
            icon: "Building2",
            path: "/field-service/customer-sites",
            fields: [
                { name: "code", kind: "text", required: true, sortable: true, width: 100 },
                { name: "customer", kind: "text", required: true, sortable: true },
                { name: "siteName", kind: "text", required: true },
                { name: "address", kind: "text" },
                { name: "city", kind: "enum", options: CITIES.map((c) => ({ value: c, label: c })) },
                { name: "contactName", kind: "text" },
                { name: "contactPhone", kind: "phone" },
                { name: "assetsCount", kind: "number", align: "right" },
                { name: "lastVisitAt", kind: "date" },
                { name: "nextScheduledAt", kind: "date" },
            ],
            seedCount: 14,
            seed: (i) => ({
                code: code("SITE", i, 5),
                customer: pick(["Acme Corp", "Globex", "Initech", "Hooli", "Pied Piper"], i),
                siteName: pick(["HQ", "Warehouse", "Factory 1", "Branch A", "Retail 1"], i),
                address: `${100 + i * 10} Main St`,
                city: pick(CITIES, i),
                contactName: personName(i),
                contactPhone: `+1-555-${String(4000 + i).slice(-4)}`,
                assetsCount: 2 + (i % 8),
                lastVisitAt: daysAgo(i * 10),
                nextScheduledAt: daysFromNow(30 + i * 5),
            }),
        },
    ],
    extraNav: [
        { id: "field-service.control-room.nav", label: "Field Service Control Room", icon: "LayoutDashboard", path: "/field-service/control-room", view: "field-service.control-room.view", order: 0 },
        { id: "field-service.reports.nav", label: "Reports", icon: "BarChart3", path: "/field-service/reports", view: "field-service.reports.view" },
        { id: "field-service.calendar.nav", label: "Calendar", icon: "Calendar", path: "/field-service/calendar", view: "field-service.calendar.view" },
    ],
    extraViews: [
        fieldServiceControlRoomView,
        fieldServiceReportsIndexView,
        fieldServiceReportsDetailView,
        fieldServiceCalendarView,
    ],
    commands: [
        { id: "field-service.go.control-room", label: "Field Service: Control Room", icon: "LayoutDashboard", run: () => { window.location.hash = "/field-service/control-room"; } },
        { id: "field-service.go.reports", label: "Field Service: Reports", icon: "BarChart3", run: () => { window.location.hash = "/field-service/reports"; } },
        { id: "field-service.go.calendar", label: "Field Service: Calendar", icon: "Calendar", run: () => { window.location.hash = "/field-service/calendar"; } },
        { id: "field-service.new-job", label: "New field job", icon: "Plus", run: () => { window.location.hash = "/field-service/jobs/new"; } },
        { id: "field-service.new-quote", label: "New quote", icon: "FileText", run: () => { window.location.hash = "/field-service/quotes/new"; } },
        { id: "field-service.new-parts-request", label: "New parts request", icon: "Package", run: () => { window.location.hash = "/field-service/parts-requests/new"; } },
    ],
});
