import { buildDomainPlugin } from "./_factory/buildDomainPlugin";
import { SECTIONS } from "./_factory/sections";
import { CURRENCY } from "./_factory/options";
import { daysAgo, daysFromNow, personEmail, personName, pick, money, code } from "./_factory/seeds";
import { hrHeadcountView } from "./hr-payroll-pages";
import { hrPayrollControlRoomView, hrPayrollReportsIndexView, hrPayrollReportsDetailView, } from "./hr-payroll-dashboard";
const DEPARTMENTS = [
    { value: "eng", label: "Engineering" },
    { value: "ops", label: "Operations" },
    { value: "sales", label: "Sales" },
    { value: "marketing", label: "Marketing" },
    { value: "support", label: "Support" },
    { value: "hr", label: "HR" },
    { value: "finance", label: "Finance" },
    { value: "product", label: "Product" },
];
const LEAVE_TYPES = [
    { value: "annual", label: "Annual" },
    { value: "sick", label: "Sick" },
    { value: "personal", label: "Personal" },
    { value: "maternity", label: "Maternity" },
    { value: "paternity", label: "Paternity" },
    { value: "bereavement", label: "Bereavement" },
    { value: "unpaid", label: "Unpaid" },
    { value: "study", label: "Study" },
];
const EXPENSE_CATS = [
    { value: "travel", label: "Travel" },
    { value: "meals", label: "Meals" },
    { value: "software", label: "Software" },
    { value: "hardware", label: "Hardware" },
    { value: "training", label: "Training" },
    { value: "other", label: "Other" },
];
export const hrPayrollPlugin = buildDomainPlugin({
    id: "hr-payroll",
    label: "HR & Payroll",
    icon: "UsersRound",
    section: SECTIONS.people,
    order: 2,
    resources: [
        {
            id: "employee",
            singular: "Employee",
            plural: "Employees",
            icon: "UserCircle2",
            path: "/hr/employees",
            defaultSort: { field: "hiredAt", dir: "desc" },
            fields: [
                { name: "empCode", label: "Emp Code", kind: "text", sortable: true, width: 110 },
                { name: "name", kind: "text", required: true, sortable: true },
                { name: "email", kind: "email", required: true },
                { name: "phone", kind: "phone", width: 130 },
                { name: "department", kind: "enum", required: true, options: DEPARTMENTS, sortable: true },
                { name: "designation", label: "Designation", kind: "text" },
                { name: "role", kind: "text", sortable: true },
                { name: "grade", kind: "enum", options: [
                        { value: "L1", label: "L1 Junior" },
                        { value: "L2", label: "L2 Mid" },
                        { value: "L3", label: "L3 Senior" },
                        { value: "L4", label: "L4 Staff" },
                        { value: "L5", label: "L5 Principal" },
                        { value: "M1", label: "M1 Manager" },
                        { value: "M2", label: "M2 Director" },
                        { value: "M3", label: "M3 VP" },
                    ] },
                { name: "manager", kind: "text" },
                { name: "employmentType", label: "Employment", kind: "enum", options: [
                        { value: "full-time", label: "Full-time" },
                        { value: "part-time", label: "Part-time" },
                        { value: "contract", label: "Contract" },
                        { value: "intern", label: "Intern" },
                        { value: "consultant", label: "Consultant" },
                    ], width: 130 },
                { name: "location", kind: "text" },
                { name: "hiredAt", kind: "date", required: true, sortable: true, width: 130 },
                { name: "anniversaryAt", label: "Next anniversary", kind: "date" },
                { name: "birthday", kind: "date" },
                { name: "status", kind: "enum", required: true, options: [
                        { value: "active", label: "Active", intent: "success" },
                        { value: "on-leave", label: "On leave", intent: "info" },
                        { value: "resigned", label: "Resigned", intent: "warning" },
                        { value: "terminated", label: "Terminated", intent: "danger" },
                    ] },
                { name: "currency", kind: "enum", options: CURRENCY, width: 100 },
                { name: "baseSalary", label: "Base salary (annual)", kind: "currency", align: "right" },
                { name: "bio", kind: "textarea", formSection: "About" },
            ],
            seedCount: 30,
            seed: (i) => {
                const hired = daysAgo(i * 60);
                const h = new Date(hired);
                const birth = new Date(h.getFullYear() - 30 - (i % 20), (i * 3) % 12, ((i * 5) % 27) + 1);
                return {
                    empCode: `EMP-${String(1000 + i).padStart(4, "0")}`,
                    name: personName(i),
                    email: personEmail(i, "gutu.dev"),
                    phone: `+1-555-${String(1000 + i).slice(-4)}`,
                    department: pick(["eng", "ops", "sales", "marketing", "support", "hr", "finance", "product"], i),
                    designation: pick(["Engineer", "Senior Engineer", "Staff Engineer", "Designer", "PM", "Manager", "Lead", "Specialist", "Analyst"], i),
                    role: pick(["Engineer", "Designer", "Manager", "Lead", "Specialist"], i),
                    grade: pick(["L1", "L2", "L3", "L4", "L5", "M1", "M2"], i),
                    manager: personName(i + 2),
                    employmentType: pick(["full-time", "full-time", "full-time", "contract", "part-time"], i),
                    location: pick(["San Francisco", "New York", "London", "Berlin", "Tokyo", "Remote"], i),
                    hiredAt: hired,
                    anniversaryAt: new Date(new Date().getFullYear(), h.getMonth(), h.getDate()).toISOString(),
                    birthday: birth.toISOString(),
                    status: pick(["active", "active", "active", "active", "on-leave", "resigned"], i),
                    currency: pick(["USD", "EUR", "GBP"], i),
                    baseSalary: 60_000 + ((i * 7_313) % 200_000),
                    bio: "",
                };
            },
        },
        {
            id: "department",
            singular: "Department",
            plural: "Departments",
            icon: "Building2",
            path: "/hr/departments",
            fields: [
                { name: "code", kind: "text", required: true, sortable: true, width: 100 },
                { name: "name", kind: "text", required: true, sortable: true },
                { name: "head", kind: "text" },
                { name: "parent", kind: "text" },
                { name: "headcount", kind: "number", align: "right" },
                { name: "budgetAnnual", label: "Budget (annual)", kind: "currency", align: "right" },
            ],
            seedCount: 8,
            seed: (i) => ({
                code: pick(["ENG", "OPS", "SAL", "MKT", "SUP", "HRP", "FIN", "PRD"], i),
                name: pick(DEPARTMENTS.map((d) => d.label), i),
                head: personName(i),
                parent: i > 0 ? "" : "",
                headcount: 4 + ((i * 5) % 18),
                budgetAnnual: 500_000 + ((i * 23_171) % 2_000_000),
            }),
        },
        {
            id: "designation",
            singular: "Designation",
            plural: "Designations",
            icon: "BadgeCheck",
            path: "/hr/designations",
            fields: [
                { name: "name", kind: "text", required: true, sortable: true },
                { name: "grade", kind: "enum", options: [
                        { value: "L1", label: "L1" }, { value: "L2", label: "L2" }, { value: "L3", label: "L3" },
                        { value: "L4", label: "L4" }, { value: "L5", label: "L5" }, { value: "M1", label: "M1" },
                        { value: "M2", label: "M2" }, { value: "M3", label: "M3" },
                    ] },
                { name: "department", kind: "enum", options: DEPARTMENTS },
                { name: "description", kind: "textarea", formSection: "About" },
            ],
            seedCount: 12,
            seed: (i) => ({
                name: pick(["Engineer", "Senior Engineer", "Staff Engineer", "Principal Engineer", "Designer", "Senior Designer", "PM", "Senior PM", "Manager", "Director", "Analyst", "Specialist"], i),
                grade: pick(["L1", "L2", "L3", "L4", "L5", "M1", "M2", "M3"], i),
                department: pick(DEPARTMENTS.map((d) => d.value), i),
                description: "",
            }),
        },
        {
            id: "leave-type",
            singular: "Leave Type",
            plural: "Leave Types",
            icon: "CalendarDays",
            path: "/hr/leave-types",
            fields: [
                { name: "name", kind: "text", required: true, sortable: true },
                { name: "code", kind: "text", sortable: true, width: 100 },
                { name: "annualAllowance", label: "Annual allowance", kind: "number", align: "right" },
                { name: "paid", kind: "boolean" },
                { name: "carryForward", kind: "boolean" },
                { name: "requiresApproval", kind: "boolean" },
            ],
            seedCount: 8,
            seed: (i) => ({
                name: pick(LEAVE_TYPES.map((l) => l.label), i),
                code: pick(LEAVE_TYPES.map((l) => l.value), i).toUpperCase(),
                annualAllowance: pick([20, 10, 5, 180, 14, 5, 0, 5], i),
                paid: !["unpaid"].includes(pick(LEAVE_TYPES.map((l) => l.value), i)),
                carryForward: pick([true, false, false, false, false, false, false, false], i),
                requiresApproval: true,
            }),
        },
        {
            id: "leave-application",
            singular: "Leave Application",
            plural: "Leave Applications",
            icon: "Calendar",
            path: "/hr/leave-applications",
            displayField: "code",
            defaultSort: { field: "submittedAt", dir: "desc" },
            fields: [
                { name: "code", kind: "text", required: true, sortable: true, width: 120 },
                { name: "employee", kind: "text", required: true, sortable: true },
                { name: "leaveType", kind: "enum", required: true, options: LEAVE_TYPES, width: 130 },
                { name: "fromAt", label: "From", kind: "date", required: true, sortable: true, width: 130 },
                { name: "toAt", label: "To", kind: "date", required: true, sortable: true, width: 130 },
                { name: "days", kind: "number", align: "right", sortable: true, width: 80 },
                { name: "reason", kind: "text" },
                { name: "submittedAt", kind: "date", sortable: true, width: 130 },
                { name: "approver", kind: "text" },
                { name: "status", kind: "enum", required: true, sortable: true, options: [
                        { value: "pending", label: "Pending", intent: "warning" },
                        { value: "approved", label: "Approved", intent: "success" },
                        { value: "rejected", label: "Rejected", intent: "danger" },
                        { value: "cancelled", label: "Cancelled", intent: "neutral" },
                    ] },
            ],
            seedCount: 30,
            seed: (i) => {
                const from = daysFromNow(i - 20);
                const days = 1 + (i % 8);
                return {
                    code: code("LV", i, 5),
                    employee: personName(i),
                    leaveType: pick(LEAVE_TYPES.map((l) => l.value), i),
                    fromAt: from,
                    toAt: new Date(Date.parse(from) + days * 86_400_000).toISOString(),
                    days,
                    reason: pick(["Family trip", "Medical", "Personal work", "Vacation", "Mental health", "Moving"], i),
                    submittedAt: daysAgo(i * 0.5),
                    approver: personName(i + 5),
                    status: pick(["approved", "pending", "pending", "approved", "rejected", "cancelled"], i),
                };
            },
        },
        {
            id: "leave-balance",
            singular: "Leave Balance",
            plural: "Leave Balances",
            icon: "ListTodo",
            path: "/hr/leave-balances",
            fields: [
                { name: "employee", kind: "text", required: true, sortable: true },
                { name: "leaveType", kind: "enum", required: true, options: LEAVE_TYPES, width: 130 },
                { name: "year", kind: "text", sortable: true, width: 90 },
                { name: "accrued", kind: "number", align: "right" },
                { name: "used", kind: "number", align: "right" },
                { name: "available", kind: "number", align: "right" },
            ],
            seedCount: 40,
            seed: (i) => {
                const accrued = pick([20, 10, 5, 14, 5], i);
                const used = (i * 3) % Math.max(accrued, 1);
                return {
                    employee: personName(i % 20),
                    leaveType: pick(LEAVE_TYPES.map((l) => l.value), i),
                    year: "2026",
                    accrued,
                    used,
                    available: Math.max(0, accrued - used),
                };
            },
        },
        {
            id: "attendance",
            singular: "Attendance",
            plural: "Attendance",
            icon: "Fingerprint",
            path: "/hr/attendance",
            displayField: "date",
            defaultSort: { field: "date", dir: "desc" },
            fields: [
                { name: "employee", kind: "text", required: true, sortable: true },
                { name: "date", kind: "date", required: true, sortable: true, width: 130 },
                { name: "status", kind: "enum", required: true, sortable: true, options: [
                        { value: "present", label: "Present", intent: "success" },
                        { value: "absent", label: "Absent", intent: "danger" },
                        { value: "late", label: "Late", intent: "warning" },
                        { value: "leave", label: "On leave", intent: "info" },
                        { value: "holiday", label: "Holiday", intent: "neutral" },
                        { value: "half-day", label: "Half day", intent: "accent" },
                    ], width: 120 },
                { name: "checkIn", kind: "datetime" },
                { name: "checkOut", kind: "datetime" },
                { name: "hoursWorked", kind: "number", align: "right", width: 110 },
                { name: "shift", kind: "text", width: 100 },
            ],
            seedCount: 60,
            seed: (i) => ({
                employee: personName(i % 20),
                date: daysAgo(i * 0.2),
                status: pick(["present", "present", "present", "present", "late", "leave", "absent"], i),
                checkIn: daysAgo(i * 0.2),
                checkOut: daysAgo(i * 0.2 - 0.3),
                hoursWorked: 8 - (i % 3) * 0.5,
                shift: pick(["Morning", "Evening", "Night"], i),
            }),
        },
        {
            id: "shift",
            singular: "Shift",
            plural: "Shifts",
            icon: "Clock",
            path: "/hr/shifts",
            fields: [
                { name: "name", kind: "text", required: true, sortable: true },
                { name: "startTime", kind: "text", width: 110 },
                { name: "endTime", kind: "text", width: 110 },
                { name: "breakMinutes", kind: "number", align: "right" },
                { name: "active", kind: "boolean" },
            ],
            seedCount: 4,
            seed: (i) => ({
                name: pick(["Morning", "Afternoon", "Night", "Weekend"], i),
                startTime: pick(["09:00", "13:00", "22:00", "09:00"], i),
                endTime: pick(["18:00", "22:00", "06:00", "17:00"], i),
                breakMinutes: 30 + (i % 3) * 15,
                active: true,
            }),
        },
        {
            id: "holiday-list",
            singular: "Holiday List",
            plural: "Holiday Lists",
            icon: "PartyPopper",
            path: "/hr/holiday-lists",
            fields: [
                { name: "name", kind: "text", required: true, sortable: true },
                { name: "country", kind: "text", width: 110 },
                { name: "year", kind: "text", sortable: true, width: 90 },
                { name: "holidaysCount", kind: "number", align: "right" },
            ],
            seedCount: 5,
            seed: (i) => ({
                name: pick(["US Federal 2026", "UK Bank Holidays 2026", "IN Public Holidays 2026", "JP National 2026", "EU General 2026"], i),
                country: pick(["USA", "UK", "IN", "JP", "EU"], i),
                year: "2026",
                holidaysCount: pick([11, 8, 12, 16, 14], i),
            }),
        },
        {
            id: "payroll",
            singular: "Payroll Run",
            plural: "Payroll Runs",
            icon: "Banknote",
            path: "/hr/payroll",
            displayField: "period",
            defaultSort: { field: "period", dir: "desc" },
            fields: [
                { name: "period", kind: "text", required: true, sortable: true, width: 100 },
                { name: "employees", kind: "number", align: "right" },
                { name: "gross", kind: "currency", align: "right", sortable: true, currency: "USD" },
                { name: "deductions", kind: "currency", align: "right", currency: "USD" },
                { name: "taxes", kind: "currency", align: "right", currency: "USD" },
                { name: "net", kind: "currency", align: "right", sortable: true, currency: "USD" },
                { name: "currency", kind: "enum", options: CURRENCY, width: 100 },
                { name: "status", kind: "enum", required: true, sortable: true, options: [
                        { value: "draft", label: "Draft", intent: "neutral" },
                        { value: "calculated", label: "Calculated", intent: "info" },
                        { value: "approved", label: "Approved", intent: "accent" },
                        { value: "paid", label: "Paid", intent: "success" },
                        { value: "failed", label: "Failed", intent: "danger" },
                    ] },
                { name: "processedAt", kind: "date", sortable: true },
                { name: "processedBy", kind: "text" },
            ],
            seedCount: 14,
            seed: (i) => {
                const gross = money(i, 50_000, 200_000);
                const deductions = Math.round(gross * 0.08);
                const taxes = Math.round(gross * 0.2);
                return {
                    period: `2026-${String(Math.max(1, 13 - i)).padStart(2, "0")}`,
                    employees: 42 + (i % 10),
                    gross,
                    deductions,
                    taxes,
                    net: gross - deductions - taxes,
                    currency: "USD",
                    status: i < 2 ? "calculated" : i < 3 ? "approved" : "paid",
                    processedAt: daysAgo(i * 30),
                    processedBy: "sam@gutu.dev",
                };
            },
        },
        {
            id: "salary-structure",
            singular: "Salary Structure",
            plural: "Salary Structures",
            icon: "LayoutGrid",
            path: "/hr/salary-structures",
            fields: [
                { name: "name", kind: "text", required: true, sortable: true },
                { name: "currency", kind: "enum", options: CURRENCY, width: 100 },
                { name: "baseAnnual", kind: "currency", align: "right" },
                { name: "hra", label: "HRA", kind: "currency", align: "right" },
                { name: "allowances", kind: "currency", align: "right" },
                { name: "active", kind: "boolean" },
            ],
            seedCount: 6,
            seed: (i) => ({
                name: pick(["L1 Standard", "L2 Standard", "L3 Staff", "L4 Senior", "M1 Manager", "Contractor"], i),
                currency: pick(["USD", "EUR", "GBP"], i),
                baseAnnual: 50_000 + i * 15_000,
                hra: Math.round((50_000 + i * 15_000) * 0.15),
                allowances: 3_000 + i * 500,
                active: true,
            }),
        },
        {
            id: "salary-component",
            singular: "Salary Component",
            plural: "Salary Components",
            icon: "Puzzle",
            path: "/hr/salary-components",
            fields: [
                { name: "name", kind: "text", required: true, sortable: true },
                { name: "kind", label: "Type", kind: "enum", options: [
                        { value: "earning", label: "Earning", intent: "success" },
                        { value: "deduction", label: "Deduction", intent: "warning" },
                    ], width: 120 },
                { name: "formula", kind: "text" },
                { name: "taxable", kind: "boolean" },
            ],
            seedCount: 10,
            seed: (i) => ({
                name: pick(["Basic", "HRA", "Transport", "Meal", "Bonus", "Tax", "PF", "Insurance", "Loan Deduction", "Overtime"], i),
                kind: pick(["earning", "earning", "earning", "earning", "earning", "deduction", "deduction", "deduction", "deduction", "earning"], i),
                formula: pick(["base", "base * 0.15", "flat 500", "flat 200", "perf * 1000", "gross * 0.2", "gross * 0.08", "flat 150", "amount", "hours * rate"], i),
                taxable: i % 2 === 0,
            }),
        },
        {
            id: "salary-slip",
            singular: "Salary Slip",
            plural: "Salary Slips",
            icon: "FileText",
            path: "/hr/salary-slips",
            displayField: "code",
            defaultSort: { field: "period", dir: "desc" },
            fields: [
                { name: "code", kind: "text", required: true, sortable: true, width: 120 },
                { name: "period", kind: "text", required: true, sortable: true, width: 100 },
                { name: "employee", kind: "text", required: true, sortable: true },
                { name: "basic", kind: "currency", align: "right", currency: "USD" },
                { name: "hra", kind: "currency", align: "right", currency: "USD" },
                { name: "allowances", kind: "currency", align: "right", currency: "USD" },
                { name: "pf", kind: "currency", align: "right", currency: "USD" },
                { name: "tax", kind: "currency", align: "right", currency: "USD" },
                { name: "otherDeductions", kind: "currency", align: "right", currency: "USD" },
                { name: "net", kind: "currency", align: "right", sortable: true, currency: "USD" },
                { name: "status", kind: "enum", required: true, sortable: true, options: [
                        { value: "draft", label: "Draft", intent: "neutral" },
                        { value: "issued", label: "Issued", intent: "info" },
                        { value: "paid", label: "Paid", intent: "success" },
                    ] },
            ],
            seedCount: 40,
            seed: (i) => {
                const basic = 3_000 + ((i * 317) % 8000);
                const hra = Math.round(basic * 0.2);
                const allowances = 500 + (i % 5) * 200;
                const pf = Math.round(basic * 0.08);
                const tax = Math.round((basic + hra + allowances) * 0.15);
                const other = (i % 4) * 100;
                const net = basic + hra + allowances - pf - tax - other;
                return {
                    code: code("SLIP", i, 5),
                    period: `2026-${String(Math.max(1, 13 - (i % 12))).padStart(2, "0")}`,
                    employee: personName(i % 20),
                    basic,
                    hra,
                    allowances,
                    pf,
                    tax,
                    otherDeductions: other,
                    net,
                    status: pick(["paid", "paid", "paid", "issued"], i),
                };
            },
        },
        {
            id: "expense-claim",
            singular: "Expense Claim",
            plural: "Expense Claims",
            icon: "ReceiptText",
            path: "/hr/expense-claims",
            displayField: "code",
            defaultSort: { field: "submittedAt", dir: "desc" },
            fields: [
                { name: "code", kind: "text", required: true, sortable: true, width: 120 },
                { name: "employee", kind: "text", required: true, sortable: true },
                { name: "category", kind: "enum", required: true, options: EXPENSE_CATS, sortable: true, width: 120 },
                { name: "amount", kind: "currency", required: true, align: "right", sortable: true, currency: "USD" },
                { name: "submittedAt", kind: "date", sortable: true, width: 130 },
                { name: "approver", kind: "text" },
                { name: "status", kind: "enum", required: true, sortable: true, options: [
                        { value: "draft", label: "Draft", intent: "neutral" },
                        { value: "submitted", label: "Submitted", intent: "info" },
                        { value: "approved", label: "Approved", intent: "success" },
                        { value: "rejected", label: "Rejected", intent: "danger" },
                        { value: "reimbursed", label: "Reimbursed", intent: "accent" },
                    ] },
                { name: "description", kind: "textarea", formSection: "Details" },
            ],
            seedCount: 30,
            seed: (i) => ({
                code: code("EXP", i, 5),
                employee: personName(i % 20),
                category: pick(EXPENSE_CATS.map((c) => c.value), i),
                amount: money(i, 20, 2000),
                submittedAt: daysAgo(i * 2),
                approver: personName(i + 5),
                status: pick(["reimbursed", "approved", "submitted", "rejected", "submitted", "reimbursed"], i),
                description: pick(["Client dinner", "Conference pass", "Team lunch", "SaaS subscription", "Flights", "Hotel", "Uber"], i),
            }),
        },
        {
            id: "advance",
            singular: "Employee Advance",
            plural: "Advances",
            icon: "PiggyBank",
            path: "/hr/advances",
            displayField: "code",
            fields: [
                { name: "code", kind: "text", required: true, sortable: true, width: 120 },
                { name: "employee", kind: "text", required: true, sortable: true },
                { name: "amount", kind: "currency", required: true, align: "right" },
                { name: "purpose", kind: "text" },
                { name: "repaymentMonths", kind: "number", align: "right" },
                { name: "status", kind: "enum", required: true, options: [
                        { value: "pending", label: "Pending", intent: "warning" },
                        { value: "approved", label: "Approved", intent: "accent" },
                        { value: "disbursed", label: "Disbursed", intent: "info" },
                        { value: "settled", label: "Settled", intent: "success" },
                    ] },
                { name: "disbursedAt", kind: "date" },
            ],
            seedCount: 8,
            seed: (i) => ({
                code: code("ADV", i, 5),
                employee: personName(i % 20),
                amount: money(i, 500, 10000),
                purpose: pick(["Relocation", "Travel advance", "Personal", "Emergency"], i),
                repaymentMonths: pick([3, 6, 12], i),
                status: pick(["settled", "disbursed", "approved", "pending"], i),
                disbursedAt: daysAgo(i * 15),
            }),
        },
        {
            id: "appraisal",
            singular: "Appraisal",
            plural: "Appraisals",
            icon: "Award",
            path: "/hr/appraisals",
            displayField: "code",
            defaultSort: { field: "cycle", dir: "desc" },
            fields: [
                { name: "code", kind: "text", required: true, sortable: true, width: 120 },
                { name: "employee", kind: "text", required: true, sortable: true },
                { name: "cycle", kind: "text", required: true, sortable: true, width: 110 },
                { name: "manager", kind: "text" },
                { name: "overallRating", kind: "number", align: "right" },
                { name: "promotionProposed", kind: "boolean" },
                { name: "status", kind: "enum", required: true, options: [
                        { value: "draft", label: "Draft", intent: "neutral" },
                        { value: "self-review", label: "Self review", intent: "info" },
                        { value: "manager-review", label: "Manager review", intent: "warning" },
                        { value: "calibrated", label: "Calibrated", intent: "accent" },
                        { value: "final", label: "Final", intent: "success" },
                    ] },
            ],
            seedCount: 20,
            seed: (i) => ({
                code: code("APR", i, 5),
                employee: personName(i % 20),
                cycle: pick(["2026-H1", "2025-H2", "2025-H1", "2024-H2"], i),
                manager: personName(i + 5),
                overallRating: Math.round((3 + ((i * 0.7) % 2)) * 10) / 10,
                promotionProposed: i % 5 === 0,
                status: pick(["final", "final", "manager-review", "self-review", "calibrated"], i),
            }),
        },
        {
            id: "training-event",
            singular: "Training Event",
            plural: "Training Events",
            icon: "GraduationCap",
            path: "/hr/training-events",
            displayField: "title",
            defaultSort: { field: "startAt", dir: "asc" },
            fields: [
                { name: "title", kind: "text", required: true, sortable: true },
                { name: "kind", label: "Type", kind: "enum", options: [
                        { value: "classroom", label: "Classroom" },
                        { value: "online", label: "Online" },
                        { value: "workshop", label: "Workshop" },
                        { value: "certification", label: "Certification" },
                    ], width: 140 },
                { name: "trainer", kind: "text" },
                { name: "startAt", kind: "date", required: true, sortable: true, width: 130 },
                { name: "durationHours", kind: "number", align: "right" },
                { name: "capacity", kind: "number", align: "right" },
                { name: "enrolled", kind: "number", align: "right" },
                { name: "status", kind: "enum", options: [
                        { value: "scheduled", label: "Scheduled", intent: "info" },
                        { value: "completed", label: "Completed", intent: "success" },
                        { value: "cancelled", label: "Cancelled", intent: "danger" },
                    ] },
            ],
            seedCount: 10,
            seed: (i) => ({
                title: pick(["React fundamentals", "Leadership 101", "Security awareness", "SQL deep-dive", "Effective writing", "Design systems", "Product thinking", "AWS Solutions Architect"], i),
                kind: pick(["classroom", "online", "workshop", "certification"], i),
                trainer: pick(["External", "Internal", "Sam", "Alex", "Taylor"], i),
                startAt: daysFromNow(i * 15 - 30),
                durationHours: pick([4, 8, 16, 24, 40], i),
                capacity: 20 + (i % 4) * 10,
                enrolled: 12 + ((i * 5) % 20),
                status: pick(["scheduled", "completed", "scheduled", "completed"], i),
            }),
        },
        {
            id: "job-requisition",
            singular: "Job Requisition",
            plural: "Job Requisitions",
            icon: "ClipboardList",
            path: "/hr/job-requisitions",
            displayField: "code",
            defaultSort: { field: "openedAt", dir: "desc" },
            fields: [
                { name: "code", kind: "text", required: true, sortable: true, width: 120 },
                { name: "title", kind: "text", required: true, sortable: true },
                { name: "department", kind: "enum", required: true, options: DEPARTMENTS },
                { name: "level", kind: "enum", options: [
                        { value: "L1", label: "L1" }, { value: "L2", label: "L2" }, { value: "L3", label: "L3" },
                        { value: "L4", label: "L4" }, { value: "L5", label: "L5" }, { value: "M1", label: "M1" },
                        { value: "M2", label: "M2" }, { value: "M3", label: "M3" },
                    ], width: 100 },
                { name: "hiringManager", kind: "text" },
                { name: "openedAt", kind: "date", sortable: true, width: 130 },
                { name: "targetHireAt", kind: "date", sortable: true, width: 130 },
                { name: "status", kind: "enum", required: true, sortable: true, options: [
                        { value: "draft", label: "Draft", intent: "neutral" },
                        { value: "open", label: "Open", intent: "info" },
                        { value: "on-hold", label: "On hold", intent: "warning" },
                        { value: "filled", label: "Filled", intent: "success" },
                        { value: "cancelled", label: "Cancelled", intent: "danger" },
                    ] },
                { name: "applicants", kind: "number", align: "right" },
                { name: "budgetedSalary", kind: "currency", align: "right" },
            ],
            seedCount: 12,
            seed: (i) => ({
                code: code("REQ", i, 5),
                title: pick(["Senior Engineer", "Staff Engineer", "Product Manager", "Designer", "Engineering Manager", "SRE", "Sales Rep", "Marketing Manager"], i),
                department: pick(DEPARTMENTS.map((d) => d.value), i),
                level: pick(["L3", "L4", "L5", "M1", "L2", "L3"], i),
                hiringManager: personName(i),
                openedAt: daysAgo(i * 10),
                targetHireAt: daysFromNow(30 - i),
                status: pick(["open", "open", "open", "filled", "on-hold", "draft"], i),
                applicants: (i * 13) % 80,
                budgetedSalary: 80_000 + (i * 12_000),
            }),
        },
        {
            id: "onboarding",
            singular: "Onboarding",
            plural: "Onboarding",
            icon: "UserPlus",
            path: "/hr/onboarding",
            displayField: "employee",
            defaultSort: { field: "startAt", dir: "desc" },
            fields: [
                { name: "employee", kind: "text", required: true, sortable: true },
                { name: "buddy", kind: "text" },
                { name: "startAt", kind: "date", required: true, sortable: true, width: 130 },
                { name: "tasksTotal", kind: "number", align: "right" },
                { name: "tasksDone", kind: "number", align: "right" },
                { name: "completionPct", label: "Completion %", kind: "number", align: "right" },
                { name: "status", kind: "enum", required: true, options: [
                        { value: "pending", label: "Pending", intent: "warning" },
                        { value: "in-progress", label: "In progress", intent: "info" },
                        { value: "completed", label: "Completed", intent: "success" },
                    ] },
            ],
            seedCount: 8,
            seed: (i) => {
                const total = 8 + (i % 5);
                const done = Math.min(total, (i * 2) % (total + 2));
                return {
                    employee: personName(i),
                    buddy: personName(i + 5),
                    startAt: daysAgo(i * 7),
                    tasksTotal: total,
                    tasksDone: done,
                    completionPct: Math.round((done / total) * 100),
                    status: done === total ? "completed" : done > 0 ? "in-progress" : "pending",
                };
            },
        },
        {
            id: "offboarding",
            singular: "Offboarding",
            plural: "Offboarding",
            icon: "UserMinus",
            path: "/hr/offboarding",
            displayField: "employee",
            fields: [
                { name: "employee", kind: "text", required: true, sortable: true },
                { name: "lastDay", kind: "date", required: true, sortable: true, width: 130 },
                { name: "reason", kind: "enum", options: [
                        { value: "voluntary", label: "Voluntary" },
                        { value: "involuntary", label: "Involuntary" },
                        { value: "retirement", label: "Retirement" },
                        { value: "contract-end", label: "Contract end" },
                    ] },
                { name: "exitInterviewAt", kind: "date" },
                { name: "assetsReturned", kind: "boolean" },
                { name: "accessRevoked", kind: "boolean" },
                { name: "finalSettlementDone", kind: "boolean" },
            ],
            seedCount: 6,
            seed: (i) => ({
                employee: personName(i + 10),
                lastDay: daysFromNow(i * 7 - 30),
                reason: pick(["voluntary", "voluntary", "retirement", "contract-end", "involuntary"], i),
                exitInterviewAt: daysFromNow(i * 7 - 25),
                assetsReturned: i > 1,
                accessRevoked: i > 2,
                finalSettlementDone: i > 3,
            }),
        },
    ],
    extraNav: [
        { id: "hr.control-room.nav", label: "HR Control Room", icon: "LayoutDashboard", path: "/hr/control-room", view: "hr-payroll.control-room.view", order: 0 },
        { id: "hr.reports.nav", label: "Reports", icon: "BarChart3", path: "/hr/reports", view: "hr-payroll.reports.view" },
        { id: "hr.headcount.nav", label: "Headcount", icon: "Users", path: "/hr/headcount", view: "hr-payroll.headcount.view" },
    ],
    extraViews: [
        hrPayrollControlRoomView,
        hrPayrollReportsIndexView,
        hrPayrollReportsDetailView,
        hrHeadcountView,
    ],
    commands: [
        { id: "hr.go.control-room", label: "HR: Control Room", icon: "LayoutDashboard", run: () => { window.location.hash = "/hr/control-room"; } },
        { id: "hr.go.reports", label: "HR: Reports", icon: "BarChart3", run: () => { window.location.hash = "/hr/reports"; } },
        { id: "hr.go.headcount", label: "HR: Headcount", icon: "Users", run: () => { window.location.hash = "/hr/headcount"; } },
        { id: "hr.new-employee", label: "New employee", icon: "UserPlus", run: () => { window.location.hash = "/hr/employees/new"; } },
        { id: "hr.new-leave", label: "Apply leave", icon: "Calendar", run: () => { window.location.hash = "/hr/leave-applications/new"; } },
        { id: "hr.new-expense", label: "Submit expense", icon: "ReceiptText", run: () => { window.location.hash = "/hr/expense-claims/new"; } },
        { id: "hr.run-payroll", label: "Run payroll", icon: "Banknote", run: () => { window.location.hash = "/hr/payroll/new"; } },
        { id: "hr.new-requisition", label: "New job requisition", icon: "ClipboardList", run: () => { window.location.hash = "/hr/job-requisitions/new"; } },
    ],
});
