import { buildDomainPlugin } from "./_factory/buildDomainPlugin";
import { SECTIONS } from "./_factory/sections";
import { STATUS_TICKET, PRIORITY } from "./_factory/options";
import { code, daysAgo, personName, pick } from "./_factory/seeds";
import { issuesKanbanView } from "./issues-pages";
import { issuesControlRoomView, issuesReportsIndexView, issuesReportsDetailView, } from "./issues-dashboard";
const COMPONENTS = [
    { value: "auth", label: "Auth" },
    { value: "billing", label: "Billing" },
    { value: "dashboard", label: "Dashboard" },
    { value: "api", label: "API" },
    { value: "search", label: "Search" },
    { value: "mobile", label: "Mobile" },
    { value: "email", label: "Email" },
    { value: "reports", label: "Reports" },
];
const LABELS = [
    { value: "bug", label: "Bug" },
    { value: "regression", label: "Regression" },
    { value: "performance", label: "Performance" },
    { value: "security", label: "Security" },
    { value: "ux", label: "UX" },
    { value: "docs", label: "Docs" },
    { value: "infra", label: "Infra" },
];
export const issuesPlugin = buildDomainPlugin({
    id: "issues",
    label: "Issues",
    icon: "AlertCircle",
    section: SECTIONS.operations,
    order: 5,
    resources: [
        {
            id: "issue",
            singular: "Issue",
            plural: "Issues",
            icon: "AlertCircle",
            path: "/issues",
            displayField: "code",
            defaultSort: { field: "updatedAt", dir: "desc" },
            pageSize: 25,
            fields: [
                { name: "code", kind: "text", required: true, sortable: true, width: 120 },
                { name: "title", kind: "text", required: true, sortable: true },
                { name: "component", kind: "enum", options: COMPONENTS, sortable: true, width: 120 },
                { name: "kind", kind: "enum", options: [
                        { value: "bug", label: "Bug", intent: "danger" },
                        { value: "regression", label: "Regression", intent: "warning" },
                        { value: "feature", label: "Feature", intent: "accent" },
                        { value: "task", label: "Task", intent: "info" },
                        { value: "doc", label: "Docs", intent: "neutral" },
                    ], sortable: true, width: 120 },
                { name: "severity", kind: "enum", options: [
                        { value: "critical", label: "Critical", intent: "danger" },
                        { value: "major", label: "Major", intent: "warning" },
                        { value: "minor", label: "Minor", intent: "info" },
                        { value: "trivial", label: "Trivial", intent: "neutral" },
                    ], sortable: true, width: 110 },
                { name: "priority", kind: "enum", options: PRIORITY, sortable: true },
                { name: "status", kind: "enum", options: STATUS_TICKET, sortable: true },
                { name: "assignee", kind: "text", sortable: true },
                { name: "reporter", kind: "text" },
                { name: "reporterKind", kind: "enum", options: [
                        { value: "customer", label: "Customer" },
                        { value: "internal", label: "Internal" },
                        { value: "automation", label: "Automation" },
                    ], width: 110 },
                { name: "labels", kind: "multi-enum", options: LABELS },
                { name: "foundInRelease", kind: "text", width: 120 },
                { name: "fixedInRelease", kind: "text", width: 120 },
                { name: "createdAt", kind: "datetime", sortable: true },
                { name: "resolvedAt", kind: "datetime" },
                { name: "updatedAt", kind: "datetime", sortable: true },
                { name: "slaBreached", kind: "boolean", width: 100 },
                { name: "description", kind: "textarea", formSection: "Details" },
                { name: "repro", label: "Reproduction", kind: "textarea", formSection: "Details" },
                { name: "resolution", kind: "textarea", formSection: "Details" },
            ],
            seedCount: 60,
            seed: (i) => {
                const created = daysAgo(i * 0.5);
                const isResolved = i % 3 === 2;
                return {
                    code: code("ISS", i, 5),
                    title: pick([
                        "Login fails in Safari 18", "Slow dashboard with > 1k rows",
                        "Typo in settings footer", "Export broken on large accounts",
                        "Email bounces on subdomain", "API 429 under burst",
                        "Mobile keyboard overlaps input", "Search misses recent items",
                        "Incorrect tax computed", "Dark-mode contrast issue",
                        "Cron job intermittently fails", "Webhook signature mismatch",
                    ], i),
                    component: pick(COMPONENTS.map((c) => c.value), i),
                    kind: pick(["bug", "bug", "regression", "feature", "task", "doc"], i),
                    severity: pick(["critical", "major", "minor", "major", "trivial"], i),
                    priority: pick(["low", "normal", "normal", "high", "urgent"], i),
                    status: pick(["open", "in_progress", "resolved", "closed"], i),
                    assignee: personName(i),
                    reporter: personName(i + 7),
                    reporterKind: pick(["customer", "customer", "internal", "automation"], i),
                    labels: pick([["bug"], ["regression", "security"], ["performance"], ["ux"], ["docs"], ["infra"]], i),
                    foundInRelease: pick(["v2.3.1", "v2.3.2", "v2.4.0", "v2.4.1"], i),
                    fixedInRelease: isResolved ? pick(["v2.4.1", "v2.4.2", "v2.5.0"], i) : "",
                    createdAt: created,
                    resolvedAt: isResolved ? daysAgo(i * 0.3) : "",
                    updatedAt: daysAgo(i * 0.4),
                    slaBreached: i % 11 === 0,
                    description: "",
                    repro: "Steps: 1. …",
                    resolution: isResolved ? "Fixed by rolling back feature flag X." : "",
                };
            },
        },
        {
            id: "release",
            singular: "Release",
            plural: "Releases",
            icon: "Package",
            path: "/issues/releases",
            displayField: "name",
            defaultSort: { field: "releasedAt", dir: "desc" },
            fields: [
                { name: "name", kind: "text", required: true, sortable: true, width: 140 },
                { name: "codename", kind: "text" },
                { name: "releasedAt", kind: "date", required: true, sortable: true },
                { name: "channel", kind: "enum", options: [
                        { value: "alpha", label: "Alpha" },
                        { value: "beta", label: "Beta" },
                        { value: "rc", label: "RC" },
                        { value: "stable", label: "Stable" },
                    ] },
                { name: "issuesFixed", kind: "number", align: "right" },
                { name: "regressions", kind: "number", align: "right" },
                { name: "status", kind: "enum", options: [
                        { value: "planned", label: "Planned", intent: "info" },
                        { value: "released", label: "Released", intent: "success" },
                        { value: "yanked", label: "Yanked", intent: "danger" },
                    ] },
            ],
            seedCount: 10,
            seed: (i) => ({
                name: `v2.${Math.floor(i / 2)}.${i % 2}`,
                codename: pick(["Nimbus", "Orion", "Pegasus", "Quasar", "Rigel", "Sirius"], i),
                releasedAt: daysAgo((10 - i) * 14),
                channel: pick(["alpha", "beta", "rc", "stable", "stable"], i),
                issuesFixed: 5 + (i * 7) % 40,
                regressions: i % 4,
                status: i < 8 ? "released" : "planned",
            }),
        },
        {
            id: "issue-comment",
            singular: "Comment",
            plural: "Comments",
            icon: "MessageSquare",
            path: "/issues/comments",
            displayField: "id",
            defaultSort: { field: "createdAt", dir: "desc" },
            fields: [
                { name: "issueCode", label: "Issue", kind: "text", required: true, sortable: true },
                { name: "author", kind: "text", required: true },
                { name: "body", kind: "text", required: true },
                { name: "createdAt", kind: "datetime", sortable: true },
                { name: "internal", kind: "boolean", width: 90 },
            ],
            seedCount: 60,
            seed: (i) => ({
                issueCode: code("ISS", i % 60, 5),
                author: personName(i),
                body: pick([
                    "Repro'd on Chrome 131.", "Added tests.", "Cannot repro — need env details.",
                    "Shipping in v2.5.0.", "Rolling back feature flag.", "Thanks — closing.",
                ], i),
                createdAt: daysAgo(i * 0.3),
                internal: i % 3 === 0,
            }),
        },
        {
            id: "issue-watcher",
            singular: "Watcher",
            plural: "Watchers",
            icon: "Eye",
            path: "/issues/watchers",
            fields: [
                { name: "issueCode", kind: "text", required: true, sortable: true },
                { name: "user", kind: "text", required: true, sortable: true },
                { name: "addedAt", kind: "datetime" },
            ],
            seedCount: 40,
            seed: (i) => ({
                issueCode: code("ISS", i % 60, 5),
                user: personName(i),
                addedAt: daysAgo(i * 0.4),
            }),
        },
    ],
    extraNav: [
        { id: "issues.control-room.nav", label: "Issues Control Room", icon: "LayoutDashboard", path: "/issues/control-room", view: "issues.control-room.view", order: 0 },
        { id: "issues.reports.nav", label: "Reports", icon: "BarChart3", path: "/issues/reports", view: "issues.reports.view" },
        { id: "issues.board.nav", label: "Board", icon: "LayoutGrid", path: "/issues/board", view: "issues.kanban.view" },
    ],
    extraViews: [
        issuesControlRoomView,
        issuesReportsIndexView,
        issuesReportsDetailView,
        issuesKanbanView,
    ],
    commands: [
        { id: "issues.go.control-room", label: "Issues: Control Room", icon: "LayoutDashboard", run: () => { window.location.hash = "/issues/control-room"; } },
        { id: "issues.go.reports", label: "Issues: Reports", icon: "BarChart3", run: () => { window.location.hash = "/issues/reports"; } },
        { id: "issues.go.board", label: "Issues: Board", icon: "LayoutGrid", run: () => { window.location.hash = "/issues/board"; } },
        { id: "issues.new", label: "New issue", icon: "Plus", run: () => { window.location.hash = "/issues/new"; } },
        { id: "issues.new-release", label: "New release", icon: "Package", run: () => { window.location.hash = "/issues/releases/new"; } },
    ],
});
