import { buildDomainPlugin } from "./_factory/buildDomainPlugin";
import { SECTIONS } from "./_factory/sections";
import { STATUS_TICKET, PRIORITY } from "./_factory/options";
import { code, daysAgo, daysFromNow, pick } from "./_factory/seeds";
import { cmmsControlRoomView, cmmsReportsIndexView, cmmsReportsDetailView, } from "./maintenance-cmms-dashboard";
const ASSETS = ["Forklift #2", "HVAC-North", "Press A", "Conveyor 1", "Compressor B", "Pump 3", "Robot-R5", "CNC-01"];
const TECHS = ["Taylor Turing", "Jordan Hamilton", "Casey Pappas", "Morgan Liskov", "Riley Perlman"];
const WORK_TYPES = [
    { value: "corrective", label: "Corrective" },
    { value: "preventive", label: "Preventive" },
    { value: "predictive", label: "Predictive" },
    { value: "inspection", label: "Inspection" },
    { value: "emergency", label: "Emergency" },
];
export const maintenanceCmmsPlugin = buildDomainPlugin({
    id: "maintenance-cmms",
    label: "Maintenance (CMMS)",
    icon: "Hammer",
    section: SECTIONS.supplyChain,
    order: 6,
    resources: [
        {
            id: "work-order",
            singular: "Work Order",
            plural: "Work Orders",
            icon: "ClipboardCheck",
            path: "/cmms/work-orders",
            displayField: "code",
            defaultSort: { field: "dueAt", dir: "asc" },
            pageSize: 25,
            fields: [
                { name: "code", kind: "text", required: true, sortable: true, width: 120 },
                { name: "title", kind: "text", required: true, sortable: true },
                { name: "asset", kind: "text", required: true, sortable: true },
                { name: "workType", kind: "enum", required: true, options: WORK_TYPES, sortable: true },
                { name: "task", kind: "text" },
                { name: "technician", kind: "text", sortable: true },
                { name: "priority", kind: "enum", options: PRIORITY, sortable: true },
                { name: "status", kind: "enum", options: STATUS_TICKET, sortable: true },
                { name: "createdAt", kind: "date", sortable: true, width: 130 },
                { name: "dueAt", kind: "date", sortable: true, width: 130 },
                { name: "completedAt", kind: "date", sortable: true },
                { name: "estimatedHours", kind: "number", align: "right" },
                { name: "actualHours", kind: "number", align: "right" },
                { name: "overdue", kind: "boolean", width: 90 },
                { name: "laborCost", kind: "currency", align: "right" },
                { name: "partsCost", kind: "currency", align: "right" },
                { name: "notes", kind: "textarea", formSection: "Notes" },
            ],
            seedCount: 40,
            seed: (i) => {
                const created = daysAgo(i * 2);
                const isCompleted = i % 3 === 2;
                const due = daysAgo(i * 2 - 5);
                return {
                    code: code("WO", i, 6),
                    title: pick([
                        "Replace motor bearing", "Lubricate chain", "Inspect belt",
                        "Calibrate sensor", "Replace filter", "Emergency repair",
                        "Monthly PM check", "Quarterly overhaul",
                    ], i),
                    asset: pick(ASSETS, i),
                    workType: pick(["corrective", "preventive", "preventive", "predictive", "inspection", "emergency"], i),
                    task: pick(["Inspect", "Replace filter", "Lubricate", "Calibrate", "Replace bearing"], i),
                    technician: pick(TECHS, i),
                    priority: pick(["low", "normal", "high"], i),
                    status: isCompleted ? "resolved" : pick(["open", "in_progress"], i),
                    createdAt: created,
                    dueAt: due,
                    completedAt: isCompleted ? daysAgo(i * 2 - 3) : "",
                    estimatedHours: pick([1, 2, 4, 8], i),
                    actualHours: isCompleted ? pick([1, 2, 4, 6], i) : 0,
                    overdue: !isCompleted && Date.parse(due) < Date.now(),
                    laborCost: (isCompleted ? pick([1, 2, 4, 6], i) : 0) * 80,
                    partsCost: (i * 29) % 500,
                    notes: "",
                };
            },
        },
        {
            id: "pm-schedule",
            singular: "PM Schedule",
            plural: "PM Schedules",
            icon: "CalendarClock",
            path: "/cmms/pm-schedules",
            displayField: "code",
            defaultSort: { field: "nextDueAt", dir: "asc" },
            fields: [
                { name: "code", kind: "text", required: true, sortable: true },
                { name: "asset", kind: "text", required: true, sortable: true },
                { name: "task", kind: "text", required: true },
                { name: "intervalDays", kind: "number", align: "right" },
                { name: "lastDoneAt", kind: "date", sortable: true, width: 130 },
                { name: "nextDueAt", kind: "date", required: true, sortable: true, width: 130 },
                { name: "dueSoon", kind: "boolean", width: 110 },
                { name: "missed", kind: "boolean", width: 90 },
                { name: "lastCompletedOnTime", kind: "boolean", width: 140 },
                { name: "active", kind: "boolean" },
            ],
            seedCount: 20,
            seed: (i) => {
                const interval = pick([30, 60, 90, 180, 365], i);
                const nextDue = daysFromNow(interval - (i % interval));
                return {
                    code: code("PM", i, 5),
                    asset: pick(ASSETS, i),
                    task: pick(["Oil change", "Belt inspection", "Sensor calibration", "Full overhaul", "Cleaning"], i),
                    intervalDays: interval,
                    lastDoneAt: daysAgo(interval - (i % interval)),
                    nextDueAt: nextDue,
                    dueSoon: (Date.parse(nextDue) - Date.now()) / 86_400_000 < 30,
                    missed: i % 9 === 0,
                    lastCompletedOnTime: i % 5 !== 0,
                    active: i !== 19,
                };
            },
        },
        {
            id: "downtime",
            singular: "Downtime Event",
            plural: "Downtime Events",
            icon: "PowerOff",
            path: "/cmms/downtimes",
            defaultSort: { field: "startedAt", dir: "desc" },
            fields: [
                { name: "code", kind: "text", required: true, sortable: true },
                { name: "asset", kind: "text", required: true, sortable: true },
                { name: "reason", kind: "enum", options: [
                        { value: "breakdown", label: "Breakdown" },
                        { value: "planned-pm", label: "Planned PM" },
                        { value: "changeover", label: "Changeover" },
                        { value: "power-loss", label: "Power loss" },
                        { value: "material-shortage", label: "Material shortage" },
                    ] },
                { name: "startedAt", kind: "datetime", required: true, sortable: true },
                { name: "endedAt", kind: "datetime" },
                { name: "durationHours", kind: "number", align: "right", sortable: true },
                { name: "costImpact", kind: "currency", align: "right" },
            ],
            seedCount: 18,
            seed: (i) => ({
                code: code("DT", i, 5),
                asset: pick(ASSETS, i),
                reason: pick(["breakdown", "planned-pm", "changeover", "power-loss", "material-shortage"], i),
                startedAt: daysAgo(i),
                endedAt: daysAgo(i - 0.1),
                durationHours: 1 + (i * 0.7) % 8,
                costImpact: 500 + (i * 311) % 5000,
            }),
        },
        {
            id: "spare-part",
            singular: "Spare Part",
            plural: "Spare Parts",
            icon: "Package",
            path: "/cmms/spare-parts",
            fields: [
                { name: "sku", kind: "text", required: true, sortable: true, width: 130 },
                { name: "name", kind: "text", required: true, sortable: true },
                { name: "asset", kind: "text" },
                { name: "onHand", kind: "number", align: "right" },
                { name: "reorderPoint", kind: "number", align: "right" },
                { name: "unitCost", kind: "currency", align: "right" },
                { name: "lastUsedAt", kind: "date" },
            ],
            seedCount: 30,
            seed: (i) => ({
                sku: `SP-${String(10000 + i).slice(-5)}`,
                name: pick(["Motor", "Filter", "Belt", "Seal", "Pump", "Thermostat", "Sensor", "Bearing"], i),
                asset: pick(ASSETS, i),
                onHand: (i * 3) % 100,
                reorderPoint: 10 + (i * 2) % 20,
                unitCost: 15 + (i * 11) % 250,
                lastUsedAt: daysAgo(i * 2),
            }),
        },
        {
            id: "asset-kpi",
            singular: "Asset KPI",
            plural: "Asset KPIs",
            icon: "Gauge",
            path: "/cmms/asset-kpis",
            displayField: "asset",
            fields: [
                { name: "asset", kind: "text", required: true, sortable: true },
                { name: "mtbfDays", label: "MTBF (days)", kind: "number", align: "right", sortable: true },
                { name: "mttrHours", label: "MTTR (hrs)", kind: "number", align: "right", sortable: true },
                { name: "availabilityPct", label: "Availability %", kind: "number", align: "right", sortable: true },
                { name: "failures", kind: "number", align: "right" },
                { name: "asOfAt", kind: "date" },
            ],
            seedCount: 8,
            seed: (i) => ({
                asset: pick(ASSETS, i),
                mtbfDays: 30 + (i * 17) % 200,
                mttrHours: 1 + (i * 0.5) % 10,
                availabilityPct: 80 + (i * 3) % 20,
                failures: 1 + (i % 8),
                asOfAt: daysAgo(i * 7),
            }),
        },
        {
            id: "checklist",
            singular: "Inspection Checklist",
            plural: "Inspection Checklists",
            icon: "ListChecks",
            path: "/cmms/checklists",
            fields: [
                { name: "name", kind: "text", required: true, sortable: true },
                { name: "assetCategory", kind: "text" },
                { name: "itemsCount", kind: "number", align: "right" },
                { name: "estimatedMinutes", kind: "number", align: "right" },
                { name: "active", kind: "boolean" },
            ],
            seedCount: 10,
            seed: (i) => ({
                name: pick([
                    "Forklift daily walk-around", "HVAC monthly PM", "Press A inspection",
                    "Conveyor weekly clean", "Compressor annual overhaul",
                ], i),
                assetCategory: pick(["Vehicle", "HVAC", "Press", "Conveyor", "Compressor"], i),
                itemsCount: 5 + (i * 2) % 20,
                estimatedMinutes: 15 + (i * 5) % 60,
                active: i !== 9,
            }),
        },
    ],
    extraNav: [
        { id: "maintenance-cmms.control-room.nav", label: "Maintenance Control Room", icon: "LayoutDashboard", path: "/cmms/control-room", view: "maintenance-cmms.control-room.view", order: 0 },
        { id: "maintenance-cmms.reports.nav", label: "Reports", icon: "BarChart3", path: "/cmms/reports", view: "maintenance-cmms.reports.view" },
    ],
    extraViews: [
        cmmsControlRoomView,
        cmmsReportsIndexView,
        cmmsReportsDetailView,
    ],
    commands: [
        { id: "cmms.go.control-room", label: "CMMS: Control Room", icon: "LayoutDashboard", run: () => { window.location.hash = "/cmms/control-room"; } },
        { id: "cmms.go.reports", label: "CMMS: Reports", icon: "BarChart3", run: () => { window.location.hash = "/cmms/reports"; } },
        { id: "cmms.new-wo", label: "New work order", icon: "Plus", run: () => { window.location.hash = "/cmms/work-orders/new"; } },
        { id: "cmms.new-pm", label: "New PM schedule", icon: "CalendarClock", run: () => { window.location.hash = "/cmms/pm-schedules/new"; } },
        { id: "cmms.new-downtime", label: "Log downtime", icon: "PowerOff", run: () => { window.location.hash = "/cmms/downtimes/new"; } },
    ],
});
