import { buildDomainPlugin } from "./_factory/buildDomainPlugin";
import { SECTIONS } from "./_factory/sections";
import { STATUS_TICKET, PRIORITY, STATUS_ACTIVE } from "./_factory/options";
import { code, daysAgo, daysFromNow, personName, personEmail, pick } from "./_factory/seeds";
import { projectsBoardView } from "./projects-pages";
import {
  projectsControlRoomView,
  projectsReportsIndexView,
  projectsReportsDetailView,
} from "./projects-dashboard";

const OWNERS = ["sam@gutu.dev", "alex@gutu.dev", "taylor@gutu.dev", "jordan@gutu.dev"];
const PROJECT_NAMES = [
  "Migrate to v2", "Redesign billing", "Launch EU", "Mobile app", "Data warehouse",
  "SOC 2 Type II", "API v3", "Customer portal", "Marketing site refresh", "Analytics pipeline",
];

export const projectsPlugin = buildDomainPlugin({
  id: "projects",
  label: "Projects",
  icon: "FolderKanban",
  section: SECTIONS.operations,
  order: 4,
  resources: [
    {
      id: "project",
      singular: "Project",
      plural: "Projects",
      icon: "FolderKanban",
      path: "/projects",
      defaultSort: { field: "dueAt", dir: "asc" },
      fields: [
        { name: "code", kind: "text", required: true, sortable: true, width: 100 },
        { name: "name", kind: "text", required: true, sortable: true },
        { name: "owner", kind: "text", sortable: true },
        { name: "portfolio", kind: "enum", options: [
          { value: "product", label: "Product" },
          { value: "infra", label: "Infra" },
          { value: "gtm", label: "GTM" },
          { value: "ops", label: "Ops" },
        ] },
        { name: "status", kind: "enum", options: STATUS_TICKET, sortable: true },
        { name: "priority", kind: "enum", options: PRIORITY },
        { name: "progressPct", label: "Progress %", kind: "number", align: "right", sortable: true, width: 110 },
        { name: "riskLevel", kind: "enum", options: [
          { value: "low", label: "Low", intent: "success" },
          { value: "medium", label: "Medium", intent: "warning" },
          { value: "high", label: "High", intent: "danger" },
        ], width: 100 },
        { name: "riskScore", kind: "number", align: "right", readonly: true, width: 100 },
        { name: "startAt", kind: "date", sortable: true, width: 130 },
        { name: "dueAt", kind: "date", sortable: true, width: 130 },
        { name: "budgetHours", kind: "number", align: "right", width: 110 },
        { name: "actualHours", kind: "number", align: "right", width: 110 },
        { name: "budgetCost", kind: "currency", align: "right" },
        { name: "actualCost", kind: "currency", align: "right" },
        { name: "description", kind: "textarea", formSection: "About" },
      ],
      seedCount: 18,
      seed: (i) => {
        const budgetHours = 100 + (i * 73) % 900;
        const progressPct = 10 + (i * 7) % 90;
        const actualHours = Math.round((budgetHours * progressPct) / 100);
        const budgetCost = budgetHours * 120;
        const actualCost = actualHours * 125;
        return {
          code: code("PRJ", i, 4),
          name: pick(PROJECT_NAMES, i),
          owner: pick(OWNERS, i),
          portfolio: pick(["product", "infra", "gtm", "ops"], i),
          status: pick(["in_progress", "in_progress", "in_progress", "open", "resolved"], i),
          priority: pick(["normal", "high", "urgent", "low"], i),
          progressPct,
          riskLevel: pick(["low", "low", "medium", "medium", "high"], i),
          riskScore: 20 + (i * 7) % 80,
          startAt: daysAgo(60 - i * 3),
          dueAt: daysFromNow(30 + i * 3),
          budgetHours,
          actualHours,
          budgetCost,
          actualCost,
          description: "",
        };
      },
    },
    {
      id: "task",
      singular: "Task",
      plural: "Tasks",
      icon: "CheckSquare",
      path: "/projects/tasks",
      displayField: "title",
      defaultSort: { field: "dueAt", dir: "asc" },
      pageSize: 25,
      fields: [
        { name: "code", kind: "text", sortable: true, width: 110 },
        { name: "title", kind: "text", required: true, sortable: true },
        { name: "projectCode", label: "Project", kind: "text", required: true, sortable: true, width: 110 },
        { name: "assignee", kind: "text", sortable: true },
        { name: "status", kind: "enum", required: true, sortable: true, options: [
          { value: "todo", label: "Todo", intent: "neutral" },
          { value: "in_progress", label: "In progress", intent: "info" },
          { value: "review", label: "In review", intent: "warning" },
          { value: "done", label: "Done", intent: "success" },
          { value: "blocked", label: "Blocked", intent: "danger" },
        ] },
        { name: "priority", kind: "enum", options: PRIORITY, sortable: true },
        { name: "estimatedHours", kind: "number", align: "right", width: 100 },
        { name: "actualHours", kind: "number", align: "right", width: 100 },
        { name: "storyPoints", kind: "number", align: "right", width: 100 },
        { name: "sprintCode", label: "Sprint", kind: "text", width: 120 },
        { name: "milestoneId", label: "Milestone", kind: "text" },
        { name: "parentTaskId", label: "Parent", kind: "text" },
        { name: "labels", kind: "multi-enum", options: [
          { value: "bug", label: "Bug" },
          { value: "feature", label: "Feature" },
          { value: "chore", label: "Chore" },
          { value: "doc", label: "Docs" },
          { value: "research", label: "Research" },
        ] },
        { name: "createdAt", kind: "date", sortable: true },
        { name: "dueAt", kind: "date", sortable: true },
        { name: "overdue", kind: "boolean", width: 90 },
        { name: "description", kind: "textarea", formSection: "Details" },
      ],
      seedCount: 80,
      seed: (i) => {
        const due = daysFromNow(i % 20 - 5);
        return {
          code: code("TASK", i, 5),
          title: pick([
            "Schema migration plan", "Auth audit", "Update billing webhook",
            "QA sweep", "Refactor dashboards", "Deploy canary",
            "Write docs", "Load test", "Stakeholder review", "Finalize designs",
          ], i),
          projectCode: code("PRJ", i % 18, 4),
          assignee: personName(i),
          status: pick(["todo", "in_progress", "in_progress", "review", "done", "blocked"], i),
          priority: pick(["low", "normal", "high", "urgent"], i),
          estimatedHours: pick([2, 4, 8, 16, 24], i),
          actualHours: pick([0, 2, 4, 8, 12], i),
          storyPoints: pick([1, 2, 3, 5, 8, 13], i),
          sprintCode: code("SPR", Math.floor(i / 15), 4),
          milestoneId: i % 5 === 0 ? `ms_${(i % 10) + 1}` : "",
          parentTaskId: "",
          labels: pick([["feature"], ["bug"], ["chore"], ["doc", "research"], []], i),
          createdAt: daysAgo((i * 7) % 60),
          dueAt: due,
          overdue: Date.parse(due) < Date.now() && i % 4 !== 3,
          description: "",
        };
      },
    },
    {
      id: "milestone",
      singular: "Milestone",
      plural: "Milestones",
      icon: "Flag",
      path: "/projects/milestones",
      displayField: "name",
      defaultSort: { field: "dueAt", dir: "asc" },
      fields: [
        { name: "name", kind: "text", required: true, sortable: true },
        { name: "projectCode", kind: "text", required: true, sortable: true },
        { name: "dueAt", kind: "date", required: true, sortable: true },
        { name: "status", kind: "enum", required: true, options: [
          { value: "upcoming", label: "Upcoming", intent: "info" },
          { value: "in-progress", label: "In progress", intent: "warning" },
          { value: "done", label: "Done", intent: "success" },
          { value: "missed", label: "Missed", intent: "danger" },
        ] },
        { name: "owner", kind: "text" },
        { name: "description", kind: "textarea", formSection: "About" },
      ],
      seedCount: 16,
      seed: (i) => ({
        name: pick([
          "Alpha release", "Beta release", "GA launch", "Security audit done",
          "Migration complete", "Infra cutover", "Design review", "QA sign-off",
        ], i),
        projectCode: code("PRJ", i % 18, 4),
        dueAt: daysFromNow((i - 3) * 10),
        status: pick(["upcoming", "upcoming", "in-progress", "done", "missed"], i),
        owner: pick(OWNERS, i),
        description: "",
      }),
    },
    {
      id: "sprint",
      singular: "Sprint",
      plural: "Sprints",
      icon: "Timer",
      path: "/projects/sprints",
      displayField: "name",
      defaultSort: { field: "startAt", dir: "desc" },
      fields: [
        { name: "code", kind: "text", required: true, sortable: true, width: 120 },
        { name: "name", kind: "text", required: true, sortable: true },
        { name: "team", kind: "text", sortable: true },
        { name: "startAt", kind: "date", sortable: true },
        { name: "endAt", kind: "date", sortable: true },
        { name: "plannedPoints", kind: "number", align: "right" },
        { name: "completedPoints", kind: "number", align: "right" },
        { name: "status", kind: "enum", options: [
          { value: "planned", label: "Planned", intent: "info" },
          { value: "active", label: "Active", intent: "warning" },
          { value: "completed", label: "Completed", intent: "success" },
          { value: "cancelled", label: "Cancelled", intent: "danger" },
        ] },
        { name: "retrospective", kind: "textarea", formSection: "Retro" },
      ],
      seedCount: 8,
      seed: (i) => ({
        code: code("SPR", i, 4),
        name: `Sprint ${2026}-${String(i + 1).padStart(2, "0")}`,
        team: pick(["Platform", "Growth", "Infra", "Data"], i),
        startAt: daysAgo(60 - i * 14),
        endAt: daysAgo(60 - i * 14 - 14),
        plannedPoints: 40 + (i * 5),
        completedPoints: 30 + (i * 4 + (i % 3)),
        status: i >= 6 ? "active" : "completed",
        retrospective: "",
      }),
    },
    {
      id: "time-log",
      singular: "Time Log",
      plural: "Time Logs",
      icon: "Clock",
      path: "/projects/time-logs",
      displayField: "id",
      defaultSort: { field: "loggedAt", dir: "desc" },
      fields: [
        { name: "user", kind: "text", required: true, sortable: true },
        { name: "projectCode", kind: "text", required: true },
        { name: "taskCode", kind: "text" },
        { name: "loggedAt", kind: "date", required: true, sortable: true },
        { name: "hours", kind: "number", required: true, align: "right", sortable: true },
        { name: "billable", kind: "boolean" },
        { name: "notes", kind: "text" },
      ],
      seedCount: 50,
      seed: (i) => ({
        user: pick(OWNERS, i),
        projectCode: code("PRJ", i % 18, 4),
        taskCode: code("TASK", i % 80, 5),
        loggedAt: daysAgo(i * 0.5),
        hours: 0.5 + (i % 8),
        billable: i % 3 !== 0,
        notes: "",
      }),
    },
    {
      id: "project-member",
      singular: "Project Member",
      plural: "Project Members",
      icon: "Users",
      path: "/projects/members",
      fields: [
        { name: "projectCode", kind: "text", required: true, sortable: true },
        { name: "user", kind: "text", required: true, sortable: true },
        { name: "role", kind: "enum", options: [
          { value: "owner", label: "Owner" },
          { value: "lead", label: "Lead" },
          { value: "contributor", label: "Contributor" },
          { value: "reviewer", label: "Reviewer" },
          { value: "stakeholder", label: "Stakeholder" },
        ] },
        { name: "allocation", label: "Allocation %", kind: "number", align: "right" },
        { name: "joinedAt", kind: "date" },
      ],
      seedCount: 30,
      seed: (i) => ({
        projectCode: code("PRJ", i % 18, 4),
        user: pick(OWNERS, i),
        role: pick(["owner", "lead", "contributor", "contributor", "reviewer", "stakeholder"], i),
        allocation: pick([25, 50, 75, 100], i),
        joinedAt: daysAgo(60 - (i * 3) % 60),
      }),
    },
    {
      id: "risk",
      singular: "Risk",
      plural: "Risks",
      icon: "AlertTriangle",
      path: "/projects/risks",
      fields: [
        { name: "projectCode", kind: "text", required: true, sortable: true },
        { name: "title", kind: "text", required: true },
        { name: "severity", kind: "enum", required: true, options: [
          { value: "low", label: "Low", intent: "success" },
          { value: "medium", label: "Medium", intent: "warning" },
          { value: "high", label: "High", intent: "danger" },
        ] },
        { name: "probability", label: "Probability %", kind: "number", align: "right" },
        { name: "impact", kind: "text" },
        { name: "mitigation", kind: "textarea", formSection: "Mitigation" },
        { name: "owner", kind: "text" },
        { name: "status", kind: "enum", options: [
          { value: "open", label: "Open", intent: "warning" },
          { value: "mitigated", label: "Mitigated", intent: "success" },
          { value: "accepted", label: "Accepted", intent: "info" },
          { value: "closed", label: "Closed", intent: "neutral" },
        ] },
      ],
      seedCount: 14,
      seed: (i) => ({
        projectCode: code("PRJ", i % 18, 4),
        title: pick(["Vendor delay", "Scope creep", "Key person dependency", "Budget overrun", "Technical debt"], i),
        severity: pick(["low", "medium", "high"], i),
        probability: 10 + (i * 11) % 80,
        impact: pick(["Delayed launch", "Budget overrun", "Customer churn", "Compliance gap"], i),
        mitigation: "Track weekly + escalate if needed.",
        owner: pick(OWNERS, i),
        status: pick(["open", "mitigated", "accepted", "closed"], i),
      }),
    },
  ],
  extraNav: [
    { id: "projects.control-room.nav", label: "Control Room", icon: "LayoutDashboard", path: "/projects/control-room", view: "projects.control-room.view", order: 0 },
    { id: "projects.reports.nav", label: "Reports", icon: "BarChart3", path: "/projects/reports", view: "projects.reports.view" },
    { id: "projects.board.nav", label: "Board", icon: "LayoutGrid", path: "/projects/board", view: "projects.board.view" },
  ],
  extraViews: [
    projectsControlRoomView,
    projectsReportsIndexView,
    projectsReportsDetailView,
    projectsBoardView,
  ],
  commands: [
    { id: "projects.go.control-room", label: "Projects: Control Room", icon: "LayoutDashboard", run: () => { window.location.hash = "/projects/control-room"; } },
    { id: "projects.go.reports", label: "Projects: Reports", icon: "BarChart3", run: () => { window.location.hash = "/projects/reports"; } },
    { id: "projects.go.board", label: "Projects: Board", icon: "LayoutGrid", run: () => { window.location.hash = "/projects/board"; } },
    { id: "projects.new-project", label: "New project", icon: "Plus", run: () => { window.location.hash = "/projects/new"; } },
    { id: "projects.new-task", label: "New task", icon: "CheckSquare", run: () => { window.location.hash = "/projects/tasks/new"; } },
    { id: "projects.new-sprint", label: "New sprint", icon: "Timer", run: () => { window.location.hash = "/projects/sprints/new"; } },
    { id: "projects.log-time", label: "Log time", icon: "Clock", run: () => { window.location.hash = "/projects/time-logs/new"; } },
  ],
});
