import { buildDomainPlugin } from "./_factory/buildDomainPlugin";
import { SECTIONS } from "./_factory/sections";
import { STATUS_TICKET, SEVERITY } from "./_factory/options";
import { code, daysAgo, daysFromNow, personName, pick } from "./_factory/seeds";
import {
  qualityControlRoomView,
  qualityReportsIndexView,
  qualityReportsDetailView,
} from "./quality-dashboard";

const PRODUCTS = ["Widget A", "Gizmo B", "Part C", "Bracket D", "Motor E", "Sensor F"];
const SUPPLIERS = ["Acme Supply", "Globex Parts", "Initech Components", "Umbrella Hardware"];
const DEFECT_TYPES = ["Dimensional", "Surface finish", "Functional", "Material", "Assembly", "Packaging"];

export const qualityPlugin = buildDomainPlugin({
  id: "quality",
  label: "Quality",
  icon: "ShieldCheck",
  section: SECTIONS.supplyChain,
  order: 7,
  resources: [
    {
      id: "inspection",
      singular: "Inspection",
      plural: "Inspections",
      icon: "Microscope",
      path: "/quality/inspections",
      displayField: "code",
      defaultSort: { field: "inspectedAt", dir: "desc" },
      pageSize: 25,
      fields: [
        { name: "code", kind: "text", required: true, sortable: true, width: 110 },
        { name: "product", kind: "text", required: true, sortable: true },
        { name: "batchCode", kind: "text" },
        { name: "inspector", kind: "text", sortable: true },
        { name: "inspectionType", kind: "enum", options: [
          { value: "incoming", label: "Incoming" },
          { value: "in-process", label: "In-process" },
          { value: "final", label: "Final" },
          { value: "customer-return", label: "Customer return" },
        ], sortable: true, width: 140 },
        { name: "result", kind: "enum", required: true, options: [
          { value: "pass", label: "Pass", intent: "success" },
          { value: "fail", label: "Fail", intent: "danger" },
          { value: "conditional", label: "Conditional", intent: "warning" },
        ], sortable: true, width: 120 },
        { name: "severity", kind: "enum", options: SEVERITY, sortable: true },
        { name: "passRate", label: "Pass %", kind: "number", align: "right", width: 90 },
        { name: "sampleSize", kind: "number", align: "right" },
        { name: "defectsFound", kind: "number", align: "right" },
        { name: "status", kind: "enum", options: STATUS_TICKET, sortable: true },
        { name: "inspectedAt", kind: "date", required: true, sortable: true, width: 130 },
        { name: "notes", kind: "textarea", formSection: "Notes" },
      ],
      seedCount: 30,
      seed: (i) => {
        const result = pick(["pass", "pass", "pass", "fail", "conditional"], i);
        const sampleSize = 20 + (i * 7) % 200;
        const defectsFound = result === "pass" ? 0 : 1 + (i % 5);
        return {
          code: code("QA", i, 5),
          product: pick(PRODUCTS, i),
          batchCode: `BTH-${String(10000 + i).slice(-5)}`,
          inspector: personName(i),
          inspectionType: pick(["incoming", "in-process", "final", "customer-return"], i),
          result,
          severity: pick(["info", "warn", "error"], i),
          passRate: result === "pass" ? 100 : Math.round(((sampleSize - defectsFound) / sampleSize) * 100),
          sampleSize,
          defectsFound,
          status: pick(["open", "resolved"], i),
          inspectedAt: daysAgo(i),
          notes: "",
        };
      },
    },
    {
      id: "ncr",
      singular: "NCR",
      plural: "Non-Conformance Reports",
      icon: "AlertOctagon",
      path: "/quality/ncrs",
      displayField: "code",
      defaultSort: { field: "openedAt", dir: "desc" },
      fields: [
        { name: "code", kind: "text", required: true, sortable: true, width: 120 },
        { name: "title", kind: "text", required: true, sortable: true },
        { name: "product", kind: "text", required: true },
        { name: "batchCode", kind: "text" },
        { name: "severity", kind: "enum", options: SEVERITY, sortable: true },
        { name: "rootCause", kind: "text" },
        { name: "disposition", kind: "enum", options: [
          { value: "rework", label: "Rework" },
          { value: "scrap", label: "Scrap" },
          { value: "use-as-is", label: "Use as-is" },
          { value: "return", label: "Return to supplier" },
        ], width: 160 },
        { name: "openedBy", kind: "text" },
        { name: "openedAt", kind: "date", required: true, sortable: true },
        { name: "closedAt", kind: "date" },
        { name: "status", kind: "enum", required: true, options: [
          { value: "open", label: "Open", intent: "warning" },
          { value: "investigating", label: "Investigating", intent: "info" },
          { value: "contained", label: "Contained", intent: "accent" },
          { value: "closed", label: "Closed", intent: "success" },
        ] },
        { name: "capaId", label: "Linked CAPA", kind: "text" },
        { name: "costImpact", kind: "currency", align: "right" },
      ],
      seedCount: 14,
      seed: (i) => ({
        code: code("NCR", i, 5),
        title: pick([
          "Dimension out of tolerance", "Surface finish variation",
          "Functional test failure", "Material certification missing",
          "Packaging damaged on receipt",
        ], i),
        product: pick(PRODUCTS, i),
        batchCode: `BTH-${String(10000 + i).slice(-5)}`,
        severity: pick(["info", "warn", "error"], i),
        rootCause: pick(["Machine wear", "Operator error", "Material defect", "Supplier issue", "Unknown"], i),
        disposition: pick(["rework", "scrap", "use-as-is", "return"], i),
        openedBy: personName(i),
        openedAt: daysAgo(i * 2),
        closedAt: i % 3 === 0 ? daysAgo(i) : "",
        status: pick(["open", "investigating", "contained", "closed"], i),
        capaId: i % 3 === 0 ? `CAPA-${String(1000 + i).slice(-4)}` : "",
        costImpact: 100 + (i * 317) % 5000,
      }),
    },
    {
      id: "capa",
      singular: "CAPA",
      plural: "Corrective & Preventive Actions",
      icon: "ClipboardCheck",
      path: "/quality/capas",
      displayField: "code",
      defaultSort: { field: "openedAt", dir: "desc" },
      fields: [
        { name: "code", kind: "text", required: true, sortable: true, width: 130 },
        { name: "title", kind: "text", required: true, sortable: true },
        { name: "kind", label: "Type", kind: "enum", options: [
          { value: "corrective", label: "Corrective" },
          { value: "preventive", label: "Preventive" },
        ] },
        { name: "ncrId", label: "Source NCR", kind: "text" },
        { name: "owner", kind: "text" },
        { name: "rootCauseAnalysis", kind: "textarea", formSection: "Analysis" },
        { name: "actionPlan", kind: "textarea", formSection: "Plan" },
        { name: "openedAt", kind: "date", sortable: true },
        { name: "dueAt", kind: "date", sortable: true },
        { name: "closedAt", kind: "date" },
        { name: "verified", kind: "boolean" },
        { name: "status", kind: "enum", required: true, options: [
          { value: "draft", label: "Draft", intent: "neutral" },
          { value: "in-progress", label: "In progress", intent: "info" },
          { value: "implemented", label: "Implemented", intent: "accent" },
          { value: "verified", label: "Verified", intent: "success" },
          { value: "closed", label: "Closed", intent: "neutral" },
        ] },
      ],
      seedCount: 12,
      seed: (i) => ({
        code: `CAPA-${String(1000 + i).slice(-4)}`,
        title: pick([
          "Tighten drill bit calibration", "Update SOP for assembly",
          "Supplier requalification", "Revise inspection checklist",
          "Operator retraining", "Tooling replacement",
        ], i),
        kind: pick(["corrective", "preventive"], i),
        ncrId: code("NCR", i, 5),
        owner: personName(i),
        rootCauseAnalysis: "5-whys analysis concluded…",
        actionPlan: "Step 1…",
        openedAt: daysAgo(i * 7),
        dueAt: daysFromNow(30 - i),
        closedAt: i % 3 === 0 ? daysAgo(i * 2) : "",
        verified: i % 3 === 0,
        status: pick(["in-progress", "in-progress", "implemented", "verified", "closed"], i),
      }),
    },
    {
      id: "defect",
      singular: "Defect",
      plural: "Defects",
      icon: "Bug",
      path: "/quality/defects",
      displayField: "code",
      fields: [
        { name: "code", kind: "text", required: true, sortable: true },
        { name: "inspectionCode", kind: "text" },
        { name: "product", kind: "text", required: true, sortable: true },
        { name: "batchCode", kind: "text" },
        { name: "defectType", kind: "enum", required: true, options: DEFECT_TYPES.map((d) => ({ value: d, label: d })), sortable: true, width: 140 },
        { name: "severity", kind: "enum", options: SEVERITY, sortable: true },
        { name: "supplier", kind: "text" },
        { name: "qty", kind: "number", align: "right" },
        { name: "cost", kind: "currency", align: "right" },
        { name: "detectedAt", kind: "date", sortable: true },
      ],
      seedCount: 40,
      seed: (i) => ({
        code: code("DEF", i, 6),
        inspectionCode: code("QA", i % 30, 5),
        product: pick(PRODUCTS, i),
        batchCode: `BTH-${String(10000 + i).slice(-5)}`,
        defectType: pick(DEFECT_TYPES, i),
        severity: pick(["info", "warn", "error"], i),
        supplier: pick(SUPPLIERS, i),
        qty: 1 + (i % 10),
        cost: 50 + (i * 37) % 1000,
        detectedAt: daysAgo(i * 0.5),
      }),
    },
    {
      id: "audit",
      singular: "Quality Audit",
      plural: "Quality Audits",
      icon: "ClipboardList",
      path: "/quality/audits",
      displayField: "code",
      fields: [
        { name: "code", kind: "text", required: true, sortable: true },
        { name: "title", kind: "text", required: true, sortable: true },
        { name: "kind", label: "Type", kind: "enum", options: [
          { value: "internal", label: "Internal" },
          { value: "supplier", label: "Supplier" },
          { value: "customer", label: "Customer" },
          { value: "regulatory", label: "Regulatory" },
          { value: "certification", label: "Certification (ISO)" },
        ] },
        { name: "auditor", kind: "text" },
        { name: "auditee", kind: "text" },
        { name: "severity", kind: "enum", options: SEVERITY },
        { name: "conductedAt", kind: "date", sortable: true },
        { name: "findingsCount", kind: "number", align: "right" },
        { name: "status", kind: "enum", options: [
          { value: "planned", label: "Planned", intent: "info" },
          { value: "in-progress", label: "In progress", intent: "warning" },
          { value: "completed", label: "Completed", intent: "success" },
          { value: "closed", label: "Closed", intent: "neutral" },
        ] },
      ],
      seedCount: 10,
      seed: (i) => ({
        code: code("AUD", i, 5),
        title: pick([
          "ISO 9001 surveillance", "Internal process audit",
          "Supplier qualification audit", "Customer walk-through",
          "FDA pre-inspection", "AS9100 gap audit",
        ], i),
        kind: pick(["internal", "supplier", "customer", "regulatory", "certification"], i),
        auditor: personName(i),
        auditee: pick(["Production", "Engineering", "Supplier A", "Supplier B"], i),
        severity: pick(["info", "warn", "error"], i),
        conductedAt: daysAgo(i * 20),
        findingsCount: (i * 3) % 12,
        status: pick(["completed", "completed", "in-progress", "closed", "planned"], i),
      }),
    },
    {
      id: "calibration",
      singular: "Calibration",
      plural: "Calibrations",
      icon: "Ruler",
      path: "/quality/calibrations",
      displayField: "code",
      defaultSort: { field: "nextDueAt", dir: "asc" },
      fields: [
        { name: "code", kind: "text", required: true, sortable: true },
        { name: "instrumentId", label: "Instrument", kind: "text", required: true },
        { name: "instrumentType", kind: "enum", options: [
          { value: "caliper", label: "Caliper" },
          { value: "micrometer", label: "Micrometer" },
          { value: "gauge", label: "Gauge" },
          { value: "scale", label: "Scale" },
          { value: "cmm", label: "CMM" },
          { value: "thermometer", label: "Thermometer" },
        ] },
        { name: "lastCalibratedAt", kind: "date", sortable: true },
        { name: "nextDueAt", kind: "date", required: true, sortable: true },
        { name: "calibratedBy", kind: "text" },
        { name: "passed", kind: "boolean" },
        { name: "status", kind: "enum", options: [
          { value: "in-spec", label: "In spec", intent: "success" },
          { value: "due", label: "Due", intent: "warning" },
          { value: "overdue", label: "Overdue", intent: "danger" },
        ] },
      ],
      seedCount: 12,
      seed: (i) => ({
        code: code("CAL", i, 5),
        instrumentId: `INS-${String(100 + i).padStart(4, "0")}`,
        instrumentType: pick(["caliper", "micrometer", "gauge", "scale", "cmm", "thermometer"], i),
        lastCalibratedAt: daysAgo(180 - i * 20),
        nextDueAt: daysFromNow(180 - i * 20),
        calibratedBy: personName(i),
        passed: i % 6 !== 5,
        status: i < 8 ? "in-spec" : i < 10 ? "due" : "overdue",
      }),
    },
  ],
  extraNav: [
    { id: "quality.control-room.nav", label: "Control Room", icon: "LayoutDashboard", path: "/quality/control-room", view: "quality.control-room.view", order: 0 },
    { id: "quality.reports.nav", label: "Reports", icon: "BarChart3", path: "/quality/reports", view: "quality.reports.view" },
  ],
  extraViews: [
    qualityControlRoomView,
    qualityReportsIndexView,
    qualityReportsDetailView,
  ],
  commands: [
    { id: "quality.go.control-room", label: "Quality: Control Room", icon: "LayoutDashboard", run: () => { window.location.hash = "/quality/control-room"; } },
    { id: "quality.go.reports", label: "Quality: Reports", icon: "BarChart3", run: () => { window.location.hash = "/quality/reports"; } },
    { id: "quality.new-inspection", label: "New inspection", icon: "Microscope", run: () => { window.location.hash = "/quality/inspections/new"; } },
    { id: "quality.new-ncr", label: "New NCR", icon: "AlertOctagon", run: () => { window.location.hash = "/quality/ncrs/new"; } },
    { id: "quality.new-capa", label: "New CAPA", icon: "ClipboardCheck", run: () => { window.location.hash = "/quality/capas/new"; } },
  ],
});
