import { buildDomainPlugin } from "./_factory/buildDomainPlugin";
import { SECTIONS } from "./_factory/sections";
import { STATUS_TICKET, PRIORITY } from "./_factory/options";
import { code, daysAgo, daysFromNow, personName, pick } from "./_factory/seeds";
import { supportKanbanView, supportAnalyticsView } from "./support-service-pages";
import { supportControlRoomView, supportReportsIndexView, supportReportsDetailView, } from "./support-service-dashboard";
const CHANNELS = [
    { value: "email", label: "Email" },
    { value: "chat", label: "Chat" },
    { value: "phone", label: "Phone" },
    { value: "portal", label: "Portal" },
    { value: "social", label: "Social" },
    { value: "api", label: "API" },
];
const CATEGORIES = [
    { value: "bug", label: "Bug" },
    { value: "question", label: "Question" },
    { value: "billing", label: "Billing" },
    { value: "feature", label: "Feature request" },
    { value: "account", label: "Account" },
    { value: "integration", label: "Integration" },
];
const AGENTS = ["Sam Hopper", "Alex Knuth", "Taylor Turing", "Jordan Hamilton", "Casey Pappas"];
export const supportServicePlugin = buildDomainPlugin({
    id: "support-service",
    label: "Support",
    icon: "LifeBuoy",
    section: SECTIONS.operations,
    order: 2,
    resources: [
        {
            id: "ticket",
            singular: "Ticket",
            plural: "Tickets",
            icon: "LifeBuoy",
            path: "/support/tickets",
            displayField: "code",
            defaultSort: { field: "updatedAt", dir: "desc" },
            pageSize: 25,
            fields: [
                { name: "code", kind: "text", required: true, sortable: true, width: 110 },
                { name: "subject", kind: "text", required: true, sortable: true },
                { name: "requester", kind: "text", sortable: true },
                { name: "requesterEmail", kind: "email" },
                { name: "customer", label: "Customer", kind: "text" },
                { name: "assignee", kind: "text", sortable: true },
                { name: "team", kind: "enum", options: [
                        { value: "tier-1", label: "Tier 1" },
                        { value: "tier-2", label: "Tier 2" },
                        { value: "engineering", label: "Engineering" },
                        { value: "billing", label: "Billing" },
                        { value: "success", label: "Success" },
                    ], sortable: true, width: 120 },
                { name: "channel", kind: "enum", options: CHANNELS, sortable: true, width: 110 },
                { name: "category", kind: "enum", options: CATEGORIES, sortable: true },
                { name: "priority", kind: "enum", options: PRIORITY, sortable: true },
                { name: "status", kind: "enum", options: STATUS_TICKET, sortable: true },
                { name: "slaPolicy", label: "SLA policy", kind: "text", width: 140 },
                { name: "slaDueAt", label: "SLA due", kind: "datetime", sortable: true, width: 140 },
                { name: "slaBreached", label: "Breached", kind: "boolean", width: 100 },
                { name: "slaAtRisk", label: "At risk", kind: "boolean", width: 100 },
                { name: "createdAt", kind: "datetime", sortable: true },
                { name: "firstResponseAt", label: "First response", kind: "datetime" },
                { name: "resolvedAt", label: "Resolved", kind: "datetime" },
                { name: "updatedAt", kind: "datetime", sortable: true },
                { name: "messagesCount", label: "Messages", kind: "number", align: "right", width: 100 },
                { name: "tags", kind: "multi-enum", options: [
                        { value: "vip", label: "VIP" },
                        { value: "escalated", label: "Escalated" },
                        { value: "followup", label: "Follow-up" },
                        { value: "training", label: "Training" },
                        { value: "product-feedback", label: "Product feedback" },
                    ] },
                { name: "description", kind: "textarea", formSection: "Details" },
                { name: "resolutionNotes", kind: "textarea", formSection: "Details" },
            ],
            seedCount: 50,
            seed: (i) => {
                const created = daysAgo(i * 0.6);
                const c = Date.parse(created);
                const isResolved = i % 4 === 2 || i % 4 === 3;
                const firstResponseMin = 15 + ((i * 37) % 720);
                const resolvedHrs = 2 + ((i * 7) % 72);
                const slaHrs = 24;
                return {
                    code: code("SUP", i, 6),
                    subject: pick([
                        "Cannot log in", "Missing invoice", "Feature request: CSV export",
                        "Slow report loading", "Billing question", "Integration webhook failing",
                        "Password reset not working", "Exports truncated", "API 429 errors",
                        "Permission denied on dashboard", "Mobile app crash", "Data import stuck",
                    ], i),
                    requester: personName(i),
                    requesterEmail: `user+${i}@example.com`,
                    customer: pick(["Acme Corp", "Globex", "Initech", "Hooli", "Pied Piper", "Dunder Mifflin"], i),
                    assignee: pick(AGENTS, i),
                    team: pick(["tier-1", "tier-1", "tier-2", "engineering", "billing", "success"], i),
                    channel: pick(CHANNELS.map((c) => c.value), i),
                    category: pick(CATEGORIES.map((c) => c.value), i),
                    priority: pick(["low", "normal", "normal", "high", "urgent"], i),
                    status: pick(["open", "in_progress", "resolved", "closed"], i),
                    slaPolicy: pick(["Standard", "Premium", "Enterprise"], i),
                    slaDueAt: new Date(c + slaHrs * 3_600_000).toISOString(),
                    slaBreached: !isResolved && (Date.now() - c) / 3_600_000 > slaHrs,
                    slaAtRisk: !isResolved && (Date.now() - c) / 3_600_000 > slaHrs * 0.75 && (Date.now() - c) / 3_600_000 <= slaHrs,
                    createdAt: created,
                    firstResponseAt: new Date(c + firstResponseMin * 60_000).toISOString(),
                    resolvedAt: isResolved ? new Date(c + resolvedHrs * 3_600_000).toISOString() : "",
                    updatedAt: daysAgo(i * 0.5),
                    messagesCount: 1 + (i % 12),
                    tags: i % 5 === 0 ? ["vip"] : i % 7 === 0 ? ["escalated"] : [],
                    description: "",
                    resolutionNotes: isResolved ? "Issue resolved after rolling back recent deployment." : "",
                };
            },
        },
        {
            id: "sla-policy",
            singular: "SLA Policy",
            plural: "SLA Policies",
            icon: "ShieldCheck",
            path: "/support/sla-policies",
            fields: [
                { name: "name", kind: "text", required: true, sortable: true },
                { name: "description", kind: "text" },
                { name: "firstResponseHours", label: "First response (h)", kind: "number", align: "right" },
                { name: "resolutionHours", label: "Resolution (h)", kind: "number", align: "right" },
                { name: "priority", kind: "enum", options: PRIORITY },
                { name: "businessHoursOnly", kind: "boolean" },
                { name: "active", kind: "boolean" },
            ],
            seedCount: 6,
            seed: (i) => ({
                name: pick(["Standard", "Premium", "Enterprise", "Dev-Tier", "Trial", "Internal"], i),
                description: pick([
                    "Default tier — small customers",
                    "Premium plan SLA",
                    "Top-tier enterprise SLA",
                    "Dev-plan SLA",
                    "Trial accounts SLA",
                    "Internal teams SLA",
                ], i),
                firstResponseHours: pick([24, 4, 1, 48, 72, 8], i),
                resolutionHours: pick([72, 24, 8, 120, 168, 48], i),
                priority: pick(["normal", "high", "urgent", "low", "low", "normal"], i),
                businessHoursOnly: i % 2 === 0,
                active: true,
            }),
        },
        {
            id: "service-contract",
            singular: "Service Contract",
            plural: "Service Contracts",
            icon: "FileSignature",
            path: "/support/service-contracts",
            displayField: "code",
            fields: [
                { name: "code", kind: "text", required: true, sortable: true, width: 130 },
                { name: "customer", kind: "text", required: true, sortable: true },
                { name: "slaPolicy", kind: "text" },
                { name: "startAt", kind: "date", sortable: true },
                { name: "endAt", kind: "date", sortable: true },
                { name: "renewalAt", kind: "date" },
                { name: "status", kind: "enum", required: true, options: [
                        { value: "active", label: "Active", intent: "success" },
                        { value: "expiring-soon", label: "Expiring soon", intent: "warning" },
                        { value: "expired", label: "Expired", intent: "danger" },
                        { value: "renewed", label: "Renewed", intent: "info" },
                    ] },
                { name: "valueAnnual", label: "Annual value", kind: "currency", align: "right" },
                { name: "owner", kind: "text" },
            ],
            seedCount: 14,
            seed: (i) => ({
                code: code("SC", i, 6),
                customer: pick(["Acme Corp", "Globex", "Initech", "Hooli", "Pied Piper"], i),
                slaPolicy: pick(["Standard", "Premium", "Enterprise"], i),
                startAt: daysAgo(365 - i * 20),
                endAt: daysFromNow(365 - i * 20),
                renewalAt: daysFromNow(335 - i * 20),
                status: pick(["active", "active", "active", "expiring-soon", "renewed"], i),
                valueAnnual: 10_000 + ((i * 7537) % 200_000),
                owner: pick(AGENTS, i),
            }),
        },
        {
            id: "warranty-claim",
            singular: "Warranty Claim",
            plural: "Warranty Claims",
            icon: "Shield",
            path: "/support/warranty-claims",
            displayField: "code",
            defaultSort: { field: "claimedAt", dir: "desc" },
            fields: [
                { name: "code", kind: "text", required: true, sortable: true, width: 130 },
                { name: "product", kind: "text", required: true, sortable: true },
                { name: "serial", kind: "text", width: 140 },
                { name: "customer", kind: "text", sortable: true },
                { name: "claimedAt", kind: "date", sortable: true },
                { name: "reportedIssue", kind: "text" },
                { name: "repairCost", kind: "currency", align: "right" },
                { name: "status", kind: "enum", required: true, sortable: true, options: [
                        { value: "pending", label: "Pending", intent: "warning" },
                        { value: "in-progress", label: "In progress", intent: "info" },
                        { value: "resolved", label: "Resolved", intent: "success" },
                        { value: "rejected", label: "Rejected", intent: "danger" },
                    ] },
            ],
            seedCount: 16,
            seed: (i) => ({
                code: code("WC", i, 5),
                product: pick(["Widget A", "Gizmo B", "Part C", "Motor O", "Sensor P"], i),
                serial: `SN-${String(10000 + i * 37).slice(-5)}`,
                customer: pick(["Acme Corp", "Globex", "Initech", "Hooli"], i),
                claimedAt: daysAgo(i * 5),
                reportedIssue: pick(["Stopped working", "Noisy", "Intermittent failures", "Overheating", "Physical damage"], i),
                repairCost: (i * 37) % 600 + 30,
                status: pick(["resolved", "in-progress", "pending", "resolved", "rejected"], i),
            }),
        },
        {
            id: "kb-article",
            singular: "KB Article",
            plural: "KB Articles",
            icon: "BookOpen",
            path: "/support/articles",
            displayField: "title",
            defaultSort: { field: "updatedAt", dir: "desc" },
            fields: [
                { name: "title", kind: "text", required: true, sortable: true },
                { name: "slug", kind: "text", width: 180 },
                { name: "category", kind: "enum", options: [
                        { value: "getting-started", label: "Getting started" },
                        { value: "troubleshooting", label: "Troubleshooting" },
                        { value: "api", label: "API" },
                        { value: "billing", label: "Billing" },
                        { value: "security", label: "Security" },
                    ], sortable: true },
                { name: "author", kind: "text" },
                { name: "views", kind: "number", align: "right", sortable: true },
                { name: "helpfulYes", label: "Helpful Yes", kind: "number", align: "right", width: 110 },
                { name: "helpfulNo", label: "Helpful No", kind: "number", align: "right", width: 110 },
                { name: "status", kind: "enum", required: true, options: [
                        { value: "draft", label: "Draft", intent: "neutral" },
                        { value: "published", label: "Published", intent: "success" },
                        { value: "archived", label: "Archived", intent: "neutral" },
                    ], sortable: true },
                { name: "updatedAt", kind: "datetime", sortable: true },
                { name: "body", kind: "textarea", formSection: "Content" },
            ],
            seedCount: 22,
            seed: (i) => ({
                title: pick([
                    "Resetting your password", "Setting up SSO", "Importing CSV files",
                    "Understanding invoices", "API rate limits", "Two-factor authentication",
                    "Migrating from v1", "Webhook event reference", "Data retention policy",
                    "Exporting your data",
                ], i),
                slug: pick([
                    "reset-password", "sso-setup", "import-csv", "understanding-invoices",
                    "rate-limits", "2fa", "migrate-v1", "webhook-reference", "data-retention", "export-data",
                ], i),
                category: pick(["getting-started", "troubleshooting", "api", "billing", "security"], i),
                author: pick(AGENTS, i),
                views: 100 + ((i * 317) % 10_000),
                helpfulYes: 50 + (i * 13) % 400,
                helpfulNo: 5 + (i * 7) % 50,
                status: pick(["published", "published", "published", "draft", "archived"], i),
                updatedAt: daysAgo(i * 3),
                body: "Full article body…",
            }),
        },
        {
            id: "canned-response",
            singular: "Canned Response",
            plural: "Canned Responses",
            icon: "MessageSquareText",
            path: "/support/canned-responses",
            fields: [
                { name: "name", kind: "text", required: true, sortable: true },
                { name: "shortcut", kind: "text", width: 120 },
                { name: "category", kind: "enum", options: CATEGORIES },
                { name: "usageCount", label: "Usage", kind: "number", align: "right" },
                { name: "active", kind: "boolean" },
                { name: "body", kind: "textarea", formSection: "Content" },
            ],
            seedCount: 12,
            seed: (i) => ({
                name: pick([
                    "Ack — looking into it", "Ack — escalating", "Request more info",
                    "Request screenshot", "Send API docs link", "Send billing portal",
                    "Close ticket — resolved", "Close ticket — dupe", "Ask for CSAT",
                    "Apology for delay", "Scheduled maintenance reply", "Follow-up after 7d",
                ], i),
                shortcut: `/${pick(["ack", "esc", "info", "ss", "api", "bill", "res", "dupe", "csat", "apo", "maint", "fu7"], i)}`,
                category: pick(CATEGORIES.map((c) => c.value), i),
                usageCount: 20 + ((i * 29) % 500),
                active: i !== 11,
                body: "Hi {{requester.firstName}}, thanks for reaching out…",
            }),
        },
        {
            id: "csat-response",
            singular: "CSAT Response",
            plural: "CSAT Responses",
            icon: "Smile",
            path: "/support/csat",
            displayField: "id",
            defaultSort: { field: "submittedAt", dir: "desc" },
            fields: [
                { name: "ticketCode", label: "Ticket", kind: "text", required: true, sortable: true, width: 120 },
                { name: "customer", kind: "text", sortable: true },
                { name: "agent", kind: "text", sortable: true },
                { name: "score", kind: "number", align: "right", sortable: true, width: 90 },
                { name: "sentiment", kind: "enum", options: [
                        { value: "positive", label: "Positive", intent: "success" },
                        { value: "neutral", label: "Neutral", intent: "info" },
                        { value: "negative", label: "Negative", intent: "danger" },
                    ] },
                { name: "submittedAt", kind: "datetime", sortable: true },
                { name: "comment", kind: "textarea", formSection: "Comment" },
            ],
            seedCount: 40,
            seed: (i) => {
                const score = pick([5, 5, 5, 4, 4, 3, 2, 1], i);
                return {
                    ticketCode: code("SUP", i % 50, 6),
                    customer: pick(["Acme Corp", "Globex", "Initech", "Hooli", "Pied Piper"], i),
                    agent: pick(AGENTS, i),
                    score,
                    sentiment: score >= 4 ? "positive" : score === 3 ? "neutral" : "negative",
                    submittedAt: daysAgo(i * 0.5),
                    comment: pick([
                        "Resolved quickly, thanks!", "Very helpful agent.", "Took longer than expected.",
                        "Great support as always.", "Response was confusing.", "No update for days.",
                    ], i),
                };
            },
        },
        {
            id: "escalation",
            singular: "Escalation",
            plural: "Escalations",
            icon: "AlertOctagon",
            path: "/support/escalations",
            displayField: "code",
            defaultSort: { field: "escalatedAt", dir: "desc" },
            fields: [
                { name: "code", kind: "text", required: true, sortable: true, width: 120 },
                { name: "ticketCode", label: "Ticket", kind: "text", required: true, width: 120 },
                { name: "fromTeam", kind: "text", width: 140 },
                { name: "toTeam", kind: "text", width: 140 },
                { name: "reason", kind: "enum", options: [
                        { value: "sla-at-risk", label: "SLA at risk" },
                        { value: "vip", label: "VIP customer" },
                        { value: "technical", label: "Technical depth" },
                        { value: "billing", label: "Billing dispute" },
                        { value: "legal", label: "Legal" },
                    ] },
                { name: "escalatedBy", kind: "text" },
                { name: "escalatedAt", kind: "datetime", sortable: true },
                { name: "resolvedAt", kind: "datetime" },
                { name: "status", kind: "enum", required: true, options: [
                        { value: "pending", label: "Pending", intent: "warning" },
                        { value: "in-progress", label: "In progress", intent: "info" },
                        { value: "resolved", label: "Resolved", intent: "success" },
                    ] },
            ],
            seedCount: 14,
            seed: (i) => ({
                code: code("ESC", i, 5),
                ticketCode: code("SUP", i % 50, 6),
                fromTeam: pick(["tier-1", "tier-2", "billing"], i),
                toTeam: pick(["tier-2", "engineering", "success"], i),
                reason: pick(["sla-at-risk", "vip", "technical", "billing", "legal"], i),
                escalatedBy: pick(AGENTS, i),
                escalatedAt: daysAgo(i * 0.8),
                resolvedAt: i % 2 === 0 ? daysAgo(i * 0.3) : "",
                status: pick(["resolved", "resolved", "in-progress", "pending"], i),
            }),
        },
    ],
    extraNav: [
        { id: "support.control-room.nav", label: "Support Service Control Room", icon: "LayoutDashboard", path: "/support/control-room", view: "support-service.control-room.view", order: 0 },
        { id: "support.reports.nav", label: "Reports", icon: "BarChart3", path: "/support/reports", view: "support-service.reports.view" },
        { id: "support.board.nav", label: "Board", icon: "LayoutGrid", path: "/support/board", view: "support-service.kanban.view" },
        { id: "support.analytics.nav", label: "Analytics", icon: "LineChart", path: "/support/analytics", view: "support-service.analytics.view" },
    ],
    extraViews: [
        supportControlRoomView,
        supportReportsIndexView,
        supportReportsDetailView,
        supportKanbanView,
        supportAnalyticsView,
    ],
    commands: [
        { id: "support.go.control-room", label: "Support: Control Room", icon: "LayoutDashboard", run: () => { window.location.hash = "/support/control-room"; } },
        { id: "support.go.reports", label: "Support: Reports", icon: "BarChart3", run: () => { window.location.hash = "/support/reports"; } },
        { id: "support.go.board", label: "Support: Board", icon: "LayoutGrid", run: () => { window.location.hash = "/support/board"; } },
        { id: "support.new-ticket", label: "New ticket", icon: "Plus", run: () => { window.location.hash = "/support/tickets/new"; } },
        { id: "support.new-article", label: "New KB article", icon: "BookOpen", run: () => { window.location.hash = "/support/articles/new"; } },
        { id: "support.new-canned", label: "New canned response", icon: "MessageSquareText", run: () => { window.location.hash = "/support/canned-responses/new"; } },
    ],
});
