DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_migrator') THEN CREATE ROLE app_migrator NOLOGIN; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_runtime') THEN CREATE ROLE app_runtime NOLOGIN; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_jobs') THEN CREATE ROLE app_jobs NOLOGIN; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_readonly') THEN CREATE ROLE app_readonly NOLOGIN; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'backup_restore') THEN CREATE ROLE backup_restore NOLOGIN; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'plugin_template_runtime') THEN CREATE ROLE plugin_template_runtime NOLOGIN; END IF; END $$;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
CREATE SCHEMA IF NOT EXISTS core;
REVOKE ALL ON SCHEMA core FROM PUBLIC;
GRANT USAGE ON SCHEMA core TO app_migrator;
CREATE SCHEMA IF NOT EXISTS identity;
REVOKE ALL ON SCHEMA identity FROM PUBLIC;
GRANT USAGE ON SCHEMA identity TO app_migrator;
CREATE SCHEMA IF NOT EXISTS crm;
REVOKE ALL ON SCHEMA crm FROM PUBLIC;
GRANT USAGE ON SCHEMA crm TO app_migrator;
CREATE SCHEMA IF NOT EXISTS finance;
REVOKE ALL ON SCHEMA finance FROM PUBLIC;
GRANT USAGE ON SCHEMA finance TO app_migrator;
CREATE SCHEMA IF NOT EXISTS inventory;
REVOKE ALL ON SCHEMA inventory FROM PUBLIC;
GRANT USAGE ON SCHEMA inventory TO app_migrator;
CREATE SCHEMA IF NOT EXISTS content;
REVOKE ALL ON SCHEMA content FROM PUBLIC;
GRANT USAGE ON SCHEMA content TO app_migrator;
CREATE SCHEMA IF NOT EXISTS support;
REVOKE ALL ON SCHEMA support FROM PUBLIC;
GRANT USAGE ON SCHEMA support TO app_migrator;
CREATE SCHEMA IF NOT EXISTS learning;
REVOKE ALL ON SCHEMA learning FROM PUBLIC;
GRANT USAGE ON SCHEMA learning TO app_migrator;
CREATE SCHEMA IF NOT EXISTS streaming;
REVOKE ALL ON SCHEMA streaming FROM PUBLIC;
GRANT USAGE ON SCHEMA streaming TO app_migrator;
CREATE SCHEMA IF NOT EXISTS booking;
REVOKE ALL ON SCHEMA booking FROM PUBLIC;
GRANT USAGE ON SCHEMA booking TO app_migrator;
CREATE SCHEMA IF NOT EXISTS audit;
REVOKE ALL ON SCHEMA audit FROM PUBLIC;
GRANT USAGE ON SCHEMA audit TO app_migrator;
CREATE SCHEMA IF NOT EXISTS api;
REVOKE ALL ON SCHEMA api FROM PUBLIC;
GRANT USAGE ON SCHEMA api TO app_migrator;
COMMENT ON SCHEMA api IS 'Curated read models and audited procedures for isolated runtimes.';
GRANT USAGE ON SCHEMA core TO app_runtime, app_jobs, app_readonly;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA core TO app_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA core TO app_jobs;
GRANT SELECT ON ALL TABLES IN SCHEMA core TO app_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_jobs;
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT SELECT ON TABLES TO app_readonly;
GRANT USAGE ON SCHEMA identity TO app_runtime, app_jobs, app_readonly;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA identity TO app_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA identity TO app_jobs;
GRANT SELECT ON ALL TABLES IN SCHEMA identity TO app_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA identity GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA identity GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_jobs;
ALTER DEFAULT PRIVILEGES IN SCHEMA identity GRANT SELECT ON TABLES TO app_readonly;
GRANT USAGE ON SCHEMA crm TO app_runtime, app_jobs, app_readonly;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA crm TO app_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA crm TO app_jobs;
GRANT SELECT ON ALL TABLES IN SCHEMA crm TO app_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA crm GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA crm GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_jobs;
ALTER DEFAULT PRIVILEGES IN SCHEMA crm GRANT SELECT ON TABLES TO app_readonly;
GRANT USAGE ON SCHEMA finance TO app_runtime, app_jobs, app_readonly;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA finance TO app_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA finance TO app_jobs;
GRANT SELECT ON ALL TABLES IN SCHEMA finance TO app_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA finance GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA finance GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_jobs;
ALTER DEFAULT PRIVILEGES IN SCHEMA finance GRANT SELECT ON TABLES TO app_readonly;
GRANT USAGE ON SCHEMA inventory TO app_runtime, app_jobs, app_readonly;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA inventory TO app_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA inventory TO app_jobs;
GRANT SELECT ON ALL TABLES IN SCHEMA inventory TO app_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA inventory GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA inventory GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_jobs;
ALTER DEFAULT PRIVILEGES IN SCHEMA inventory GRANT SELECT ON TABLES TO app_readonly;
GRANT USAGE ON SCHEMA content TO app_runtime, app_jobs, app_readonly;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA content TO app_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA content TO app_jobs;
GRANT SELECT ON ALL TABLES IN SCHEMA content TO app_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA content GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA content GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_jobs;
ALTER DEFAULT PRIVILEGES IN SCHEMA content GRANT SELECT ON TABLES TO app_readonly;
GRANT USAGE ON SCHEMA support TO app_runtime, app_jobs, app_readonly;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA support TO app_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA support TO app_jobs;
GRANT SELECT ON ALL TABLES IN SCHEMA support TO app_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA support GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA support GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_jobs;
ALTER DEFAULT PRIVILEGES IN SCHEMA support GRANT SELECT ON TABLES TO app_readonly;
GRANT USAGE ON SCHEMA learning TO app_runtime, app_jobs, app_readonly;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA learning TO app_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA learning TO app_jobs;
GRANT SELECT ON ALL TABLES IN SCHEMA learning TO app_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA learning GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA learning GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_jobs;
ALTER DEFAULT PRIVILEGES IN SCHEMA learning GRANT SELECT ON TABLES TO app_readonly;
GRANT USAGE ON SCHEMA streaming TO app_runtime, app_jobs, app_readonly;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA streaming TO app_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA streaming TO app_jobs;
GRANT SELECT ON ALL TABLES IN SCHEMA streaming TO app_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA streaming GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA streaming GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_jobs;
ALTER DEFAULT PRIVILEGES IN SCHEMA streaming GRANT SELECT ON TABLES TO app_readonly;
GRANT USAGE ON SCHEMA booking TO app_runtime, app_jobs, app_readonly;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA booking TO app_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA booking TO app_jobs;
GRANT SELECT ON ALL TABLES IN SCHEMA booking TO app_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA booking GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA booking GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_jobs;
ALTER DEFAULT PRIVILEGES IN SCHEMA booking GRANT SELECT ON TABLES TO app_readonly;
GRANT USAGE ON SCHEMA audit TO app_runtime, app_jobs, app_readonly;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA audit TO app_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA audit TO app_jobs;
GRANT SELECT ON ALL TABLES IN SCHEMA audit TO app_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_jobs;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT SELECT ON TABLES TO app_readonly;
GRANT USAGE ON SCHEMA api TO app_runtime, app_jobs, app_readonly;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA api TO app_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA api TO app_jobs;
GRANT SELECT ON ALL TABLES IN SCHEMA api TO app_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA api GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA api GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_jobs;
ALTER DEFAULT PRIVILEGES IN SCHEMA api GRANT SELECT ON TABLES TO app_readonly;
CREATE OR REPLACE FUNCTION core.set_request_context(p_tenant_id text, p_actor_id text DEFAULT NULL, p_user_id text DEFAULT NULL, p_request_id text DEFAULT NULL) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = core, pg_catalog AS $$ BEGIN PERFORM set_config('app.tenant_id', p_tenant_id, true); IF p_actor_id IS NOT NULL THEN PERFORM set_config('app.actor_id', p_actor_id, true); END IF; IF p_user_id IS NOT NULL THEN PERFORM set_config('app.user_id', p_user_id, true); END IF; IF p_request_id IS NOT NULL THEN PERFORM set_config('app.request_id', p_request_id, true); END IF; END; $$;
REVOKE ALL ON FUNCTION core.set_request_context(text, text, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION core.set_request_context(text, text, text, text) TO app_runtime, app_jobs;
ALTER TABLE booking.reservations ENABLE ROW LEVEL SECURITY;
CREATE POLICY booking_reservations_tenant_isolation ON booking.reservations USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE booking.reservations FORCE ROW LEVEL SECURITY;
ALTER TABLE crm.contacts ENABLE ROW LEVEL SECURITY;
CREATE POLICY crm_contacts_tenant_isolation ON crm.contacts USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE crm.contacts FORCE ROW LEVEL SECURITY;
ALTER TABLE identity.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY identity_users_tenant_isolation ON identity.users USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE identity.users FORCE ROW LEVEL SECURITY;
ALTER TABLE marketing.campaigns ENABLE ROW LEVEL SECURITY;
CREATE POLICY marketing_campaigns_tenant_isolation ON marketing.campaigns USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE marketing.campaigns FORCE ROW LEVEL SECURITY;
ALTER TABLE sales.opportunities ENABLE ROW LEVEL SECURITY;
CREATE POLICY sales_opportunities_tenant_isolation ON sales.opportunities USING (tenant_id = current_setting('app.tenant_id', true));
ALTER TABLE sales.opportunities FORCE ROW LEVEL SECURITY;
CREATE OR REPLACE VIEW api.booking_reservations_summary WITH (security_barrier=true, security_invoker=false) AS SELECT "id", "tenant_id", "resource_class", "resource_id", "slot_start", "slot_end", "confirmation_status" FROM booking.reservations;
CREATE OR REPLACE VIEW api.crm_contacts_summary WITH (security_barrier=true, security_invoker=false) AS SELECT "id", "tenant_id", "email", "status" FROM crm.contacts WHERE status <> 'inactive';
CREATE OR REPLACE VIEW api.marketing_campaigns_summary WITH (security_barrier=true, security_invoker=false) AS SELECT "id", "tenant_id", "segment_key", "status", "launch_at" FROM marketing.campaigns;
CREATE OR REPLACE VIEW api.sales_opportunities_summary WITH (security_barrier=true, security_invoker=false) AS SELECT "id", "tenant_id", "stage", "amount_cents", "currency" FROM sales.opportunities WHERE stage <> 'closed-lost';
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'plugin_cloudflare_gateway_adapter_runtime') THEN CREATE ROLE plugin_cloudflare_gateway_adapter_runtime NOLOGIN; END IF; END $$;
GRANT USAGE ON SCHEMA api TO plugin_cloudflare_gateway_adapter_runtime;
GRANT SELECT ON api.booking_reservations_summary TO plugin_cloudflare_gateway_adapter_runtime;
GRANT SELECT ON api.crm_contacts_summary TO plugin_cloudflare_gateway_adapter_runtime;
GRANT SELECT ON api.marketing_campaigns_summary TO plugin_cloudflare_gateway_adapter_runtime;
GRANT SELECT ON api.sales_opportunities_summary TO plugin_cloudflare_gateway_adapter_runtime;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'plugin_google_workspace_import_runtime') THEN CREATE ROLE plugin_google_workspace_import_runtime NOLOGIN; END IF; END $$;
GRANT USAGE ON SCHEMA api TO plugin_google_workspace_import_runtime;
GRANT SELECT ON api.booking_reservations_summary TO plugin_google_workspace_import_runtime;
GRANT SELECT ON api.crm_contacts_summary TO plugin_google_workspace_import_runtime;
GRANT SELECT ON api.marketing_campaigns_summary TO plugin_google_workspace_import_runtime;
GRANT SELECT ON api.sales_opportunities_summary TO plugin_google_workspace_import_runtime;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'plugin_oidc_sso_adapter_runtime') THEN CREATE ROLE plugin_oidc_sso_adapter_runtime NOLOGIN; END IF; END $$;
GRANT USAGE ON SCHEMA api TO plugin_oidc_sso_adapter_runtime;
GRANT SELECT ON api.booking_reservations_summary TO plugin_oidc_sso_adapter_runtime;
GRANT SELECT ON api.crm_contacts_summary TO plugin_oidc_sso_adapter_runtime;
GRANT SELECT ON api.marketing_campaigns_summary TO plugin_oidc_sso_adapter_runtime;
GRANT SELECT ON api.sales_opportunities_summary TO plugin_oidc_sso_adapter_runtime;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'plugin_openai_adapter_runtime') THEN CREATE ROLE plugin_openai_adapter_runtime NOLOGIN; END IF; END $$;
GRANT USAGE ON SCHEMA api TO plugin_openai_adapter_runtime;
GRANT SELECT ON api.booking_reservations_summary TO plugin_openai_adapter_runtime;
GRANT SELECT ON api.crm_contacts_summary TO plugin_openai_adapter_runtime;
GRANT SELECT ON api.marketing_campaigns_summary TO plugin_openai_adapter_runtime;
GRANT SELECT ON api.sales_opportunities_summary TO plugin_openai_adapter_runtime;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'plugin_s3_storage_adapter_runtime') THEN CREATE ROLE plugin_s3_storage_adapter_runtime NOLOGIN; END IF; END $$;
GRANT USAGE ON SCHEMA api TO plugin_s3_storage_adapter_runtime;
GRANT SELECT ON api.booking_reservations_summary TO plugin_s3_storage_adapter_runtime;
GRANT SELECT ON api.crm_contacts_summary TO plugin_s3_storage_adapter_runtime;
GRANT SELECT ON api.marketing_campaigns_summary TO plugin_s3_storage_adapter_runtime;
GRANT SELECT ON api.sales_opportunities_summary TO plugin_s3_storage_adapter_runtime;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'plugin_salesforce_import_runtime') THEN CREATE ROLE plugin_salesforce_import_runtime NOLOGIN; END IF; END $$;
GRANT USAGE ON SCHEMA api TO plugin_salesforce_import_runtime;
GRANT SELECT ON api.booking_reservations_summary TO plugin_salesforce_import_runtime;
GRANT SELECT ON api.crm_contacts_summary TO plugin_salesforce_import_runtime;
GRANT SELECT ON api.marketing_campaigns_summary TO plugin_salesforce_import_runtime;
GRANT SELECT ON api.sales_opportunities_summary TO plugin_salesforce_import_runtime;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'plugin_sendgrid_adapter_runtime') THEN CREATE ROLE plugin_sendgrid_adapter_runtime NOLOGIN; END IF; END $$;
GRANT USAGE ON SCHEMA api TO plugin_sendgrid_adapter_runtime;
GRANT SELECT ON api.booking_reservations_summary TO plugin_sendgrid_adapter_runtime;
GRANT SELECT ON api.crm_contacts_summary TO plugin_sendgrid_adapter_runtime;
GRANT SELECT ON api.marketing_campaigns_summary TO plugin_sendgrid_adapter_runtime;
GRANT SELECT ON api.sales_opportunities_summary TO plugin_sendgrid_adapter_runtime;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'plugin_shopify_import_runtime') THEN CREATE ROLE plugin_shopify_import_runtime NOLOGIN; END IF; END $$;
GRANT USAGE ON SCHEMA api TO plugin_shopify_import_runtime;
GRANT SELECT ON api.booking_reservations_summary TO plugin_shopify_import_runtime;
GRANT SELECT ON api.crm_contacts_summary TO plugin_shopify_import_runtime;
GRANT SELECT ON api.marketing_campaigns_summary TO plugin_shopify_import_runtime;
GRANT SELECT ON api.sales_opportunities_summary TO plugin_shopify_import_runtime;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'plugin_slack_adapter_runtime') THEN CREATE ROLE plugin_slack_adapter_runtime NOLOGIN; END IF; END $$;
GRANT USAGE ON SCHEMA api TO plugin_slack_adapter_runtime;
GRANT SELECT ON api.booking_reservations_summary TO plugin_slack_adapter_runtime;
GRANT SELECT ON api.crm_contacts_summary TO plugin_slack_adapter_runtime;
GRANT SELECT ON api.marketing_campaigns_summary TO plugin_slack_adapter_runtime;
GRANT SELECT ON api.sales_opportunities_summary TO plugin_slack_adapter_runtime;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'plugin_stripe_adapter_runtime') THEN CREATE ROLE plugin_stripe_adapter_runtime NOLOGIN; END IF; END $$;
GRANT USAGE ON SCHEMA api TO plugin_stripe_adapter_runtime;
GRANT SELECT ON api.booking_reservations_summary TO plugin_stripe_adapter_runtime;
GRANT SELECT ON api.crm_contacts_summary TO plugin_stripe_adapter_runtime;
GRANT SELECT ON api.marketing_campaigns_summary TO plugin_stripe_adapter_runtime;
GRANT SELECT ON api.sales_opportunities_summary TO plugin_stripe_adapter_runtime;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'plugin_warehouse_export_adapter_runtime') THEN CREATE ROLE plugin_warehouse_export_adapter_runtime NOLOGIN; END IF; END $$;
GRANT USAGE ON SCHEMA api TO plugin_warehouse_export_adapter_runtime;
GRANT SELECT ON api.booking_reservations_summary TO plugin_warehouse_export_adapter_runtime;
GRANT SELECT ON api.crm_contacts_summary TO plugin_warehouse_export_adapter_runtime;
GRANT SELECT ON api.marketing_campaigns_summary TO plugin_warehouse_export_adapter_runtime;
GRANT SELECT ON api.sales_opportunities_summary TO plugin_warehouse_export_adapter_runtime;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'plugin_wordpress_import_runtime') THEN CREATE ROLE plugin_wordpress_import_runtime NOLOGIN; END IF; END $$;
GRANT USAGE ON SCHEMA api TO plugin_wordpress_import_runtime;
GRANT SELECT ON api.booking_reservations_summary TO plugin_wordpress_import_runtime;
GRANT SELECT ON api.crm_contacts_summary TO plugin_wordpress_import_runtime;
GRANT SELECT ON api.marketing_campaigns_summary TO plugin_wordpress_import_runtime;
GRANT SELECT ON api.sales_opportunities_summary TO plugin_wordpress_import_runtime;
GRANT USAGE ON SCHEMA api TO plugin_cloudflare_gateway_adapter_runtime;
GRANT SELECT ON api.crm_contacts_summary TO plugin_cloudflare_gateway_adapter_runtime;
GRANT SELECT ON api.sales_opportunities_summary TO plugin_cloudflare_gateway_adapter_runtime;
GRANT SELECT ON api.marketing_campaigns_summary TO plugin_cloudflare_gateway_adapter_runtime;
GRANT SELECT ON api.booking_reservations_summary TO plugin_cloudflare_gateway_adapter_runtime;
GRANT USAGE ON SCHEMA api TO plugin_google_workspace_import_runtime;
GRANT SELECT ON api.crm_contacts_summary TO plugin_google_workspace_import_runtime;
GRANT SELECT ON api.sales_opportunities_summary TO plugin_google_workspace_import_runtime;
GRANT SELECT ON api.marketing_campaigns_summary TO plugin_google_workspace_import_runtime;
GRANT SELECT ON api.booking_reservations_summary TO plugin_google_workspace_import_runtime;
GRANT USAGE ON SCHEMA api TO plugin_oidc_sso_adapter_runtime;
GRANT SELECT ON api.crm_contacts_summary TO plugin_oidc_sso_adapter_runtime;
GRANT SELECT ON api.sales_opportunities_summary TO plugin_oidc_sso_adapter_runtime;
GRANT SELECT ON api.marketing_campaigns_summary TO plugin_oidc_sso_adapter_runtime;
GRANT SELECT ON api.booking_reservations_summary TO plugin_oidc_sso_adapter_runtime;
GRANT USAGE ON SCHEMA api TO plugin_openai_adapter_runtime;
GRANT SELECT ON api.crm_contacts_summary TO plugin_openai_adapter_runtime;
GRANT SELECT ON api.sales_opportunities_summary TO plugin_openai_adapter_runtime;
GRANT SELECT ON api.marketing_campaigns_summary TO plugin_openai_adapter_runtime;
GRANT SELECT ON api.booking_reservations_summary TO plugin_openai_adapter_runtime;
GRANT USAGE ON SCHEMA api TO plugin_s3_storage_adapter_runtime;
GRANT SELECT ON api.crm_contacts_summary TO plugin_s3_storage_adapter_runtime;
GRANT SELECT ON api.sales_opportunities_summary TO plugin_s3_storage_adapter_runtime;
GRANT SELECT ON api.marketing_campaigns_summary TO plugin_s3_storage_adapter_runtime;
GRANT SELECT ON api.booking_reservations_summary TO plugin_s3_storage_adapter_runtime;
GRANT USAGE ON SCHEMA api TO plugin_salesforce_import_runtime;
GRANT SELECT ON api.crm_contacts_summary TO plugin_salesforce_import_runtime;
GRANT SELECT ON api.sales_opportunities_summary TO plugin_salesforce_import_runtime;
GRANT SELECT ON api.marketing_campaigns_summary TO plugin_salesforce_import_runtime;
GRANT SELECT ON api.booking_reservations_summary TO plugin_salesforce_import_runtime;
GRANT USAGE ON SCHEMA api TO plugin_sendgrid_adapter_runtime;
GRANT SELECT ON api.crm_contacts_summary TO plugin_sendgrid_adapter_runtime;
GRANT SELECT ON api.sales_opportunities_summary TO plugin_sendgrid_adapter_runtime;
GRANT SELECT ON api.marketing_campaigns_summary TO plugin_sendgrid_adapter_runtime;
GRANT SELECT ON api.booking_reservations_summary TO plugin_sendgrid_adapter_runtime;
GRANT USAGE ON SCHEMA api TO plugin_shopify_import_runtime;
GRANT SELECT ON api.crm_contacts_summary TO plugin_shopify_import_runtime;
GRANT SELECT ON api.sales_opportunities_summary TO plugin_shopify_import_runtime;
GRANT SELECT ON api.marketing_campaigns_summary TO plugin_shopify_import_runtime;
GRANT SELECT ON api.booking_reservations_summary TO plugin_shopify_import_runtime;
GRANT USAGE ON SCHEMA api TO plugin_slack_adapter_runtime;
GRANT SELECT ON api.crm_contacts_summary TO plugin_slack_adapter_runtime;
GRANT SELECT ON api.sales_opportunities_summary TO plugin_slack_adapter_runtime;
GRANT SELECT ON api.marketing_campaigns_summary TO plugin_slack_adapter_runtime;
GRANT SELECT ON api.booking_reservations_summary TO plugin_slack_adapter_runtime;
GRANT USAGE ON SCHEMA api TO plugin_stripe_adapter_runtime;
GRANT SELECT ON api.crm_contacts_summary TO plugin_stripe_adapter_runtime;
GRANT SELECT ON api.sales_opportunities_summary TO plugin_stripe_adapter_runtime;
GRANT SELECT ON api.marketing_campaigns_summary TO plugin_stripe_adapter_runtime;
GRANT SELECT ON api.booking_reservations_summary TO plugin_stripe_adapter_runtime;
GRANT USAGE ON SCHEMA api TO plugin_warehouse_export_adapter_runtime;
GRANT SELECT ON api.crm_contacts_summary TO plugin_warehouse_export_adapter_runtime;
GRANT SELECT ON api.sales_opportunities_summary TO plugin_warehouse_export_adapter_runtime;
GRANT SELECT ON api.marketing_campaigns_summary TO plugin_warehouse_export_adapter_runtime;
GRANT SELECT ON api.booking_reservations_summary TO plugin_warehouse_export_adapter_runtime;
GRANT USAGE ON SCHEMA api TO plugin_wordpress_import_runtime;
GRANT SELECT ON api.crm_contacts_summary TO plugin_wordpress_import_runtime;
GRANT SELECT ON api.sales_opportunities_summary TO plugin_wordpress_import_runtime;
GRANT SELECT ON api.marketing_campaigns_summary TO plugin_wordpress_import_runtime;
GRANT SELECT ON api.booking_reservations_summary TO plugin_wordpress_import_runtime;
